In [2]:
import logging
import os
import random
from pathlib import Path

import hydra
import matplotlib.pyplot as plt
import mlflow
import numpy as np
import pandas as pd
import pyvips
import torch
from lightning import seed_everything
from mlflow.tracking import MlflowClient
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)

from explainability.cams import grad_cam, grad_cam_pp, layer_cam
from explainability.cams.abstract import (
    HookedModule,
    modify_ReLU_inplace,
    reshape_for_clustering,
)
from explainability.precomputing import ClusteringManager
from prostate_cancer.data import DataModule
from prostate_cancer.prostate_cancer_model import ProstateCancerModel

In [3]:
def get_clustering_instance_fp(clustering_algorithm: str, num_clusters: int) -> Path:
    return Path(
        "/mnt/projects/explainability/XAICNNEmbeddings/PRECOMPUTED",
        "VGG16_Prostate",
        "global_clustering_instances",
        f"clustering_instance_test_global_{clustering_algorithm.lower()}_{num_clusters}clusters.npy",
    )

In [4]:
# Define clustering algorithms and cluster numbers to test
CLUSTERING_ALGORITHMS = ["NMF", "KMeans"]
CLUSTER_NUMBERS = [4, 6, 8]

In [5]:
# Load all clustering models
print("Loading all clustering models...")
clustering_models = {}

for clustering_algorithm in CLUSTERING_ALGORITHMS:
    for num_clusters in CLUSTER_NUMBERS:
        model_name = f"{clustering_algorithm}_{num_clusters}"
        print(f"Loading {model_name}...")

        clustering_instance_fp = get_clustering_instance_fp(
            clustering_algorithm, num_clusters
        )
        clustering_model = ClusteringManager.load_model(
            algorithm=clustering_algorithm,
            num_clusters=num_clusters,
            path=clustering_instance_fp,
        )

        clustering_models[model_name] = (
            clustering_model,
            num_clusters,
            clustering_algorithm,
        )

print(f"\nLoaded {len(clustering_models)} clustering models")
print(f"Models: {list(clustering_models.keys())}\n")

Loading all clustering models...
Loading NMF_4...
Loading NMF_6...
Loading NMF_8...
Loading KMeans_4...
Loading KMeans_6...
Loading KMeans_8...

Loaded 6 clustering models
Models: ['NMF_4', 'NMF_6', 'NMF_8', 'KMeans_4', 'KMeans_6', 'KMeans_8']

In [6]:
logging.basicConfig(level=logging.INFO)

# Set random seed for reproducibility
seed_everything(42, workers=True)
torch.set_float32_matmul_precision(precision="medium")

# Configuration overrides for prediction
overrides = ["experiment=predict/images/vgg16", "mode=predict"]

# Initialize Hydra configuration
with hydra.initialize(config_path="conf", version_base=None):
    config = hydra.compose(config_name="default", overrides=overrides)

print("Configuration loaded successfully!")
print(f"Mode: {config.mode}")
print(f"Checkpoint: {config.checkpoint}")
print(f"Batch size: {config.data.batch_size}")

# Instantiate data module and model
data: DataModule = hydra.utils.instantiate(
    config.data,
    _recursive_=False,  # to avoid instantiating all the datasets
    _target_=DataModule,
)

chkcpt_path = mlflow.artifacts.download_artifacts(config.checkpoint)
checkpoint = torch.load(chkcpt_path, map_location="cuda:0")

model: ProstateCancerModel = hydra.utils.instantiate(config.model)
model.load_state_dict(checkpoint["state_dict"], strict=True)

model = model.to("cuda:0")

print("Data module and model instantiated successfully!")

print(model)

Seed set to 42

Configuration loaded successfully!
Mode: predict
Checkpoint: mlflow-artifacts:/65/7b52930515c14710855962f8882fb4d3/artifacts/checkpoints/epoch=1-step=11620/checkpoint.ckpt
Batch size: 74

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Data module and model instantiated successfully!
ProstateCancerModel(
  (backbone): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (17): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (18): ReLU(inplace=True)
    (19): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (20): ReLU(inplace=True)
    (21): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (22): ReLU(inplace=True)
    (23): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (24): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (25): ReLU(inplace=True)
    (26): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (27): ReLU(inplace=True)
    (28): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (29): ReLU(inplace=True)
    (30): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (decode_head): BinaryClassifier(
    (global_pool): AdaptiveMaxPool2d(output_size=1)
    (dropout): Dropout(p=0.5, inplace=False)
    (proj): Linear(in_features=512, out_features=1, bias=True)
  )
  (criterion): BCEWithLogitsLoss()
  (train_metrics): MetricCollection(
    (AUC): BinaryAUROC()
    (accuracy): BinaryAccuracy()
    (negative_predictive_value): BinaryNegativePredictiveValue()
    (precision): BinaryPrecision()
    (recall): BinaryRecall()
    (specificity): BinarySpecificity(),
    prefix=train/
  )
  (val_metrics): MetricCollection(
    (AUC): BinaryAUROC()
    (accuracy): BinaryAccuracy()
    (negative_predictive_value): BinaryNegativePredictiveValue()
    (precision): BinaryPrecision()
    (recall): BinaryRecall()
    (specificity): BinarySpecificity(),
    prefix=validation/
  )
  (test_metrics): MetricCollection(
    (AUC): BinaryAUROC()
    (accuracy): BinaryAccuracy()
    (negative_predictive_value): BinaryNegativePredictiveValue()
    (precision): BinaryPrecision()
    (recall): BinaryRecall()
    (specificity): BinarySpecificity(),
    prefix=test/
  )
)

In [7]:
mlflow_client = MlflowClient(tracking_uri="http://mlflow.rationai-mlflow:5000/")
chkcpt_path = mlflow_client.download_artifacts(
    run_id="199141b76f90457fbf6183bd70a1e488", path="annotation_masks"
)

Downloading artifacts:   0%|          | 0/397 [00:00<?, ?it/s]

In [8]:
def get_carcinoma_mask(slide_id: str) -> np.ndarray | None:
    if not os.path.exists(f"{chkcpt_path}/carcinoma/{slide_id}.tiff"):
        return None

    carcinoma = pyvips.Image.new_from_file(f"{chkcpt_path}/carcinoma/{slide_id}.tiff")
    carcinoma_np = np.asarray(carcinoma) > 0

    # if exclude does not exists, it is empty
    if not os.path.exists(f"{chkcpt_path}/exclude/{slide_id}.tiff"):
        exclude_np = np.zeros_like(carcinoma_np)
    else:
        exclude = pyvips.Image.new_from_file(f"{chkcpt_path}/exclude/{slide_id}.tiff")
        exclude_np = np.asarray(exclude) > 0

    return carcinoma_np & ~exclude_np


def get_another_pathology_mask(slide_id: str) -> np.ndarray | None:
    if not os.path.exists(f"{chkcpt_path}/another_pathology/{slide_id}.tiff"):
        return None

    another_pathology = pyvips.Image.new_from_file(
        f"{chkcpt_path}/another_pathology/{slide_id}.tiff"
    )
    return np.asarray(another_pathology) > 0


def get_tile_mask(mask: np.ndarray | None, x: int, y: int) -> np.ndarray | None:
    if mask is None:
        return None

    yy, xx = x // 16, y // 16
    # get the 32x32 patch around th
    tile_mask = mask[xx : xx + 32, yy : yy + 32]

    if tile_mask.sum() == 0:
        return None

    return tile_mask

In [9]:
target_layer = "backbone.29"
hooked_model = HookedModule(model, layer_names=[target_layer])
modify_ReLU_inplace(hooked_model, inplace=False)

In [10]:
# Get one batch from validation dataset
data.batch_size = 32
data.setup("test")
dataloaders = data.test_dataloader()

Downloading artifacts:   0%|          | 0/2 [00:00<?, ?it/s]

In [11]:
carcinoma_masks = {}
another_pathology_masks = {}

for i in range(len(dataloaders)):
    slide_metadata = data.test.slides.iloc[i]
    extent_x = slide_metadata["extent_x"]
    extent_y = slide_metadata["extent_y"]
    slide_id = Path(slide_metadata["path"]).stem

    carcinoma_masks[slide_id] = get_carcinoma_mask(slide_id)
    another_pathology_masks[slide_id] = get_another_pathology_mask(slide_id)

INFO:pyvips:VIPS: threadpool completed with 3 workers
INFO:pyvips:VIPS: threadpool completed with 7 workers
INFO:pyvips:VIPS: threadpool completed with 7 workers
INFO:pyvips:VIPS: threadpool completed with 6 workers
INFO:pyvips:VIPS: threadpool completed with 3 workers
INFO:pyvips:VIPS: threadpool completed with 2 workers
INFO:pyvips:VIPS: threadpool completed with 5 workers
INFO:pyvips:VIPS: threadpool completed with 6 workers
INFO:pyvips:VIPS: threadpool completed with 2 workers
INFO:pyvips:VIPS: threadpool completed with 3 workers
INFO:pyvips:VIPS: threadpool completed with 2 workers
INFO:pyvips:VIPS: threadpool completed with 3 workers
INFO:pyvips:VIPS: threadpool completed with 6 workers
INFO:pyvips:VIPS: threadpool completed with 5 workers
INFO:pyvips:VIPS: threadpool completed with 4 workers
INFO:pyvips:VIPS: threadpool completed with 5 workers
INFO:pyvips:VIPS: threadpool completed with 5 workers
INFO:pyvips:VIPS: threadpool completed with 5 workers
INFO:pyvips:VIPS: threadpool completed with 2 workers
INFO:pyvips:VIPS: threadpool completed with 5 workers
INFO:pyvips:VIPS: threadpool completed with 8 workers
INFO:pyvips:VIPS: threadpool completed with 2 workers
INFO:pyvips:VIPS: threadpool completed with 4 workers
INFO:pyvips:VIPS: threadpool completed with 3 workers
INFO:pyvips:VIPS: threadpool completed with 4 workers
INFO:pyvips:VIPS: threadpool completed with 4 workers
INFO:pyvips:VIPS: threadpool completed with 8 workers
INFO:pyvips:VIPS: threadpool completed with 3 workers
INFO:pyvips:VIPS: threadpool completed with 4 workers
INFO:pyvips:VIPS: threadpool completed with 5 workers
INFO:pyvips:VIPS: threadpool completed with 5 workers
INFO:pyvips:VIPS: threadpool completed with 5 workers
INFO:pyvips:VIPS: threadpool completed with 4 workers
INFO:pyvips:VIPS: threadpool completed with 3 workers
INFO:pyvips:VIPS: threadpool completed with 10 workers
INFO:pyvips:VIPS: threadpool completed with 2 workers
INFO:pyvips:VIPS: threadpool completed with 9 workers
INFO:pyvips:VIPS: threadpool completed with 6 workers
INFO:pyvips:VIPS: threadpool completed with 5 workers
INFO:pyvips:VIPS: threadpool completed with 5 workers
INFO:pyvips:VIPS: threadpool completed with 3 workers
INFO:pyvips:VIPS: threadpool completed with 3 workers
INFO:pyvips:VIPS: threadpool completed with 4 workers
INFO:pyvips:VIPS: threadpool completed with 4 workers
INFO:pyvips:VIPS: threadpool completed with 5 workers
INFO:pyvips:VIPS: threadpool completed with 2 workers
INFO:pyvips:VIPS: threadpool completed with 8 workers
INFO:pyvips:VIPS: threadpool completed with 5 workers
INFO:pyvips:VIPS: threadpool completed with 5 workers
INFO:pyvips:VIPS: threadpool completed with 3 workers
INFO:pyvips:VIPS: threadpool completed with 4 workers

In [12]:
# Constants
CAM_METHODS = ["grad_cam", "grad_cam_pp", "layer_cam"]
MASK_TYPES = ["carcinoma", "another_pathology"]


def create_data(clustering_models, tile_samples):
    all_datasets = {model_name: [] for model_name in clustering_models}

    # Process all tile samples
    for slide_index, tile_idx in tile_samples:
        dataloader = dataloaders[slide_index]
        dataset = dataloader.dataset
        tile, label, metadata = dataset[tile_idx]
        tile = tile.to("cuda:0").unsqueeze(0)

        # Forward pass - compute once for all models
        output = hooked_model(tile)
        output.backward()

        # Get activations and gradients once
        activations = hooked_model.get_activations(target_layer)
        activations_flattened, shape = reshape_for_clustering(activations)
        activations_np = activations_flattened.detach().cpu().numpy()
        gradients = hooked_model.get_gradients(target_layer)

        slide, x, y = metadata["slide"], metadata["x"], metadata["y"]
        carcinoma_mask = get_tile_mask(carcinoma_masks[slide], x, y)
        another_pathology_mask = get_tile_mask(another_pathology_masks[slide], x, y)

        cams = {}
        cam_functions = {
            "grad_cam_pp": grad_cam_pp,
            "grad_cam": grad_cam,
            "layer_cam": layer_cam,
        }
        for cam_name in CAM_METHODS:
            cam_fn = cam_functions[cam_name]
            cam = cam_fn(activations, gradients)[0]
            cam_np = cam.flatten().detach().cpu().numpy()
            cam_mask = (cam > 1e-9).detach().cpu().numpy()
            cams[cam_name] = {
                "cam": cam,
                "cam_np": cam_np,
                "cam_mask": cam_mask,
                "cam_count": cam_mask.sum(),
            }

        batch_size, _, height, width = shape

        # Process each clustering model
        for model_name, (
            clustering_model,
            num_clusters,
            clustering_algorithm,
        ) in clustering_models.items():
            # Build header for this specific model (only columns for its num_clusters)
            header = ["label", "output", "clustering_algorithm", "num_clusters"]

            # Add columns for this model's clusters
            for i in range(num_clusters):
                header.append(f"weight_sum_{i}")
                header.append(f"cluster_count_{i}")
                header.append(f"cluster_soft_count_{i}")

            # Annotation mask presence flags
            header += ["has_carcinoma_mask", "has_another_pathology_mask"]

            # CAM columns
            for cam in CAM_METHODS:
                header += [f"{cam}_count"]
                for i in range(num_clusters):
                    header += [
                        f"intersection_count_{cam}_{i}",
                        f"union_count_{cam}_{i}",
                    ]
                    header += [
                        f"intersection_soft_count_{cam}_{i}",
                        f"union_soft_count_{cam}_{i}",
                    ]
                    header += [f"correlation_{cam}_{i}"]
                    header += [f"l2_distance_{cam}_{i}"]

                # CAM with annotation masks
                header += [
                    f"intersection_count_{cam}_carcinoma",
                    f"union_count_{cam}_carcinoma",
                    f"intersection_count_{cam}_another_pathology",
                    f"union_count_{cam}_another_pathology",
                ]

            # Cluster masks with annotation masks
            for i in range(num_clusters):
                header += [
                    f"intersection_count_cluster_{i}_carcinoma",
                    f"union_count_cluster_{i}_carcinoma",
                    f"intersection_soft_count_cluster_{i}_carcinoma",
                    f"union_soft_count_cluster_{i}_carcinoma",
                    f"intersection_count_cluster_{i}_another_pathology",
                    f"union_count_cluster_{i}_another_pathology",
                    f"intersection_soft_count_cluster_{i}_another_pathology",
                    f"union_soft_count_cluster_{i}_another_pathology",
                ]

            # Transform activations with this clustering model
            if clustering_algorithm == "KMeans":
                # For KMeans, transform returns distances, use argmin to get cluster assignments
                distances = clustering_model.transform(activations_np)
                clustering_flat = distances.argmin(
                    axis=1
                )  # Cluster with minimum distance
                clustering = clustering_flat.reshape(batch_size, height, width)

                # For KMeans, we use distances as "weights" for sum calculation
                # but they represent distances, not probabilities
                weights_sum = np.sum(distances, axis=0)

                # For soft masks with KMeans, we could use inverse distances or just use hard masks
                # Using inverse distances normalized by sum for soft assignment
                epsilon = 1e-9
                inv_distances = 1.0 / (distances + epsilon)
                inv_distances_norm = inv_distances / (
                    inv_distances.sum(axis=1, keepdims=True) + epsilon
                )
                weights_reshaped = inv_distances_norm.reshape(
                    batch_size, height, width, num_clusters
                )
            else:
                # For NMF, transform returns weights/coefficients
                weights = clustering_model.transform(activations_np)
                weights_sum = np.sum(weights, axis=0)
                weights_reshaped = weights.reshape(
                    batch_size, height, width, num_clusters
                )

                clustering = weights.argmax(axis=1)
                clustering = clustering.reshape(batch_size, height, width)

            # Count number of tiles per cluster
            cluster_counts = np.bincount(clustering.flatten(), minlength=num_clusters)

            # Start building row data
            tile_data = [
                label.item(),
                output.cpu().item(),
                clustering_algorithm,
                num_clusters,
            ]

            # Add weight_sum, cluster_count, cluster_soft_count for this model's clusters
            for i in range(num_clusters):
                tile_data.append(weights_sum[i])
                tile_data.append(cluster_counts[i])
                if clustering_algorithm == "KMeans":
                    # For KMeans, count pixels where this cluster has highest inverse distance (soft assignment)
                    max_cluster = weights_reshaped[0, :, :, :].argmax(axis=2)
                    tile_data.append((max_cluster == i).sum())
                else:
                    # For NMF, count pixels where weight > threshold
                    tile_data.append((weights[:, i] > 1e-9).sum())

            # Add annotation mask presence flags
            has_carcinoma = carcinoma_mask is not None
            has_another_pathology = another_pathology_mask is not None
            tile_data.append(int(has_carcinoma))
            tile_data.append(int(has_another_pathology))

            # Create masks for this model
            masks = []
            for i in range(num_clusters):
                mask = np.zeros((height, width), dtype=np.float32)
                mask[clustering[0, :, :] == i] = 1
                assert mask.sum() == cluster_counts[i]
                assert mask.shape == (height, width)
                masks.append(mask)

            soft_masks = []
            for i in range(num_clusters):
                mask = np.zeros((height, width), dtype=np.float32)
                if clustering_algorithm == "KMeans":
                    # For KMeans, use inverse distance threshold for soft assignment
                    mask[weights_reshaped[0, :, :, i] > 1e-3] = 1
                else:
                    # For NMF, use weight threshold
                    mask[weights_reshaped[0, :, :, i] > 1e-9] = 1
                assert mask.shape == (height, width)
                soft_masks.append(mask)

            # Process CAMs
            for cam_name in CAM_METHODS:
                cam_data = cams[cam_name]
                cam_count = cam_data["cam_count"]
                cam_mask = cam_data["cam_mask"]
                cam_np = cam_data["cam_np"]

                tile_data.append(cam_count)

                for i in range(num_clusters):
                    # Use masks for this cluster
                    for cluster_mask in [masks[i], soft_masks[i]]:
                        intersection_count = (cam_mask * cluster_mask).sum()
                        union_count = (cam_mask + cluster_mask).sum()
                        tile_data.extend([int(intersection_count), int(union_count)])

                    # Correlation
                    weights_cluster = weights_reshaped[0, :, :, i].flatten()
                    if (
                        cam_count == 0
                        or np.std(cam_np) == 0
                        or np.std(weights_cluster) == 0
                    ):
                        correlation = np.nan
                    else:
                        correlation = np.corrcoef(cam_np, weights_cluster)[0, 1]
                    tile_data.append(correlation)

                    # Calculate L2 distance
                    weights_cluster_flat = weights_reshaped[0, :, :, i].flatten()
                    l2_distance = np.sqrt(np.sum((cam_np - weights_cluster_flat) ** 2))
                    tile_data.append(l2_distance)

                # CAM with annotation masks
                if has_carcinoma:
                    intersection_cam_carcinoma = (cam_mask * carcinoma_mask).sum()
                    union_cam_carcinoma = (cam_mask + carcinoma_mask).sum()
                else:
                    intersection_cam_carcinoma = 0
                    union_cam_carcinoma = 0
                tile_data.extend(
                    [int(intersection_cam_carcinoma), int(union_cam_carcinoma)]
                )

                if has_another_pathology:
                    intersection_cam_another = (cam_mask * another_pathology_mask).sum()
                    union_cam_another = (cam_mask + another_pathology_mask).sum()
                else:
                    intersection_cam_another = 0
                    union_cam_another = 0
                tile_data.extend(
                    [int(intersection_cam_another), int(union_cam_another)]
                )

            # Cluster masks with annotation masks
            for i in range(num_clusters):
                # Hard cluster mask with carcinoma
                if has_carcinoma:
                    intersection_cluster_carcinoma = (masks[i] * carcinoma_mask).sum()
                    union_cluster_carcinoma = (masks[i] + carcinoma_mask).sum()
                else:
                    intersection_cluster_carcinoma = 0
                    union_cluster_carcinoma = 0
                tile_data.extend(
                    [int(intersection_cluster_carcinoma), int(union_cluster_carcinoma)]
                )

                # Soft cluster mask with carcinoma
                if has_carcinoma:
                    intersection_soft_cluster_carcinoma = (
                        soft_masks[i] * carcinoma_mask
                    ).sum()
                    union_soft_cluster_carcinoma = (
                        soft_masks[i] + carcinoma_mask
                    ).sum()
                else:
                    intersection_soft_cluster_carcinoma = 0
                    union_soft_cluster_carcinoma = 0
                tile_data.extend(
                    [
                        int(intersection_soft_cluster_carcinoma),
                        int(union_soft_cluster_carcinoma),
                    ]
                )

                # Hard cluster mask with another_pathology
                if has_another_pathology:
                    intersection_cluster_another = (
                        masks[i] * another_pathology_mask
                    ).sum()
                    union_cluster_another = (masks[i] + another_pathology_mask).sum()
                else:
                    intersection_cluster_another = 0
                    union_cluster_another = 0
                tile_data.extend(
                    [int(intersection_cluster_another), int(union_cluster_another)]
                )

                # Soft cluster mask with another_pathology
                if has_another_pathology:
                    intersection_soft_cluster_another = (
                        soft_masks[i] * another_pathology_mask
                    ).sum()
                    union_soft_cluster_another = (
                        soft_masks[i] + another_pathology_mask
                    ).sum()
                else:
                    intersection_soft_cluster_another = 0
                    union_soft_cluster_another = 0
                tile_data.extend(
                    [
                        int(intersection_soft_cluster_another),
                        int(union_soft_cluster_another),
                    ]
                )

            assert len(tile_data) == len(header), (
                f"Expected {len(header)} columns, got {len(tile_data)}"
            )
            all_datasets[model_name].append(tile_data)

        hooked_model.zero_grad()

    # Convert each model's data list to DataFrame
    result = {}
    for model_name, data_list in all_datasets.items():
        _, num_clusters, clustering_algorithm = clustering_models[model_name]

        # Build header for this model
        header = ["label", "output", "clustering_algorithm", "num_clusters"]
        for i in range(num_clusters):
            header.append(f"weight_sum_{i}")
            header.append(f"cluster_count_{i}")
            header.append(f"cluster_soft_count_{i}")

        # Annotation mask presence flags
        header += ["has_carcinoma_mask", "has_another_pathology_mask"]

        for cam in CAM_METHODS:
            header += [f"{cam}_count"]
            for i in range(num_clusters):
                header += [f"intersection_count_{cam}_{i}", f"union_count_{cam}_{i}"]
                header += [
                    f"intersection_soft_count_{cam}_{i}",
                    f"union_soft_count_{cam}_{i}",
                ]
                header += [f"correlation_{cam}_{i}"]
                header += [f"l2_distance_{cam}_{i}"]

            # CAM with annotation masks
            header += [
                f"intersection_count_{cam}_carcinoma",
                f"union_count_{cam}_carcinoma",
                f"intersection_count_{cam}_another_pathology",
                f"union_count_{cam}_another_pathology",
            ]

        # Cluster masks with annotation masks
        for i in range(num_clusters):
            header += [
                f"intersection_count_cluster_{i}_carcinoma",
                f"union_count_cluster_{i}_carcinoma",
                f"intersection_soft_count_cluster_{i}_carcinoma",
                f"union_soft_count_cluster_{i}_carcinoma",
                f"intersection_count_cluster_{i}_another_pathology",
                f"union_count_cluster_{i}_another_pathology",
                f"intersection_soft_count_cluster_{i}_another_pathology",
                f"union_soft_count_cluster_{i}_another_pathology",
            ]

        result[model_name] = pd.DataFrame(data_list, columns=header)

    return result

In [13]:
def set_my_seed(seed):
    np.random.seed(seed)
    random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)

In [14]:
# set_my_seed(42)

# n = 10000

In [15]:
# # First, generate the tile samples once to ensure we use the same tiles for all modelsprint("Generating tile samples (same tiles for all models)...")
# #
# num_slides = len(dataloaders)
# slide_indices = np.random.choice(list(range(num_slides)), n, replace=True)
# slide_counts = [0] * num_slides

# for slide_index in slide_indices:
#     slide_counts[slide_index] += 1

# # Generate tile_samples: list of (slide_index, tile_idx) tuples

# tile_samples = []
# for slide_index, count in enumerate(slide_counts):
#     if count == 0:
#         continue
#     dataloader = dataloaders[slide_index]
#     dataset = dataloader.dataset
#     num_tiles_in_slide = len(dataset)
#     tile_indices = sorted(
#         np.random.choice(list(range(num_tiles_in_slide)), count, replace=True)
#     )
#     for tile_idx in tile_indices:
#         tile_samples.append((slide_index, tile_idx))


# print(f"Generated {len(tile_samples)} tile samples")
# print(
#     "These same tiles will be used for all clustering algorithms and cluster numbers\n"
# )

In [16]:
# # Create data for all models at once (same tiles, same activations)
# print("Processing all tiles with all clustering models...")
# all_datasets = create_data(clustering_models, tile_samples)

# print(f"\nCreated {len(all_datasets)} separate datasets:")
# for model_name, data in all_datasets.items():
#     print(f"  {model_name}: {data.shape}")

In [17]:
# # Save each dataset to a separate CSV file
# print("\nSaving datasets...")
# for model_name, data in all_datasets.items():
#     filename = f"data_{model_name.lower()}.csv"
#     data.to_csv(filename, index=False)
#     print(f"  Saved {filename}")

In [18]:
# Load all separate datasets
all_datasets = {}

print("Loading separate datasets:")
for clustering_algorithm in CLUSTERING_ALGORITHMS:
    for num_clusters in CLUSTER_NUMBERS:
        model_name = f"{clustering_algorithm}_{num_clusters}"
        filename = f"data_{model_name.lower()}.csv"
        data = pd.read_csv(filename)
        all_datasets[model_name] = data
        print(f"  {model_name}: {data.shape}")

print(f"\nTotal datasets loaded: {len(all_datasets)}")

# Create combinations list from the datasets
combinations = []
for _, data in all_datasets.items():
    alg = data["clustering_algorithm"].iloc[0]
    n_clust = data["num_clusters"].iloc[0]
    combinations.append({"clustering_algorithm": alg, "num_clusters": n_clust})

combinations = pd.DataFrame(combinations).drop_duplicates()
print("\nAvailable combinations:")
print(combinations.to_string(index=False))

Loading separate datasets:
  NMF_4: (10000, 137)
  NMF_6: (10000, 195)
  NMF_8: (10000, 253)
  KMeans_4: (10000, 137)
  KMeans_6: (10000, 195)
  KMeans_8: (10000, 253)

Total datasets loaded: 6

Available combinations:
clustering_algorithm  num_clusters
                 NMF             4
                 NMF             6
                 NMF             8
              KMeans             4
              KMeans             6
              KMeans             8

In [ ]:
# Constants
CAM_METHODS = ["grad_cam", "grad_cam_pp", "layer_cam"]
MASK_TYPES = ["carcinoma", "another_pathology"]
MASK_DISPLAYS = {"carcinoma": "Carcinoma", "another_pathology": "Another Pathology"}


# Helper functions for visualization
def get_method_display(method: str) -> str:
    """Get display name for CAM method."""
    return {
        "grad_cam": "Grad-CAM",
        "grad_cam_pp": "Grad-CAM++",
        "layer_cam": "Layer-CAM",
    }.get(method, method)


def calculate_iou(
    data: pd.DataFrame, intersection_col: str, union_col: str, iou_col: str
):
    """Calculate IoU from intersection and union columns."""
    mask = data[union_col].notna() & (data[union_col] > 0)
    data.loc[mask, iou_col] = (
        data.loc[mask, intersection_col] / data.loc[mask, union_col]
    )


def create_boxplot_by_label(
    data: pd.DataFrame,
    columns: list[str],
    labels: list[str],
    title: str,
    ylabel: str,
    filename: str,
    figsize: tuple = (14, 6),
):
    """Create boxplot comparing two labels."""
    cluster_data_label0 = []
    cluster_data_label1 = []

    for col in columns:
        data_0 = data[data["predicted_label"] == 0][col].dropna()
        data_1 = data[data["predicted_label"] == 1][col].dropna()
        cluster_data_label0.append(data_0)
        cluster_data_label1.append(data_1)

    positions = np.arange(len(labels))
    width = 0.35

    plt.figure(figsize=figsize)
    bp0 = plt.boxplot(
        cluster_data_label0,
        positions=positions - width / 2,
        widths=width,
        tick_labels=labels,
        patch_artist=True,
    )
    bp1 = plt.boxplot(
        cluster_data_label1,
        positions=positions + width / 2,
        widths=width,
        patch_artist=True,
    )

    for patch in bp0["boxes"]:
        patch.set_facecolor("lightblue")
    for patch in bp1["boxes"]:
        patch.set_facecolor("lightcoral")

    plt.title(title)
    plt.xlabel("Cluster" if labels and "Cluster" in labels[0] else "Category")
    plt.ylabel(ylabel)
    plt.xticks(positions, labels, rotation=45)
    plt.legend([bp0["boxes"][0], bp1["boxes"][0]], ["Label 0", "Label 1"])
    plt.tight_layout()
    plt.savefig(filename, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Saved figure: {filename}")


def create_boxplot_all_data(
    data: pd.DataFrame,
    columns: list[str],
    labels: list[str],
    title: str,
    ylabel: str,
    filename: str,
    figsize: tuple = (12, 6),
):
    """Create boxplot for all data."""
    cluster_data = []
    for col in columns:
        col_data = data[col].dropna()
        cluster_data.append(col_data)

    plt.figure(figsize=figsize)
    plt.boxplot(cluster_data, tick_labels=labels)
    plt.title(title)
    plt.xlabel("Cluster" if labels and "Cluster" in labels[0] else "Category")
    plt.ylabel(ylabel)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig(filename, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Saved figure: {filename}")


def create_metric_plots(
    data: pd.DataFrame,
    method: str,
    metric_suffix: str,
    metric_display: str,
    num_clusters: int,
    figures_dir: str,
    alg: str,
    n_clust: int,
):
    """Create both by-label and all-data plots for a metric."""
    method_display = get_method_display(method)
    cluster_labels = [f"Cluster {i + 1}" for i in range(num_clusters)]
    columns = [f"{metric_suffix}_{method}_{i}" for i in range(num_clusters)]

    # By label plot
    create_boxplot_by_label(
        data,
        columns,
        cluster_labels,
        f"{method_display} {metric_display} by Cluster - {alg} ({n_clust} clusters)",
        metric_display,
        f"{figures_dir}/{metric_suffix}_by_label_{method}.png",
    )

    # All data plot
    create_boxplot_all_data(
        data,
        columns,
        cluster_labels,
        f"{method_display} {metric_display} by Cluster (All Data) - {alg} ({n_clust} clusters)",
        metric_display,
        f"{figures_dir}/{metric_suffix}_all_data_{method}.png",
    )


def create_annotation_mask_plots(
    data: pd.DataFrame,
    mask_type: str,
    mask_display: str,
    num_clusters: int,
    figures_dir: str,
    alg: str,
    n_clust: int,
):
    """Create hard and soft IoU plots for annotation masks."""
    data_with_mask = data[data[f"has_{mask_type}_mask"] == 1]

    if len(data_with_mask) == 0:
        return

    # Hard IoU: Combine all CAM methods + all clusters
    hard_data = []
    hard_labels = []

    # Add CAM methods
    for method in CAM_METHODS:
        method_display = get_method_display(method)
        iou_col = f"iou_{method}_{mask_type}"
        iou_data = data_with_mask[iou_col].dropna()
        if len(iou_data) > 0:
            hard_data.append(iou_data)
            hard_labels.append(method_display)

    # Add clusters
    for i in range(num_clusters):
        iou_col = f"iou_cluster_{i}_{mask_type}"
        iou_data = data_with_mask[iou_col].dropna()
        if len(iou_data) > 0:
            hard_data.append(iou_data)
            hard_labels.append(f"Cluster {i + 1}")

    if len(hard_data) > 0:
        plt.figure(figsize=(14, 6))
        plt.boxplot(hard_data, tick_labels=hard_labels)
        plt.title(f"IoU (Hard) with {mask_display} Mask - {alg} ({n_clust} clusters)")
        plt.xlabel("Method/Cluster")
        plt.ylabel("IoU")
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.savefig(
            f"{figures_dir}/iou_hard_{mask_type}.png", dpi=300, bbox_inches="tight"
        )
        plt.close()
        print(f"Saved figure: {figures_dir}/iou_hard_{mask_type}.png")

    # Soft IoU: Only clusters
    soft_data = []
    soft_labels = []
    for i in range(num_clusters):
        iou_col = f"iou_soft_cluster_{i}_{mask_type}"
        iou_data = data_with_mask[iou_col].dropna()
        if len(iou_data) > 0:
            soft_data.append(iou_data)
            soft_labels.append(f"Cluster {i + 1}")

    if len(soft_data) > 0:
        plt.figure(figsize=(12, 6))
        plt.boxplot(soft_data, tick_labels=soft_labels)
        plt.title(f"IoU (Soft) with {mask_display} Mask - {alg} ({n_clust} clusters)")
        plt.xlabel("Cluster")
        plt.ylabel("IoU")
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.savefig(
            f"{figures_dir}/iou_soft_{mask_type}.png", dpi=300, bbox_inches="tight"
        )
        plt.close()
        print(f"Saved figure: {figures_dir}/iou_soft_{mask_type}.png")


def create_cam_cluster_table(
    data: pd.DataFrame,
    method: str,
    label_filter: int | None,
    num_clusters: int,
    total_pixels: int,
    figures_dir: str,
    alg: str,
    n_clust: int,
) -> pd.DataFrame:
    """Create statistics table for CAM method and clusters."""
    method_display = get_method_display(method)

    if label_filter is None:
        label_name = "Overall"
        label_suffix = "all"
        label_data = data
    else:
        label_name = f"Label {label_filter}"
        label_suffix = f"label_{label_filter}"
        label_data = data[data["predicted_label"] == label_filter]

    print(f"\n{method_display} - {label_name}:")
    print("-" * 60)

    table_data = []
    for i in range(num_clusters):
        row = {"Cluster": i + 1}

        # Weight Sum
        weight_col = f"weight_sum_{i}"
        weight_values = label_data[weight_col].dropna()
        row["Weight Sum"] = (
            f"{weight_values.mean():.4f} ± {weight_values.std():.4f}"
            if len(weight_values) > 0
            else "N/A"
        )

        # Cluster Count
        count_col = f"cluster_count_{i}"
        count_values = label_data[count_col].dropna()
        row["Cluster Count"] = (
            f"{count_values.mean():.4f} ± {count_values.std():.4f}"
            if len(count_values) > 0
            else "N/A"
        )

        # Normalized Cluster Count
        if len(count_values) > 0:
            normalized_counts = count_values / total_pixels
            row["Norm Count"] = (
                f"{normalized_counts.mean():.4f} ± {normalized_counts.std():.4f}"
            )
        else:
            row["Norm Count"] = "N/A"

        # Intersection / Total Pixels (Hard)
        intersection_col = f"intersection_count_{method}_{i}"
        intersection_values = label_data[intersection_col].dropna()
        if len(intersection_values) > 0:
            normalized_intersection = intersection_values / total_pixels
            row["Intersection/Pixels"] = (
                f"{normalized_intersection.mean():.4f} ± {normalized_intersection.std():.4f}"
            )
        else:
            row["Intersection/Pixels"] = "N/A"

        # Intersection / Total Pixels (Soft)
        intersection_soft_col = f"intersection_soft_count_{method}_{i}"
        intersection_soft_values = label_data[intersection_soft_col].dropna()
        if len(intersection_soft_values) > 0:
            normalized_intersection_soft = intersection_soft_values / total_pixels
            row["Intersection/Pixels (Soft)"] = (
                f"{normalized_intersection_soft.mean():.4f} ± {normalized_intersection_soft.std():.4f}"
            )
        else:
            row["Intersection/Pixels (Soft)"] = "N/A"

        # IoU
        iou_col = f"iou_{method}_{i}"
        iou_values = label_data[iou_col].dropna()
        row["IoU"] = (
            f"{iou_values.mean():.4f} ± {iou_values.std():.4f}"
            if len(iou_values) > 0
            else "N/A"
        )

        # Soft IoU
        soft_iou_col = f"iou_soft_{method}_{i}"
        soft_iou_values = label_data[soft_iou_col].dropna()
        row["Soft IoU"] = (
            f"{soft_iou_values.mean():.4f} ± {soft_iou_values.std():.4f}"
            if len(soft_iou_values) > 0
            else "N/A"
        )

        # Correlation
        corr_col = f"correlation_{method}_{i}"
        corr_values = label_data[corr_col].dropna()
        row["Correlation"] = (
            f"{corr_values.mean():.4f} ± {corr_values.std():.4f}"
            if len(corr_values) > 0
            else "N/A"
        )

        # L2 Distance
        l2_col = f"l2_distance_{method}_{i}"
        l2_values = label_data[l2_col].dropna()
        row["L2 Distance"] = (
            f"{l2_values.mean():.4f} ± {l2_values.std():.4f}"
            if len(l2_values) > 0
            else "N/A"
        )

        table_data.append(row)

    if table_data:
        table_df = pd.DataFrame(table_data)
        display(table_df)
        filename = f"{figures_dir}/table_{method}_{label_suffix}.csv"
        table_df.to_csv(filename, index=False)
        print(f"Saved table: {filename}")
        return table_df
    return pd.DataFrame()


def create_cam_iou_correlation_table(
    data: pd.DataFrame,
    method: str,
    num_clusters: int,
    figures_dir: str,
    alg: str,
    n_clust: int,
) -> pd.DataFrame:
    """Create table showing IoU (all data) and Correlation (Label 0, Label 1) for each CAM method."""
    _ = get_method_display(method)

    def get_statistic_string(values: pd.Series) -> str:
        """Get formatted statistic string (mean ± std) or N/A."""
        if len(values) > 0:
            return f"{values.mean():.4f} ± {values.std():.4f}"
        return "N/A"

    table_rows = []

    for i in range(num_clusters):
        row = {"Cluster": i + 1}

        # IoU (All Data)
        iou_col = f"iou_{method}_{i}"
        iou_values_all = data[iou_col].dropna()
        row["IoU (All Data)"] = get_statistic_string(iou_values_all)

        # Correlation (Label 0)
        data_label0 = data[data["predicted_label"] == 0]
        corr_col = f"correlation_{method}_{i}"
        corr_values_label0 = data_label0[corr_col].dropna()
        row["Correlation (Label 0)"] = get_statistic_string(corr_values_label0)

        # Correlation (Label 1)
        data_label1 = data[data["predicted_label"] == 1]
        corr_values_label1 = data_label1[corr_col].dropna()
        row["Correlation (Label 1)"] = get_statistic_string(corr_values_label1)

        table_rows.append(row)

    if table_rows:
        table_df = pd.DataFrame(table_rows)
        display(table_df)
        filename = f"{figures_dir}/table_{method}_iou_correlation.csv"
        table_df.to_csv(filename, index=False)
        print(f"Saved table: {filename}")
        return table_df
    return pd.DataFrame()


def create_cam_cluster_comparison_table(
    data: pd.DataFrame,
    method: str,
    num_clusters: int,
    figures_dir: str,
    alg: str,
    n_clust: int,
) -> pd.DataFrame:
    """Create table comparing CAM-cluster metrics across labels (Label 0, Label 1)."""
    _ = get_method_display(method)

    def get_statistic_string(values: pd.Series) -> str:
        """Get formatted statistic string (mean ± std) or N/A."""
        if len(values) > 0:
            return f"{values.mean():.4f} ± {values.std():.4f}"
        return "N/A"

    table_rows = []

    for i in range(num_clusters):
        row = {"Cluster": i + 1}

        # Label 0 metrics
        data_label0 = data[data["predicted_label"] == 0]

        # IoU
        iou_col = f"iou_{method}_{i}"
        iou_values_label0 = data_label0[iou_col].dropna()
        row["Label 0 IoU"] = get_statistic_string(iou_values_label0)

        # Correlation
        corr_col = f"correlation_{method}_{i}"
        corr_values_label0 = data_label0[corr_col].dropna()
        row["Label 0 Correlation"] = get_statistic_string(corr_values_label0)

        # L2 Distance
        l2_col = f"l2_distance_{method}_{i}"
        l2_values_label0 = data_label0[l2_col].dropna()
        row["Label 0 L2 Distance"] = get_statistic_string(l2_values_label0)

        # Label 1 metrics
        data_label1 = data[data["predicted_label"] == 1]

        # IoU
        iou_values_label1 = data_label1[iou_col].dropna()
        row["Label 1 IoU"] = get_statistic_string(iou_values_label1)

        # Correlation
        corr_values_label1 = data_label1[corr_col].dropna()
        row["Label 1 Correlation"] = get_statistic_string(corr_values_label1)

        # L2 Distance
        l2_values_label1 = data_label1[l2_col].dropna()
        row["Label 1 L2 Distance"] = get_statistic_string(l2_values_label1)

        table_rows.append(row)

    if table_rows:
        table_df = pd.DataFrame(table_rows)
        display(table_df)
        filename = f"{figures_dir}/table_{method}_cluster_comparison.csv"
        table_df.to_csv(filename, index=False)
        print(f"Saved table: {filename}")
        return table_df
    return pd.DataFrame()


def create_norm_count_comparison_table(
    data: pd.DataFrame,
    num_clusters: int,
    total_pixels: int,
    figures_dir: str,
    alg: str,
    n_clust: int,
) -> pd.DataFrame:
    """Create table comparing normalized cluster counts across labels (All Data, Label 0, Label 1)."""

    def get_statistic_string(values: pd.Series) -> str:
        """Get formatted statistic string (mean ± std) or N/A."""
        if len(values) > 0:
            return f"{values.mean():.4f} ± {values.std():.4f}"
        return "N/A"

    table_rows = []

    for i in range(num_clusters):
        row = {"Cluster": i + 1}

        count_col = f"cluster_count_{i}"

        # All Data
        count_values_all = data[count_col].dropna()
        if len(count_values_all) > 0:
            normalized_counts_all = count_values_all / total_pixels
            row["All Data"] = get_statistic_string(normalized_counts_all)
        else:
            row["All Data"] = "N/A"

        # Label 0
        data_label0 = data[data["predicted_label"] == 0]
        count_values_label0 = data_label0[count_col].dropna()
        if len(count_values_label0) > 0:
            normalized_counts_label0 = count_values_label0 / total_pixels
            row["Label 0"] = get_statistic_string(normalized_counts_label0)
        else:
            row["Label 0"] = "N/A"

        # Label 1
        data_label1 = data[data["predicted_label"] == 1]
        count_values_label1 = data_label1[count_col].dropna()
        if len(count_values_label1) > 0:
            normalized_counts_label1 = count_values_label1 / total_pixels
            row["Label 1"] = get_statistic_string(normalized_counts_label1)
        else:
            row["Label 1"] = "N/A"

        table_rows.append(row)

    if table_rows:
        table_df = pd.DataFrame(table_rows)
        display(table_df)
        filename = f"{figures_dir}/table_norm_count_comparison.csv"
        table_df.to_csv(filename, index=False)
        print(f"Saved table: {filename}")
        return table_df
    return pd.DataFrame()


def create_carcinoma_iou_comparison_table(
    data: pd.DataFrame,
    num_clusters: int,
    figures_dir: str,
    alg: str,
    n_clust: int,
) -> pd.DataFrame:
    """Create table comparing Carcinoma IoU across labels (Label 0, Label 1, All Data)."""
    data_with_mask = data[data["has_carcinoma_mask"] == 1]

    if len(data_with_mask) == 0:
        return pd.DataFrame()

    mask_type = "carcinoma"

    def get_statistic_string(values: pd.Series) -> str:
        """Get formatted statistic string (mean ± std) or N/A."""
        if len(values) > 0:
            return f"{values.mean():.4f} ± {values.std():.4f}"
        return "N/A"

    table_rows = []

    # Add CAM method rows
    for method in CAM_METHODS:
        method_display = get_method_display(method)
        row = {"Method/Cluster": method_display}

        iou_col = f"iou_{method}_{mask_type}"

        # All Data
        iou_all = data_with_mask[iou_col].dropna()
        row["All Data"] = get_statistic_string(iou_all)

        # Label 0
        iou_label0 = data_with_mask[data_with_mask["predicted_label"] == 0][
            iou_col
        ].dropna()
        row["Label 0"] = get_statistic_string(iou_label0)

        # Label 1
        iou_label1 = data_with_mask[data_with_mask["predicted_label"] == 1][
            iou_col
        ].dropna()
        row["Label 1"] = get_statistic_string(iou_label1)

        table_rows.append(row)

    # Add cluster rows
    for i in range(num_clusters):
        row = {"Method/Cluster": f"Cluster {i + 1}"}

        iou_col = f"iou_cluster_{i}_{mask_type}"

        # All Data
        iou_all = data_with_mask[iou_col].dropna()
        row["All Data"] = get_statistic_string(iou_all)

        # Label 0
        iou_label0 = data_with_mask[data_with_mask["predicted_label"] == 0][
            iou_col
        ].dropna()
        row["Label 0"] = get_statistic_string(iou_label0)

        # Label 1
        iou_label1 = data_with_mask[data_with_mask["predicted_label"] == 1][
            iou_col
        ].dropna()
        row["Label 1"] = get_statistic_string(iou_label1)

        table_rows.append(row)

    if table_rows:
        table_df = pd.DataFrame(table_rows)
        display(table_df)
        filename = f"{figures_dir}/table_carcinoma_iou_comparison.csv"
        table_df.to_csv(filename, index=False)
        print(f"Saved table: {filename}")
        return table_df
    return pd.DataFrame()


def create_annotation_mask_table(
    data: pd.DataFrame,
    mask_type: str,
    mask_display: str,
    num_clusters: int,
    figures_dir: str,
    alg: str,
    n_clust: int,
    label_filter: int | None = None,
) -> pd.DataFrame:
    """Create comprehensive table for annotation mask metrics."""
    data_with_mask = data[data[f"has_{mask_type}_mask"] == 1]

    if len(data_with_mask) == 0:
        return pd.DataFrame()

    # Filter by predicted label if specified
    if label_filter is not None:
        data_with_mask = data_with_mask[
            data_with_mask["predicted_label"] == label_filter
        ]
        if len(data_with_mask) == 0:
            return pd.DataFrame()
        label_name = f"Predicted Label {label_filter}"
        label_suffix = f"label_{label_filter}"
    else:
        label_name = "All Data"
        label_suffix = "all"

    total_pixels = 32 * 32  # Total number of pixels

    print(f"\n{mask_display} Mask Metrics - {label_name} (n={len(data_with_mask)}):")
    print("-" * 60)

    table_rows = []

    # Add CAM method rows
    for method in CAM_METHODS:
        method_display = get_method_display(method)
        row = {"Method/Cluster": method_display}

        # Intersection / Total Pixels
        intersection_col = f"intersection_count_{method}_{mask_type}"
        intersection_values = data_with_mask[intersection_col].dropna()
        if len(intersection_values) > 0:
            normalized_intersection = intersection_values / total_pixels
            row["Intersection/Pixels"] = (
                f"{normalized_intersection.mean():.4f} ± {normalized_intersection.std():.4f}"
            )
        else:
            row["Intersection/Pixels"] = "N/A"

        iou_col = f"iou_{method}_{mask_type}"
        iou_values = data_with_mask[iou_col].dropna()
        row["IoU (Mean ± Std)"] = (
            f"{iou_values.mean():.4f} ± {iou_values.std():.4f}"
            if len(iou_values) > 0
            else "N/A"
        )
        row["IoU Soft (Mean ± Std)"] = "N/A"
        table_rows.append(row)

    # Add cluster rows
    for i in range(num_clusters):
        row = {"Method/Cluster": f"Cluster {i + 1}"}

        # Intersection / Total Pixels (Hard)
        intersection_col = f"intersection_count_cluster_{i}_{mask_type}"
        intersection_values = data_with_mask[intersection_col].dropna()
        if len(intersection_values) > 0:
            normalized_intersection = intersection_values / total_pixels
            row["Intersection/Pixels"] = (
                f"{normalized_intersection.mean():.4f} ± {normalized_intersection.std():.4f}"
            )
        else:
            row["Intersection/Pixels"] = "N/A"

        # Intersection / Total Pixels (Soft)
        intersection_soft_col = f"intersection_soft_count_cluster_{i}_{mask_type}"
        intersection_soft_values = data_with_mask[intersection_soft_col].dropna()
        if len(intersection_soft_values) > 0:
            normalized_intersection_soft = intersection_soft_values / total_pixels
            row["Intersection/Pixels (Soft)"] = (
                f"{normalized_intersection_soft.mean():.4f} ± {normalized_intersection_soft.std():.4f}"
            )
        else:
            row["Intersection/Pixels (Soft)"] = "N/A"

        iou_col = f"iou_cluster_{i}_{mask_type}"
        iou_values = data_with_mask[iou_col].dropna()
        row["IoU (Mean ± Std)"] = (
            f"{iou_values.mean():.4f} ± {iou_values.std():.4f}"
            if len(iou_values) > 0
            else "N/A"
        )

        soft_iou_col = f"iou_soft_cluster_{i}_{mask_type}"
        soft_iou_values = data_with_mask[soft_iou_col].dropna()
        row["IoU Soft (Mean ± Std)"] = (
            f"{soft_iou_values.mean():.4f} ± {soft_iou_values.std():.4f}"
            if len(soft_iou_values) > 0
            else "N/A"
        )
        table_rows.append(row)

    if table_rows:
        table_df = pd.DataFrame(table_rows)
        display(table_df)
        filename = f"{figures_dir}/table_{mask_type}_{label_suffix}.csv"
        table_df.to_csv(filename, index=False)
        print(f"Saved table: {filename}")
        return table_df
    return pd.DataFrame()


base_figures_dir = "figures"
os.makedirs(base_figures_dir, exist_ok=True)

# Process each clustering model combination separately
for _, row in combinations.iterrows():
    alg = row["clustering_algorithm"]
    n_clust = row["num_clusters"]
    model_name = f"{alg}_{n_clust}"

    # Create subdirectory for this combination
    figures_dir = f"{base_figures_dir}/{model_name}"
    os.makedirs(figures_dir, exist_ok=True)

    print(f"\n{'=' * 80}")
    print(f"Processing: {alg} with {n_clust} clusters")
    print(f"{'=' * 80}\n")

    # Get the dataset for this combination
    data = all_datasets[model_name].copy()

    num_clusters = n_clust

    # y is the sigmoid of output
    data["y"] = 1 / (1 + np.exp(-data["output"]))

    # print count of labels - either 0 or 1
    print("Label distribution:")
    display(data["label"].value_counts())

    plt.hist(data["y"])
    plt.title(
        f"Distribution of predicted probabilities (y) - {alg} ({n_clust} clusters)"
    )
    plt.xlabel("y")
    plt.ylabel("Frequency")
    filename = f"{figures_dir}/hist_predicted_prob.png"
    plt.savefig(filename, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Saved figure: {filename}")

    # Compute prediction metrics
    data["predicted_label"] = (data["y"] > 0.94).astype(int)

    print(f"\nPrediction Metrics - {alg} with {n_clust} clusters:")
    print("=" * 60)
    print(f"Number of samples: {len(data)}")
    display(pd.crosstab(data["predicted_label"], data["label"]))
    print(f"Accuracy: {accuracy_score(data['label'], data['predicted_label'])}")
    print(f"Precision: {precision_score(data['label'], data['predicted_label'])}")
    print(f"Recall: {recall_score(data['label'], data['predicted_label'])}")
    print(f"F1 Score: {f1_score(data['label'], data['predicted_label'])}")
    print(f"AUC Score: {roc_auc_score(data['label'], data['y'])}")

    # Add IoU columns for each method and cluster
    for method in CAM_METHODS:
        for i in range(num_clusters):
            calculate_iou(
                data,
                f"intersection_count_{method}_{i}",
                f"union_count_{method}_{i}",
                f"iou_{method}_{i}",
            )

    # Fit linear regression model
    print(f"\nFitting linear regression model - {alg} ({n_clust} clusters):")
    print("=" * 60)

    X = data[[f"weight_sum_{i}" for i in range(num_clusters)]]
    y = data["output"]

    model = LinearRegression()
    model.fit(X, y)

    print(f"Coefficients: {model.coef_}")
    print(f"Intercept: {model.intercept_}")
    print(f"R-squared: {model.score(X, y)}")

    # Fit linear regression model using cluster counts
    print(
        f"\nFitting linear regression model (using cluster counts) - {alg} ({n_clust} clusters):"
    )
    print("=" * 60)

    X_clusters = data[[f"cluster_count_{i}" for i in range(num_clusters)]]
    y = data["output"]

    model_clusters = LinearRegression()
    model_clusters.fit(X_clusters, y)

    print(f"Coefficients: {model_clusters.coef_}")
    print(f"Intercept: {model_clusters.intercept_}")
    print(f"R-squared: {model_clusters.score(X_clusters, y)}")

    # Visualize weight distributions by cluster
    cluster_labels = [f"Cluster {i + 1}" for i in range(num_clusters)]
    weight_cols = [f"weight_sum_{i}" for i in range(num_clusters)]

    create_boxplot_by_label(
        data,
        weight_cols,
        cluster_labels,
        f"Weight Sum by Cluster - {alg} ({n_clust} clusters)",
        "Weight Sum",
        f"{figures_dir}/weight_sum_by_label.png",
    )

    create_boxplot_all_data(
        data,
        weight_cols,
        cluster_labels,
        f"Weight Sum by Cluster (All Data) - {alg} ({n_clust} clusters)",
        "Weight Sum",
        f"{figures_dir}/weight_sum_all_data.png",
    )

    # Visualize cluster count distributions by cluster
    count_cols = [f"cluster_count_{i}" for i in range(num_clusters)]

    create_boxplot_by_label(
        data,
        count_cols,
        cluster_labels,
        f"Cluster Count by Cluster - {alg} ({n_clust} clusters)",
        "Cluster Count",
        f"{figures_dir}/cluster_count_by_label.png",
    )

    create_boxplot_all_data(
        data,
        count_cols,
        cluster_labels,
        f"Cluster Count by Cluster (All Data) - {alg} ({n_clust} clusters)",
        "Cluster Count",
        f"{figures_dir}/cluster_count_all_data.png",
    )

    # Add soft IoU columns for each method and cluster
    for method in CAM_METHODS:
        for i in range(num_clusters):
            calculate_iou(
                data,
                f"intersection_soft_count_{method}_{i}",
                f"union_soft_count_{method}_{i}",
                f"iou_soft_{method}_{i}",
            )

    # Add IoU columns for CAMs with annotation masks
    for method in CAM_METHODS:
        for mask_type in MASK_TYPES:
            calculate_iou(
                data,
                f"intersection_count_{method}_{mask_type}",
                f"union_count_{method}_{mask_type}",
                f"iou_{method}_{mask_type}",
            )

    # Add IoU columns for clusters with annotation masks
    for i in range(num_clusters):
        for mask_type in MASK_TYPES:
            # Hard cluster mask
            calculate_iou(
                data,
                f"intersection_count_cluster_{i}_{mask_type}",
                f"union_count_cluster_{i}_{mask_type}",
                f"iou_cluster_{i}_{mask_type}",
            )
            # Soft cluster mask
            calculate_iou(
                data,
                f"intersection_soft_count_cluster_{i}_{mask_type}",
                f"union_soft_count_cluster_{i}_{mask_type}",
                f"iou_soft_cluster_{i}_{mask_type}",
            )

    # Visualize for all CAM methods
    metrics = [
        ("iou", "IoU"),
        ("iou_soft", "Soft IoU"),
        ("correlation", "Correlation"),
        ("l2_distance", "L2 Distance"),
    ]

    for method in CAM_METHODS:
        for metric_suffix, metric_display in metrics:
            create_metric_plots(
                data,
                method,
                metric_suffix,
                metric_display,
                num_clusters,
                figures_dir,
                alg,
                n_clust,
            )

    # Visualize IoU with annotation masks - 2 plots per mask type (hard and soft)
    for mask_type in MASK_TYPES:
        mask_display = MASK_DISPLAYS[mask_type]
        create_annotation_mask_plots(
            data, mask_type, mask_display, num_clusters, figures_dir, alg, n_clust
        )

    # Create tables split by CAM method and label
    print(f"\n{'=' * 60}")
    print(f"Statistics (Mean ± Std) - {alg} ({n_clust} clusters)")
    print(f"{'=' * 60}\n")

    total_pixels = 32 * 32  # Total number of pixels

    # For each CAM method
    for method in CAM_METHODS:
        # For each label split (Overall, Label 0, Label 1)
        for label_filter in [None, 0, 1]:
            create_cam_cluster_table(
                data,
                method,
                label_filter,
                num_clusters,
                total_pixels,
                figures_dir,
                alg,
                n_clust,
            )

    # Create CAM-cluster comparison tables (Label 0 vs Label 1)
    print(f"\n{'=' * 60}")
    print(f"CAM-Cluster Comparison (Label 0 vs Label 1) - {alg} ({n_clust} clusters)")
    print(f"{'=' * 60}\n")
    for method in CAM_METHODS:
        create_cam_cluster_comparison_table(
            data,
            method,
            num_clusters,
            figures_dir,
            alg,
            n_clust,
        )

    # Create CAM IoU and Correlation tables
    print(f"\n{'=' * 60}")
    print(
        f"CAM IoU (All Data) and Correlation (Label 0, Label 1) - {alg} ({n_clust} clusters)"
    )
    print(f"{'=' * 60}\n")
    for method in CAM_METHODS:
        create_cam_iou_correlation_table(
            data,
            method,
            num_clusters,
            figures_dir,
            alg,
            n_clust,
        )

    # Create normalized cluster count comparison table
    print(f"\n{'=' * 60}")
    print(f"Normalized Cluster Count Comparison - {alg} ({n_clust} clusters)")
    print(f"{'=' * 60}\n")
    create_norm_count_comparison_table(
        data,
        num_clusters,
        total_pixels,
        figures_dir,
        alg,
        n_clust,
    )

    # Print statistics for annotation mask metrics
    print(f"\n{'=' * 60}")
    print(f"Annotation Mask Statistics - {alg} ({n_clust} clusters)")
    print(f"{'=' * 60}\n")

    # Comprehensive tables for annotation masks
    # For each annotation mask type, create 3 tables: all data, predicted label 0, predicted label 1
    for mask_type in MASK_TYPES:
        mask_display = MASK_DISPLAYS[mask_type]
        for label_filter in [None, 0, 1]:
            create_annotation_mask_table(
                data,
                mask_type,
                mask_display,
                num_clusters,
                figures_dir,
                alg,
                n_clust,
                label_filter,
            )

    # Create Carcinoma IoU comparison table
    print(f"\n{'=' * 60}")
    print(f"Carcinoma IoU Comparison - {alg} ({n_clust} clusters)")
    print(f"{'=' * 60}\n")
    create_carcinoma_iou_comparison_table(
        data,
        num_clusters,
        figures_dir,
        alg,
        n_clust,
    )

    print(f"\n{'=' * 80}\n")

================================================================================
Processing: NMF with 4 clusters
================================================================================

Label distribution:

label
0.0    8369
1.0    1631
Name: count, dtype: int64

Saved figure: figures/NMF_4/hist_predicted_prob.png

Prediction Metrics - NMF with 4 clusters:
============================================================
Number of samples: 10000

label             0.0   1.0
predicted_label
0                8093   124
1                 276  1507

Accuracy: 0.96
Precision: 0.8452047111609646
Recall: 0.923973022685469
F1 Score: 0.8828353837141183
AUC Score: 0.9844677288867657

Fitting linear regression model - NMF (4 clusters):
============================================================
Coefficients: [-0.03855283  0.04259869 -0.02857835  0.42907042]
Intercept: -2.761856093920791
R-squared: 0.7580769296044544

Fitting linear regression model (using cluster counts) - NMF (4 clusters):
============================================================
Coefficients: [-0.01626165  0.01086608 -0.01284096  0.01823652]
Intercept: 8.295282748419986
R-squared: 0.7395264688422954
Saved figure: figures/NMF_4/weight_sum_by_label.png
Saved figure: figures/NMF_4/weight_sum_all_data.png
Saved figure: figures/NMF_4/cluster_count_by_label.png
Saved figure: figures/NMF_4/cluster_count_all_data.png
Saved figure: figures/NMF_4/iou_by_label_grad_cam.png
Saved figure: figures/NMF_4/iou_all_data_grad_cam.png
Saved figure: figures/NMF_4/iou_soft_by_label_grad_cam.png
Saved figure: figures/NMF_4/iou_soft_all_data_grad_cam.png
Saved figure: figures/NMF_4/correlation_by_label_grad_cam.png
Saved figure: figures/NMF_4/correlation_all_data_grad_cam.png
Saved figure: figures/NMF_4/l2_distance_by_label_grad_cam.png
Saved figure: figures/NMF_4/l2_distance_all_data_grad_cam.png
Saved figure: figures/NMF_4/iou_by_label_grad_cam_pp.png
Saved figure: figures/NMF_4/iou_all_data_grad_cam_pp.png
Saved figure: figures/NMF_4/iou_soft_by_label_grad_cam_pp.png
Saved figure: figures/NMF_4/iou_soft_all_data_grad_cam_pp.png
Saved figure: figures/NMF_4/correlation_by_label_grad_cam_pp.png
Saved figure: figures/NMF_4/correlation_all_data_grad_cam_pp.png
Saved figure: figures/NMF_4/l2_distance_by_label_grad_cam_pp.png
Saved figure: figures/NMF_4/l2_distance_all_data_grad_cam_pp.png
Saved figure: figures/NMF_4/iou_by_label_layer_cam.png
Saved figure: figures/NMF_4/iou_all_data_layer_cam.png
Saved figure: figures/NMF_4/iou_soft_by_label_layer_cam.png
Saved figure: figures/NMF_4/iou_soft_all_data_layer_cam.png
Saved figure: figures/NMF_4/correlation_by_label_layer_cam.png
Saved figure: figures/NMF_4/correlation_all_data_layer_cam.png
Saved figure: figures/NMF_4/l2_distance_by_label_layer_cam.png
Saved figure: figures/NMF_4/l2_distance_all_data_layer_cam.png
Saved figure: figures/NMF_4/iou_hard_carcinoma.png
Saved figure: figures/NMF_4/iou_soft_carcinoma.png

============================================================
Statistics (Mean ± Std) - NMF (4 clusters)
============================================================


Grad-CAM - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,31.9184 ± 37.6553,517.6019 ± 188.9200,0.5055 ± 0.1845,0.0030 ± 0.0046,0.0550 ± 0.0671,0.0045 ± 0.0069,0.0606 ± 0.0630,-0.0840 ± 0.0493,1.9873 ± 1.7818
1,2,11.5654 ± 35.1601,142.2194 ± 199.3305,0.1389 ± 0.1947,0.1176 ± 0.1844,0.1436 ± 0.2098,0.3278 ± 0.1188,0.1905 ± 0.1479,0.7575 ± 0.2459,0.7441 ± 1.7254
2,3,19.6199 ± 21.1444,334.0306 ± 159.2210,0.3262 ± 0.1555,0.0066 ± 0.0122,0.0586 ± 0.0853,0.0118 ± 0.0172,0.0674 ± 0.0733,-0.0876 ± 0.0567,1.1961 ± 0.9772
3,4,4.0659 ± 9.6045,30.1481 ± 43.1152,0.0294 ± 0.0421,0.0225 ± 0.0368,0.0579 ± 0.0965,0.1158 ± 0.1038,0.0741 ± 0.0909,0.4551 ± 0.3281,0.4643 ± 0.8812

Saved table: figures/NMF_4/table_grad_cam_all.csv

Grad-CAM - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,37.1782 ± 39.0914,571.1207 ± 144.0812,0.5577 ± 0.1407,0.0027 ± 0.0045,0.0324 ± 0.0376,0.0043 ± 0.0070,0.0393 ± 0.0413,-0.0711 ± 0.0383,2.2682 ± 1.8022
1,2,0.9978 ± 1.9514,68.4706 ± 83.6153,0.0669 ± 0.0817,0.0485 ± 0.0664,0.0634 ± 0.0799,0.3041 ± 0.1193,0.1414 ± 0.1112,0.7222 ± 0.2605,0.1434 ± 0.2184
2,3,22.6323 ± 21.8680,366.4408 ± 149.5026,0.3579 ± 0.1460,0.0054 ± 0.0113,0.0357 ± 0.0593,0.0109 ± 0.0172,0.0470 ± 0.0562,-0.0743 ± 0.0445,1.3489 ± 0.9890
3,4,0.6396 ± 1.2427,17.9679 ± 25.0747,0.0175 ± 0.0245,0.0112 ± 0.0175,0.0214 ± 0.0295,0.1134 ± 0.1095,0.0396 ± 0.0473,0.4052 ± 0.3420,0.1262 ± 0.2162

Saved table: figures/NMF_4/table_grad_cam_label_0.csv

Grad-CAM - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,7.6786 ± 13.9679,270.9591 ± 174.5807,0.2646 ± 0.1705,0.0043 ± 0.0050,0.1593 ± 0.0743,0.0055 ± 0.0063,0.1592 ± 0.0509,-0.1361 ± 0.0544,0.6929 ± 0.8939
1,2,60.2663 ± 63.4902,482.0925 ± 223.7224,0.4708 ± 0.2185,0.4359 ± 0.2171,0.5136 ± 0.2255,0.4258 ± 0.0416,0.4171 ± 0.0565,0.8995 ± 0.0724,3.5125 ± 2.6742
2,3,5.7373 ± 8.3162,184.6674 ± 109.6952,0.1803 ± 0.1071,0.0117 ± 0.0145,0.1641 ± 0.1051,0.0159 ± 0.0170,0.1612 ± 0.0699,-0.1414 ± 0.0680,0.4917 ± 0.4946
3,4,19.8561 ± 14.3835,86.2810 ± 60.7868,0.0843 ± 0.0594,0.0742 ± 0.0542,0.2260 ± 0.1173,0.1257 ± 0.0753,0.2332 ± 0.0723,0.6562 ± 0.1403,2.0228 ± 1.0883

Saved table: figures/NMF_4/table_grad_cam_label_1.csv

Grad-CAM++ - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,31.9184 ± 37.6553,517.6019 ± 188.9200,0.5055 ± 0.1845,0.0141 ± 0.0145,0.0825 ± 0.0835,0.0193 ± 0.0185,0.0883 ± 0.0756,-0.0814 ± 0.0525,2.6477 ± 1.6543
1,2,11.5654 ± 35.1601,142.2194 ± 199.3305,0.1389 ± 0.1947,0.1258 ± 0.1876,0.1686 ± 0.2182,0.2932 ± 0.1322,0.2258 ± 0.1487,0.7564 ± 0.2509,0.8109 ± 1.1663
2,3,19.6199 ± 21.1444,334.0306 ± 159.2210,0.3262 ± 0.1555,0.0149 ± 0.0196,0.0788 ± 0.0932,0.0264 ± 0.0264,0.0903 ± 0.0792,-0.0812 ± 0.0770,1.9166 ± 1.1549
3,4,4.0659 ± 9.6045,30.1481 ± 43.1152,0.0294 ± 0.0421,0.0262 ± 0.0396,0.0724 ± 0.1012,0.1078 ± 0.0968,0.0930 ± 0.0925,0.4754 ± 0.3140,0.8489 ± 0.9491

Saved table: figures/NMF_4/table_grad_cam_pp_all.csv

Grad-CAM++ - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,37.1782 ± 39.0914,571.1207 ± 144.0812,0.5577 ± 0.1407,0.0140 ± 0.0150,0.0588 ± 0.0616,0.0196 ± 0.0193,0.0673 ± 0.0621,-0.0698 ± 0.0444,2.4627 ± 1.7377
1,2,0.9978 ± 1.9514,68.4706 ± 83.6153,0.0669 ± 0.0817,0.0560 ± 0.0720,0.0868 ± 0.0967,0.2645 ± 0.1286,0.1811 ± 0.1230,0.7330 ± 0.2707,0.4363 ± 0.4659
2,3,22.6323 ± 21.8680,366.4408 ± 149.5026,0.3579 ± 0.1460,0.0130 ± 0.0186,0.0547 ± 0.0690,0.0254 ± 0.0268,0.0706 ± 0.0666,-0.0684 ± 0.0728,1.5932 ± 0.9758
3,4,0.6396 ± 1.2427,17.9679 ± 25.0747,0.0175 ± 0.0245,0.0148 ± 0.0217,0.0355 ± 0.0416,0.1041 ± 0.1011,0.0608 ± 0.0593,0.4330 ± 0.3299,0.4766 ± 0.5126

Saved table: figures/NMF_4/table_grad_cam_pp_label_0.csv

Grad-CAM++ - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,7.6786 ± 13.9679,270.9591 ± 174.5807,0.2646 ± 0.1705,0.0146 ± 0.0118,0.1919 ± 0.0837,0.0177 ± 0.0141,0.1851 ± 0.0533,-0.1321 ± 0.0550,3.5006 ± 0.7397
1,2,60.2663 ± 63.4902,482.0925 ± 223.7224,0.4708 ± 0.2185,0.4473 ± 0.2182,0.5456 ± 0.2261,0.4196 ± 0.0440,0.4318 ± 0.0508,0.8590 ± 0.0692,2.5372 ± 1.7331
2,3,5.7373 ± 8.3162,184.6674 ± 109.6952,0.1803 ± 0.1071,0.0238 ± 0.0216,0.1900 ± 0.1084,0.0310 ± 0.0241,0.1813 ± 0.0679,-0.1368 ± 0.0701,3.4071 ± 0.6229
3,4,19.8561 ± 14.3835,86.2810 ± 60.7868,0.0843 ± 0.0594,0.0790 ± 0.0568,0.2423 ± 0.1199,0.1243 ± 0.0728,0.2413 ± 0.0705,0.6606 ± 0.1083,2.5645 ± 0.5084

Saved table: figures/NMF_4/table_grad_cam_pp_label_1.csv

Layer-CAM - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,31.9184 ± 37.6553,517.6019 ± 188.9200,0.5055 ± 0.1845,0.0010 ± 0.0015,0.0116 ± 0.0093,0.0018 ± 0.0026,0.0174 ± 0.0133,-0.0415 ± 0.0260,2.4761 ± 1.6358
1,2,11.5654 ± 35.1601,142.2194 ± 199.3305,0.1389 ± 0.1947,0.0194 ± 0.0176,0.0266 ± 0.0220,0.1433 ± 0.0864,0.0647 ± 0.0407,0.5597 ± 0.2282,0.9633 ± 1.6178
2,3,19.6199 ± 21.1444,334.0306 ± 159.2210,0.3262 ± 0.1555,0.0009 ± 0.0012,0.0087 ± 0.0060,0.0025 ± 0.0034,0.0152 ± 0.0108,-0.0392 ± 0.0545,1.7325 ± 1.0327
3,4,4.0659 ± 9.6045,30.1481 ± 43.1152,0.0294 ± 0.0421,0.0066 ± 0.0080,0.0158 ± 0.0159,0.0920 ± 0.0777,0.0360 ± 0.0352,0.3916 ± 0.2694,0.7765 ± 0.9414

Saved table: figures/NMF_4/table_layer_cam_all.csv

Layer-CAM - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,37.1782 ± 39.0914,571.1207 ± 144.0812,0.5577 ± 0.1407,0.0013 ± 0.0016,0.0117 ± 0.0099,0.0021 ± 0.0027,0.0162 ± 0.0135,-0.0404 ± 0.0271,2.4026 ± 1.7460
1,2,0.9978 ± 1.9514,68.4706 ± 83.6153,0.0669 ± 0.0817,0.0135 ± 0.0121,0.0190 ± 0.0156,0.1533 ± 0.0912,0.0594 ± 0.0418,0.5823 ± 0.2388,0.3886 ± 0.3839
2,3,22.6323 ± 21.8680,366.4408 ± 149.5026,0.3579 ± 0.1460,0.0011 ± 0.0013,0.0087 ± 0.0063,0.0030 ± 0.0036,0.0147 ± 0.0112,-0.0373 ± 0.0586,1.5214 ± 0.9548
3,4,0.6396 ± 1.2427,17.9679 ± 25.0747,0.0175 ± 0.0245,0.0046 ± 0.0060,0.0103 ± 0.0103,0.0894 ± 0.0816,0.0236 ± 0.0230,0.3713 ± 0.2856,0.4062 ± 0.3943

Saved table: figures/NMF_4/table_layer_cam_label_0.csv

Layer-CAM - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,7.6786 ± 13.9679,270.9591 ± 174.5807,0.2646 ± 0.1705,0.0001 ± 0.0003,0.0112 ± 0.0057,0.0002 ± 0.0008,0.0227 ± 0.0108,-0.0462 ± 0.0204,2.8153 ± 0.9048
1,2,60.2663 ± 63.4902,482.0925 ± 223.7224,0.4708 ± 0.2185,0.0466 ± 0.0125,0.0613 ± 0.0108,0.0993 ± 0.0367,0.0895 ± 0.0221,0.4614 ± 0.1359,3.6117 ± 2.3379
2,3,5.7373 ± 8.3162,184.6674 ± 109.6952,0.1803 ± 0.1071,0.0001 ± 0.0003,0.0084 ± 0.0045,0.0004 ± 0.0014,0.0175 ± 0.0087,-0.0472 ± 0.0294,2.7055 ± 0.7926
3,4,19.8561 ± 14.3835,86.2810 ± 60.7868,0.0843 ± 0.0594,0.0156 ± 0.0100,0.0415 ± 0.0110,0.1034 ± 0.0564,0.0933 ± 0.0226,0.4802 ± 0.1535,2.4829 ± 0.8424

Saved table: figures/NMF_4/table_layer_cam_label_1.csv

============================================================
CAM-Cluster Comparison (Label 0 vs Label 1) - NMF (4 clusters)
============================================================

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0043 ± 0.0070,-0.0711 ± 0.0383,2.2682 ± 1.8022,0.0055 ± 0.0063,-0.1361 ± 0.0544,0.6929 ± 0.8939
1,2,0.3041 ± 0.1193,0.7222 ± 0.2605,0.1434 ± 0.2184,0.4258 ± 0.0416,0.8995 ± 0.0724,3.5125 ± 2.6742
2,3,0.0109 ± 0.0172,-0.0743 ± 0.0445,1.3489 ± 0.9890,0.0159 ± 0.0170,-0.1414 ± 0.0680,0.4917 ± 0.4946
3,4,0.1134 ± 0.1095,0.4052 ± 0.3420,0.1262 ± 0.2162,0.1257 ± 0.0753,0.6562 ± 0.1403,2.0228 ± 1.0883

Saved table: figures/NMF_4/table_grad_cam_cluster_comparison.csv

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0196 ± 0.0193,-0.0698 ± 0.0444,2.4627 ± 1.7377,0.0177 ± 0.0141,-0.1321 ± 0.0550,3.5006 ± 0.7397
1,2,0.2645 ± 0.1286,0.7330 ± 0.2707,0.4363 ± 0.4659,0.4196 ± 0.0440,0.8590 ± 0.0692,2.5372 ± 1.7331
2,3,0.0254 ± 0.0268,-0.0684 ± 0.0728,1.5932 ± 0.9758,0.0310 ± 0.0241,-0.1368 ± 0.0701,3.4071 ± 0.6229
3,4,0.1041 ± 0.1011,0.4330 ± 0.3299,0.4766 ± 0.5126,0.1243 ± 0.0728,0.6606 ± 0.1083,2.5645 ± 0.5084

Saved table: figures/NMF_4/table_grad_cam_pp_cluster_comparison.csv

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0021 ± 0.0027,-0.0404 ± 0.0271,2.4026 ± 1.7460,0.0002 ± 0.0008,-0.0462 ± 0.0204,2.8153 ± 0.9048
1,2,0.1533 ± 0.0912,0.5823 ± 0.2388,0.3886 ± 0.3839,0.0993 ± 0.0367,0.4614 ± 0.1359,3.6117 ± 2.3379
2,3,0.0030 ± 0.0036,-0.0373 ± 0.0586,1.5214 ± 0.9548,0.0004 ± 0.0014,-0.0472 ± 0.0294,2.7055 ± 0.7926
3,4,0.0894 ± 0.0816,0.3713 ± 0.2856,0.4062 ± 0.3943,0.1034 ± 0.0564,0.4802 ± 0.1535,2.4829 ± 0.8424

Saved table: figures/NMF_4/table_layer_cam_cluster_comparison.csv

============================================================
CAM IoU (All Data) and Correlation (Label 0, Label 1) - NMF (4 clusters)
============================================================

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.0045 ± 0.0069      -0.0711 ± 0.0383      -0.1361 ± 0.0544
1        2  0.3278 ± 0.1188       0.7222 ± 0.2605       0.8995 ± 0.0724
2        3  0.0118 ± 0.0172      -0.0743 ± 0.0445      -0.1414 ± 0.0680
3        4  0.1158 ± 0.1038       0.4052 ± 0.3420       0.6562 ± 0.1403

Saved table: figures/NMF_4/table_grad_cam_iou_correlation.csv

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.0193 ± 0.0185      -0.0698 ± 0.0444      -0.1321 ± 0.0550
1        2  0.2932 ± 0.1322       0.7330 ± 0.2707       0.8590 ± 0.0692
2        3  0.0264 ± 0.0264      -0.0684 ± 0.0728      -0.1368 ± 0.0701
3        4  0.1078 ± 0.0968       0.4330 ± 0.3299       0.6606 ± 0.1083

Saved table: figures/NMF_4/table_grad_cam_pp_iou_correlation.csv

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.0018 ± 0.0026      -0.0404 ± 0.0271      -0.0462 ± 0.0204
1        2  0.1433 ± 0.0864       0.5823 ± 0.2388       0.4614 ± 0.1359
2        3  0.0025 ± 0.0034      -0.0373 ± 0.0586      -0.0472 ± 0.0294
3        4  0.0920 ± 0.0777       0.3713 ± 0.2856       0.4802 ± 0.1535

Saved table: figures/NMF_4/table_layer_cam_iou_correlation.csv

============================================================
Normalized Cluster Count Comparison - NMF (4 clusters)
============================================================

   Cluster         All Data          Label 0          Label 1
0        1  0.5055 ± 0.1845  0.5577 ± 0.1407  0.2646 ± 0.1705
1        2  0.1389 ± 0.1947  0.0669 ± 0.0817  0.4708 ± 0.2185
2        3  0.3262 ± 0.1555  0.3579 ± 0.1460  0.1803 ± 0.1071
3        4  0.0294 ± 0.0421  0.0175 ± 0.0245  0.0843 ± 0.0594

Saved table: figures/NMF_4/table_norm_count_comparison.csv

============================================================
Annotation Mask Statistics - NMF (4 clusters)
============================================================


Carcinoma Mask Metrics - All Data (n=1841):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.4200 ± 0.2724,0.5311 ± 0.2455,N/A,NaN
1,Grad-CAM++,0.4471 ± 0.2806,0.5584 ± 0.2502,N/A,NaN
2,Layer-CAM,0.0516 ± 0.0212,0.0920 ± 0.0526,N/A,NaN
3,Cluster 1,0.0984 ± 0.0919,0.0957 ± 0.0720,0.2332 ± 0.0990,0.2795 ± 0.1735
4,Cluster 2,0.3786 ± 0.2561,0.3068 ± 0.1175,0.3455 ± 0.1264,0.4943 ± 0.2915
5,Cluster 3,0.0959 ± 0.0965,0.1010 ± 0.0752,0.2210 ± 0.1029,0.2652 ± 0.1804
6,Cluster 4,0.0601 ± 0.0561,0.0776 ± 0.0560,0.2265 ± 0.0891,0.2574 ± 0.1525

Saved table: figures/NMF_4/table_carcinoma_all.csv

Carcinoma Mask Metrics - Predicted Label 0 (n=245):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.0800 ± 0.0938,0.1946 ± 0.1593,N/A,NaN
1,Grad-CAM++,0.0967 ± 0.1128,0.2150 ± 0.1688,N/A,NaN
2,Layer-CAM,0.0199 ± 0.0174,0.0903 ± 0.0879,N/A,NaN
3,Cluster 1,0.0846 ± 0.1142,0.0874 ± 0.0907,0.1516 ± 0.1307,0.1648 ± 0.1880
4,Cluster 2,0.0754 ± 0.0936,0.1393 ± 0.1045,0.1572 ± 0.1214,0.1352 ± 0.1595
5,Cluster 3,0.0806 ± 0.1236,0.0986 ± 0.0935,0.1489 ± 0.1312,0.1618 ± 0.2053
6,Cluster 4,0.0160 ± 0.0276,0.0407 ± 0.0510,0.1122 ± 0.0971,0.0955 ± 0.1204

Saved table: figures/NMF_4/table_carcinoma_label_0.csv

Carcinoma Mask Metrics - Predicted Label 1 (n=1596):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.4723 ± 0.2525,0.5828 ± 0.2135,N/A,NaN
1,Grad-CAM++,0.5009 ± 0.2592,0.6111 ± 0.2168,N/A,NaN
2,Layer-CAM,0.0565 ± 0.0171,0.0923 ± 0.0449,N/A,NaN
3,Cluster 1,0.1005 ± 0.0878,0.0970 ± 0.0687,0.2458 ± 0.0866,0.2972 ± 0.1642
4,Cluster 2,0.4251 ± 0.2410,0.3325 ± 0.0964,0.3744 ± 0.0994,0.5494 ± 0.2670
5,Cluster 3,0.0982 ± 0.0915,0.1013 ± 0.0720,0.2321 ± 0.0931,0.2811 ± 0.1709
6,Cluster 4,0.0669 ± 0.0563,0.0833 ± 0.0546,0.2441 ± 0.0736,0.2822 ± 0.1413

Saved table: figures/NMF_4/table_carcinoma_label_1.csv

============================================================
Carcinoma IoU Comparison - NMF (4 clusters)
============================================================

  Method/Cluster         All Data          Label 0          Label 1
0       Grad-CAM  0.5311 ± 0.2455  0.1946 ± 0.1593  0.5828 ± 0.2135
1     Grad-CAM++  0.5584 ± 0.2502  0.2150 ± 0.1688  0.6111 ± 0.2168
2      Layer-CAM  0.0920 ± 0.0526  0.0903 ± 0.0879  0.0923 ± 0.0449
3      Cluster 1  0.0957 ± 0.0720  0.0874 ± 0.0907  0.0970 ± 0.0687
4      Cluster 2  0.3068 ± 0.1175  0.1393 ± 0.1045  0.3325 ± 0.0964
5      Cluster 3  0.1010 ± 0.0752  0.0986 ± 0.0935  0.1013 ± 0.0720
6      Cluster 4  0.0776 ± 0.0560  0.0407 ± 0.0510  0.0833 ± 0.0546

Saved table: figures/NMF_4/table_carcinoma_iou_comparison.csv

================================================================================


================================================================================
Processing: NMF with 6 clusters
================================================================================

Label distribution:

label
0.0    8369
1.0    1631
Name: count, dtype: int64

Saved figure: figures/NMF_6/hist_predicted_prob.png

Prediction Metrics - NMF with 6 clusters:
============================================================
Number of samples: 10000

label             0.0   1.0
predicted_label
0                8093   124
1                 276  1507

Accuracy: 0.96
Precision: 0.8452047111609646
Recall: 0.923973022685469
F1 Score: 0.8828353837141183
AUC Score: 0.9844677288867657

Fitting linear regression model - NMF (6 clusters):
============================================================
Coefficients: [-0.03543218  0.003148   -0.04252527  0.2864983   0.24433947 -0.14065138]
Intercept: -0.6851108749120791
R-squared: 0.8355292112284505

Fitting linear regression model (using cluster counts) - NMF (6 clusters):
============================================================
Coefficients: [-0.01275302  0.01218383 -0.01650584  0.0319343   0.00345166 -0.01831094]
Intercept: 8.991093412241904
R-squared: 0.7766980902893685
Saved figure: figures/NMF_6/weight_sum_by_label.png
Saved figure: figures/NMF_6/weight_sum_all_data.png
Saved figure: figures/NMF_6/cluster_count_by_label.png
Saved figure: figures/NMF_6/cluster_count_all_data.png
Saved figure: figures/NMF_6/iou_by_label_grad_cam.png
Saved figure: figures/NMF_6/iou_all_data_grad_cam.png
Saved figure: figures/NMF_6/iou_soft_by_label_grad_cam.png
Saved figure: figures/NMF_6/iou_soft_all_data_grad_cam.png
Saved figure: figures/NMF_6/correlation_by_label_grad_cam.png
Saved figure: figures/NMF_6/correlation_all_data_grad_cam.png
Saved figure: figures/NMF_6/l2_distance_by_label_grad_cam.png
Saved figure: figures/NMF_6/l2_distance_all_data_grad_cam.png
Saved figure: figures/NMF_6/iou_by_label_grad_cam_pp.png
Saved figure: figures/NMF_6/iou_all_data_grad_cam_pp.png
Saved figure: figures/NMF_6/iou_soft_by_label_grad_cam_pp.png
Saved figure: figures/NMF_6/iou_soft_all_data_grad_cam_pp.png
Saved figure: figures/NMF_6/correlation_by_label_grad_cam_pp.png
Saved figure: figures/NMF_6/correlation_all_data_grad_cam_pp.png
Saved figure: figures/NMF_6/l2_distance_by_label_grad_cam_pp.png
Saved figure: figures/NMF_6/l2_distance_all_data_grad_cam_pp.png
Saved figure: figures/NMF_6/iou_by_label_layer_cam.png
Saved figure: figures/NMF_6/iou_all_data_layer_cam.png
Saved figure: figures/NMF_6/iou_soft_by_label_layer_cam.png
Saved figure: figures/NMF_6/iou_soft_all_data_layer_cam.png
Saved figure: figures/NMF_6/correlation_by_label_layer_cam.png
Saved figure: figures/NMF_6/correlation_all_data_layer_cam.png
Saved figure: figures/NMF_6/l2_distance_by_label_layer_cam.png
Saved figure: figures/NMF_6/l2_distance_all_data_layer_cam.png
Saved figure: figures/NMF_6/iou_hard_carcinoma.png
Saved figure: figures/NMF_6/iou_soft_carcinoma.png

============================================================
Statistics (Mean ± Std) - NMF (6 clusters)
============================================================


Grad-CAM - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,31.2580 ± 37.4893,373.4985 ± 174.5594,0.3647 ± 0.1705,0.0024 ± 0.0043,0.0199 ± 0.0226,0.0047 ± 0.0079,0.0294 ± 0.0286,-0.0787 ± 0.0479,1.9719 ± 1.7723
1,2,10.6151 ± 33.5771,104.0335 ± 166.4104,0.1016 ± 0.1625,0.0906 ± 0.1564,0.1349 ± 0.2038,0.2711 ± 0.1209,0.2870 ± 0.1442,0.6920 ± 0.2542,0.6843 ± 1.6657
2,3,19.2766 ± 20.8719,246.3407 ± 152.8369,0.2406 ± 0.1493,0.0058 ± 0.0115,0.0452 ± 0.0723,0.0123 ± 0.0185,0.0560 ± 0.0649,-0.0866 ± 0.0570,1.1793 ± 0.9644
3,4,3.8502 ± 9.1421,22.1061 ± 35.0101,0.0216 ± 0.0342,0.0190 ± 0.0319,0.0553 ± 0.0930,0.1056 ± 0.1022,0.0917 ± 0.0993,0.4412 ± 0.3226,0.4503 ± 0.8563
4,5,3.9982 ± 9.4538,29.3932 ± 39.4690,0.0287 ± 0.0385,0.0268 ± 0.0374,0.0712 ± 0.1078,0.1464 ± 0.0987,0.1379 ± 0.1092,0.5078 ± 0.2755,0.4557 ± 0.8045
5,6,12.9178 ± 13.5182,248.6280 ± 165.3862,0.2428 ± 0.1615,0.0050 ± 0.0063,0.1045 ± 0.1427,0.0115 ± 0.0137,0.1210 ± 0.1153,-0.0610 ± 0.0507,1.0221 ± 0.8796

Saved table: figures/NMF_6/table_grad_cam_all.csv

Grad-CAM - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,36.4067 ± 38.9863,411.0404 ± 156.3267,0.4014 ± 0.1527,0.0022 ± 0.0042,0.0129 ± 0.0144,0.0046 ± 0.0081,0.0217 ± 0.0229,-0.0670 ± 0.0382,2.2504 ± 1.7933
1,2,0.7867 ± 1.6801,42.1196 ± 56.3768,0.0411 ± 0.0551,0.0325 ± 0.0469,0.0568 ± 0.0735,0.2450 ± 0.1180,0.2524 ± 0.1361,0.6537 ± 0.2654,0.1161 ± 0.1898
2,3,22.2347 ± 21.5979,269.3669 ± 152.1107,0.2631 ± 0.1485,0.0048 ± 0.0107,0.0295 ± 0.0561,0.0117 ± 0.0188,0.0416 ± 0.0544,-0.0735 ± 0.0447,1.3299 ± 0.9762
3,4,0.5934 ± 1.1925,11.5968 ± 17.5057,0.0113 ± 0.0171,0.0092 ± 0.0148,0.0202 ± 0.0282,0.1040 ± 0.1087,0.0583 ± 0.0680,0.3925 ± 0.3362,0.1225 ± 0.2115
4,5,0.6969 ± 1.3091,16.9619 ± 24.3154,0.0166 ± 0.0237,0.0148 ± 0.0222,0.0308 ± 0.0418,0.1485 ± 0.1072,0.1054 ± 0.0895,0.4961 ± 0.3007,0.1464 ± 0.2348
5,6,14.9383 ± 13.9583,272.9143 ± 166.0249,0.2665 ± 0.1621,0.0044 ± 0.0059,0.0530 ± 0.0685,0.0115 ± 0.0144,0.0816 ± 0.0798,-0.0509 ± 0.0368,1.1632 ± 0.8936

Saved table: figures/NMF_6/table_grad_cam_label_0.csv

Grad-CAM - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,7.5302 ± 13.8864,200.4857 ± 147.8318,0.1958 ± 0.1444,0.0036 ± 0.0048,0.0518 ± 0.0257,0.0051 ± 0.0065,0.0647 ± 0.0256,-0.1256 ± 0.0543,0.6886 ± 0.8900
1,2,55.9096 ± 61.7651,389.3651 ± 203.9499,0.3802 ± 0.1992,0.3584 ± 0.1994,0.4948 ± 0.2248,0.3787 ± 0.0557,0.4423 ± 0.0381,0.8462 ± 0.1067,3.3031 ± 2.6554
2,3,5.6440 ± 8.2111,140.2238 ± 103.3507,0.1369 ± 0.1009,0.0105 ± 0.0136,0.1172 ± 0.0924,0.0152 ± 0.0169,0.1223 ± 0.0680,-0.1395 ± 0.0692,0.4853 ± 0.4884
3,4,18.8595 ± 13.7145,70.5384 ± 51.0726,0.0689 ± 0.0499,0.0639 ± 0.0472,0.2171 ± 0.1140,0.1119 ± 0.0691,0.2454 ± 0.0726,0.6374 ± 0.1414,1.9610 ± 1.0624
4,5,19.2123 ± 14.5510,86.6831 ± 44.9278,0.0847 ± 0.0439,0.0820 ± 0.0430,0.2571 ± 0.1228,0.1380 ± 0.0506,0.2881 ± 0.0499,0.5551 ± 0.1201,1.8807 ± 0.9513
5,6,3.6064 ± 4.6379,136.7039 ± 105.5381,0.1335 ± 0.1031,0.0078 ± 0.0073,0.3414 ± 0.1557,0.0116 ± 0.0097,0.3029 ± 0.0707,-0.1018 ± 0.0736,0.3719 ± 0.3816

Saved table: figures/NMF_6/table_grad_cam_label_1.csv

Grad-CAM++ - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,31.2580 ± 37.4893,373.4985 ± 174.5594,0.3647 ± 0.1705,0.0060 ± 0.0083,0.0327 ± 0.0317,0.0107 ± 0.0134,0.0460 ± 0.0379,-0.0776 ± 0.0507,2.6350 ± 1.6464
1,2,10.6151 ± 33.5771,104.0335 ± 166.4104,0.1016 ± 0.1625,0.0918 ± 0.1572,0.1538 ± 0.2112,0.2136 ± 0.1239,0.3202 ± 0.1401,0.6912 ± 0.2480,0.8700 ± 1.1999
2,3,19.2766 ± 20.8719,246.3407 ± 152.8369,0.2406 ± 0.1493,0.0120 ± 0.0185,0.0583 ± 0.0791,0.0242 ± 0.0276,0.0707 ± 0.0689,-0.0806 ± 0.0772,1.9023 ± 1.1507
3,4,3.8502 ± 9.1421,22.1061 ± 35.0101,0.0216 ± 0.0342,0.0196 ± 0.0324,0.0669 ± 0.0973,0.0798 ± 0.0825,0.1109 ± 0.1023,0.4615 ± 0.3102,0.8621 ± 0.9676
4,5,3.9982 ± 9.4538,29.3932 ± 39.4690,0.0287 ± 0.0385,0.0273 ± 0.0376,0.0839 ± 0.1118,0.1093 ± 0.0839,0.1604 ± 0.1110,0.5266 ± 0.2763,0.8641 ± 0.9868
5,6,12.9178 ± 13.5182,248.6280 ± 165.3862,0.2428 ± 0.1615,0.0243 ± 0.0289,0.1286 ± 0.1514,0.0490 ± 0.0471,0.1467 ± 0.1184,-0.0372 ± 0.0720,1.7444 ± 1.1623

Saved table: figures/NMF_6/table_grad_cam_pp_all.csv

Grad-CAM++ - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,36.4067 ± 38.9863,411.0404 ± 156.3267,0.4014 ± 0.1527,0.0054 ± 0.0077,0.0246 ± 0.0245,0.0104 ± 0.0135,0.0379 ± 0.0342,-0.0673 ± 0.0435,2.4474 ± 1.7274
1,2,0.7867 ± 1.6801,42.1196 ± 56.3768,0.0411 ± 0.0551,0.0334 ± 0.0475,0.0739 ± 0.0860,0.1795 ± 0.1082,0.2910 ± 0.1376,0.6684 ± 0.2657,0.4671 ± 0.5045
2,3,22.2347 ± 21.5979,269.3669 ± 152.1107,0.2631 ± 0.1485,0.0101 ± 0.0174,0.0413 ± 0.0629,0.0233 ± 0.0282,0.0561 ± 0.0598,-0.0681 ± 0.0730,1.5761 ± 0.9647
3,4,0.5934 ± 1.1925,11.5968 ± 17.5057,0.0113 ± 0.0171,0.0097 ± 0.0154,0.0311 ± 0.0377,0.0740 ± 0.0851,0.0804 ± 0.0799,0.4210 ± 0.3265,0.4815 ± 0.5198
4,5,0.6969 ± 1.3091,16.9619 ± 24.3154,0.0166 ± 0.0237,0.0152 ± 0.0225,0.0433 ± 0.0516,0.1047 ± 0.0896,0.1319 ± 0.0995,0.5103 ± 0.3006,0.4724 ± 0.5241
5,6,14.9383 ± 13.9583,272.9143 ± 166.0249,0.2665 ± 0.1621,0.0239 ± 0.0298,0.0766 ± 0.0856,0.0517 ± 0.0498,0.1099 ± 0.0922,-0.0247 ± 0.0662,1.3913 ± 0.9298

Saved table: figures/NMF_6/table_grad_cam_pp_label_0.csv

Grad-CAM++ - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,7.5302 ± 13.8864,200.4857 ± 147.8318,0.1958 ± 0.1444,0.0091 ± 0.0100,0.0697 ± 0.0346,0.0122 ± 0.0130,0.0829 ± 0.0321,-0.1227 ± 0.0554,3.4995 ± 0.7373
1,2,55.9096 ± 61.7651,389.3651 ± 203.9499,0.3802 ± 0.1992,0.3611 ± 0.2000,0.5221 ± 0.2258,0.3637 ± 0.0610,0.4528 ± 0.0355,0.7894 ± 0.1012,2.7266 ± 1.6457
2,3,5.6440 ± 8.2111,140.2238 ± 103.3507,0.1369 ± 0.1009,0.0207 ± 0.0206,0.1366 ± 0.0970,0.0286 ± 0.0243,0.1379 ± 0.0681,-0.1351 ± 0.0712,3.4056 ± 0.6220
3,4,18.8595 ± 13.7145,70.5384 ± 51.0726,0.0689 ± 0.0499,0.0651 ± 0.0478,0.2314 ± 0.1164,0.1053 ± 0.0640,0.2516 ± 0.0716,0.6386 ± 0.1110,2.6162 ± 0.5109
4,5,19.2123 ± 14.5510,86.6831 ± 44.9278,0.0847 ± 0.0439,0.0826 ± 0.0432,0.2710 ± 0.1232,0.1291 ± 0.0472,0.2921 ± 0.0485,0.5975 ± 0.0954,2.6693 ± 0.4788
5,6,3.6064 ± 4.6379,136.7039 ± 105.5381,0.1335 ± 0.1031,0.0261 ± 0.0243,0.3680 ± 0.1584,0.0363 ± 0.0288,0.3164 ± 0.0663,-0.0919 ± 0.0704,3.3721 ± 0.6073

Saved table: figures/NMF_6/table_grad_cam_pp_label_1.csv

Layer-CAM - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,31.2580 ± 37.4893,373.4985 ± 174.5594,0.3647 ± 0.1705,0.0004 ± 0.0008,0.0038 ± 0.0035,0.0011 ± 0.0023,0.0083 ± 0.0079,-0.0397 ± 0.0255,2.4630 ± 1.6268
1,2,10.6151 ± 33.5771,104.0335 ± 166.4104,0.1016 ± 0.1625,0.0123 ± 0.0136,0.0239 ± 0.0211,0.1068 ± 0.0772,0.1256 ± 0.0741,0.4896 ± 0.2283,0.9817 ± 1.6019
2,3,19.2766 ± 20.8719,246.3407 ± 152.8369,0.2406 ± 0.1493,0.0006 ± 0.0010,0.0057 ± 0.0044,0.0023 ± 0.0041,0.0110 ± 0.0087,-0.0389 ± 0.0548,1.7177 ± 1.0260
3,4,3.8502 ± 9.1421,22.1061 ± 35.0101,0.0216 ± 0.0342,0.0052 ± 0.0067,0.0148 ± 0.0152,0.0788 ± 0.0753,0.0503 ± 0.0457,0.3781 ± 0.2668,0.7816 ± 0.9441
4,5,3.9982 ± 9.4538,29.3932 ± 39.4690,0.0287 ± 0.0385,0.0070 ± 0.0068,0.0167 ± 0.0146,0.1137 ± 0.0841,0.0699 ± 0.0450,0.4289 ± 0.2548,0.7949 ± 0.9816
5,6,12.9178 ± 13.5182,248.6280 ± 165.3862,0.2428 ± 0.1615,0.0026 ± 0.0036,0.0181 ± 0.0132,0.0090 ± 0.0138,0.0332 ± 0.0223,-0.0176 ± 0.0441,1.5687 ± 1.0126

Saved table: figures/NMF_6/table_layer_cam_all.csv

Layer-CAM - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,36.4067 ± 38.9863,411.0404 ± 156.3267,0.4014 ± 0.1527,0.0005 ± 0.0009,0.0040 ± 0.0036,0.0013 ± 0.0024,0.0078 ± 0.0076,-0.0389 ± 0.0265,2.3869 ± 1.7355
1,2,0.7867 ± 1.6801,42.1196 ± 56.3768,0.0411 ± 0.0551,0.0075 ± 0.0078,0.0165 ± 0.0142,0.1116 ± 0.0832,0.1307 ± 0.0794,0.5106 ± 0.2392,0.4098 ± 0.4098
2,3,22.2347 ± 21.5979,269.3669 ± 152.1107,0.2631 ± 0.1485,0.0007 ± 0.0011,0.0058 ± 0.0046,0.0027 ± 0.0044,0.0107 ± 0.0087,-0.0372 ± 0.0589,1.5039 ± 0.9426
3,4,0.5934 ± 1.1925,11.5968 ± 17.5057,0.0113 ± 0.0171,0.0035 ± 0.0049,0.0094 ± 0.0097,0.0746 ± 0.0791,0.0380 ± 0.0392,0.3586 ± 0.2828,0.4102 ± 0.4000
4,5,0.6969 ± 1.3091,16.9619 ± 24.3154,0.0166 ± 0.0237,0.0052 ± 0.0056,0.0117 ± 0.0101,0.1157 ± 0.0913,0.0625 ± 0.0453,0.4353 ± 0.2748,0.4065 ± 0.4030
5,6,14.9383 ± 13.9583,272.9143 ± 166.0249,0.2665 ± 0.1621,0.0031 ± 0.0038,0.0160 ± 0.0130,0.0107 ± 0.0146,0.0304 ± 0.0228,-0.0134 ± 0.0464,1.3299 ± 0.8919

Saved table: figures/NMF_6/table_layer_cam_label_0.csv

Layer-CAM - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,7.5302 ± 13.8864,200.4857 ± 147.8318,0.1958 ± 0.1444,0.0001 ± 0.0002,0.0033 ± 0.0028,0.0002 ± 0.0009,0.0109 ± 0.0088,-0.0430 ± 0.0204,2.8137 ± 0.9026
1,2,55.9096 ± 61.7651,389.3651 ± 203.9499,0.3802 ± 0.1992,0.0340 ± 0.0133,0.0582 ± 0.0115,0.0857 ± 0.0341,0.1023 ± 0.0338,0.3987 ± 0.1417,3.6171 ± 2.2732
2,3,5.6440 ± 8.2111,140.2238 ± 103.3507,0.1369 ± 0.1009,0.0001 ± 0.0003,0.0052 ± 0.0035,0.0004 ± 0.0015,0.0127 ± 0.0084,-0.0466 ± 0.0299,2.7035 ± 0.7920
3,4,18.8595 ± 13.7145,70.5384 ± 51.0726,0.0689 ± 0.0499,0.0131 ± 0.0083,0.0396 ± 0.0109,0.0970 ± 0.0524,0.1069 ± 0.0269,0.4633 ± 0.1538,2.4936 ± 0.8338
4,5,19.2123 ± 14.5510,86.6831 ± 44.9278,0.0847 ± 0.0439,0.0150 ± 0.0060,0.0396 ± 0.0087,0.1049 ± 0.0377,0.1041 ± 0.0226,0.4010 ± 0.1327,2.5850 ± 0.8694
5,6,3.6064 ± 4.6379,136.7039 ± 105.5381,0.1335 ± 0.1031,0.0002 ± 0.0006,0.0279 ± 0.0090,0.0008 ± 0.0023,0.0460 ± 0.0138,-0.0357 ± 0.0254,2.6693 ± 0.7814

Saved table: figures/NMF_6/table_layer_cam_label_1.csv

============================================================
CAM-Cluster Comparison (Label 0 vs Label 1) - NMF (6 clusters)
============================================================

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0046 ± 0.0081,-0.0670 ± 0.0382,2.2504 ± 1.7933,0.0051 ± 0.0065,-0.1256 ± 0.0543,0.6886 ± 0.8900
1,2,0.2450 ± 0.1180,0.6537 ± 0.2654,0.1161 ± 0.1898,0.3787 ± 0.0557,0.8462 ± 0.1067,3.3031 ± 2.6554
2,3,0.0117 ± 0.0188,-0.0735 ± 0.0447,1.3299 ± 0.9762,0.0152 ± 0.0169,-0.1395 ± 0.0692,0.4853 ± 0.4884
3,4,0.1040 ± 0.1087,0.3925 ± 0.3362,0.1225 ± 0.2115,0.1119 ± 0.0691,0.6374 ± 0.1414,1.9610 ± 1.0624
4,5,0.1485 ± 0.1072,0.4961 ± 0.3007,0.1464 ± 0.2348,0.1380 ± 0.0506,0.5551 ± 0.1201,1.8807 ± 0.9513
5,6,0.0115 ± 0.0144,-0.0509 ± 0.0368,1.1632 ± 0.8936,0.0116 ± 0.0097,-0.1018 ± 0.0736,0.3719 ± 0.3816

Saved table: figures/NMF_6/table_grad_cam_cluster_comparison.csv

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0104 ± 0.0135,-0.0673 ± 0.0435,2.4474 ± 1.7274,0.0122 ± 0.0130,-0.1227 ± 0.0554,3.4995 ± 0.7373
1,2,0.1795 ± 0.1082,0.6684 ± 0.2657,0.4671 ± 0.5045,0.3637 ± 0.0610,0.7894 ± 0.1012,2.7266 ± 1.6457
2,3,0.0233 ± 0.0282,-0.0681 ± 0.0730,1.5761 ± 0.9647,0.0286 ± 0.0243,-0.1351 ± 0.0712,3.4056 ± 0.6220
3,4,0.0740 ± 0.0851,0.4210 ± 0.3265,0.4815 ± 0.5198,0.1053 ± 0.0640,0.6386 ± 0.1110,2.6162 ± 0.5109
4,5,0.1047 ± 0.0896,0.5103 ± 0.3006,0.4724 ± 0.5241,0.1291 ± 0.0472,0.5975 ± 0.0954,2.6693 ± 0.4788
5,6,0.0517 ± 0.0498,-0.0247 ± 0.0662,1.3913 ± 0.9298,0.0363 ± 0.0288,-0.0919 ± 0.0704,3.3721 ± 0.6073

Saved table: figures/NMF_6/table_grad_cam_pp_cluster_comparison.csv

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0013 ± 0.0024,-0.0389 ± 0.0265,2.3869 ± 1.7355,0.0002 ± 0.0009,-0.0430 ± 0.0204,2.8137 ± 0.9026
1,2,0.1116 ± 0.0832,0.5106 ± 0.2392,0.4098 ± 0.4098,0.0857 ± 0.0341,0.3987 ± 0.1417,3.6171 ± 2.2732
2,3,0.0027 ± 0.0044,-0.0372 ± 0.0589,1.5039 ± 0.9426,0.0004 ± 0.0015,-0.0466 ± 0.0299,2.7035 ± 0.7920
3,4,0.0746 ± 0.0791,0.3586 ± 0.2828,0.4102 ± 0.4000,0.0970 ± 0.0524,0.4633 ± 0.1538,2.4936 ± 0.8338
4,5,0.1157 ± 0.0913,0.4353 ± 0.2748,0.4065 ± 0.4030,0.1049 ± 0.0377,0.4010 ± 0.1327,2.5850 ± 0.8694
5,6,0.0107 ± 0.0146,-0.0134 ± 0.0464,1.3299 ± 0.8919,0.0008 ± 0.0023,-0.0357 ± 0.0254,2.6693 ± 0.7814

Saved table: figures/NMF_6/table_layer_cam_cluster_comparison.csv

============================================================
CAM IoU (All Data) and Correlation (Label 0, Label 1) - NMF (6 clusters)
============================================================

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.0047 ± 0.0079      -0.0670 ± 0.0382      -0.1256 ± 0.0543
1        2  0.2711 ± 0.1209       0.6537 ± 0.2654       0.8462 ± 0.1067
2        3  0.0123 ± 0.0185      -0.0735 ± 0.0447      -0.1395 ± 0.0692
3        4  0.1056 ± 0.1022       0.3925 ± 0.3362       0.6374 ± 0.1414
4        5  0.1464 ± 0.0987       0.4961 ± 0.3007       0.5551 ± 0.1201
5        6  0.0115 ± 0.0137      -0.0509 ± 0.0368      -0.1018 ± 0.0736

Saved table: figures/NMF_6/table_grad_cam_iou_correlation.csv

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.0107 ± 0.0134      -0.0673 ± 0.0435      -0.1227 ± 0.0554
1        2  0.2136 ± 0.1239       0.6684 ± 0.2657       0.7894 ± 0.1012
2        3  0.0242 ± 0.0276      -0.0681 ± 0.0730      -0.1351 ± 0.0712
3        4  0.0798 ± 0.0825       0.4210 ± 0.3265       0.6386 ± 0.1110
4        5  0.1093 ± 0.0839       0.5103 ± 0.3006       0.5975 ± 0.0954
5        6  0.0490 ± 0.0471      -0.0247 ± 0.0662      -0.0919 ± 0.0704

Saved table: figures/NMF_6/table_grad_cam_pp_iou_correlation.csv

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.0011 ± 0.0023      -0.0389 ± 0.0265      -0.0430 ± 0.0204
1        2  0.1068 ± 0.0772       0.5106 ± 0.2392       0.3987 ± 0.1417
2        3  0.0023 ± 0.0041      -0.0372 ± 0.0589      -0.0466 ± 0.0299
3        4  0.0788 ± 0.0753       0.3586 ± 0.2828       0.4633 ± 0.1538
4        5  0.1137 ± 0.0841       0.4353 ± 0.2748       0.4010 ± 0.1327
5        6  0.0090 ± 0.0138      -0.0134 ± 0.0464      -0.0357 ± 0.0254

Saved table: figures/NMF_6/table_layer_cam_iou_correlation.csv

============================================================
Normalized Cluster Count Comparison - NMF (6 clusters)
============================================================

   Cluster         All Data          Label 0          Label 1
0        1  0.3647 ± 0.1705  0.4014 ± 0.1527  0.1958 ± 0.1444
1        2  0.1016 ± 0.1625  0.0411 ± 0.0551  0.3802 ± 0.1992
2        3  0.2406 ± 0.1493  0.2631 ± 0.1485  0.1369 ± 0.1009
3        4  0.0216 ± 0.0342  0.0113 ± 0.0171  0.0689 ± 0.0499
4        5  0.0287 ± 0.0385  0.0166 ± 0.0237  0.0847 ± 0.0439
5        6  0.2428 ± 0.1615  0.2665 ± 0.1621  0.1335 ± 0.1031

Saved table: figures/NMF_6/table_norm_count_comparison.csv

============================================================
Annotation Mask Statistics - NMF (6 clusters)
============================================================


Carcinoma Mask Metrics - All Data (n=1841):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.4200 ± 0.2724,0.5311 ± 0.2455,N/A,NaN
1,Grad-CAM++,0.4471 ± 0.2806,0.5584 ± 0.2502,N/A,NaN
2,Layer-CAM,0.0516 ± 0.0212,0.0920 ± 0.0526,N/A,NaN
3,Cluster 1,0.0689 ± 0.0695,0.0732 ± 0.0618,0.1528 ± 0.0906,0.1577 ± 0.1294
4,Cluster 2,0.3093 ± 0.2249,0.2687 ± 0.1123,0.3417 ± 0.1194,0.4526 ± 0.2803
5,Cluster 3,0.0862 ± 0.0924,0.0963 ± 0.0761,0.1889 ± 0.1042,0.2168 ± 0.1706
6,Cluster 4,0.0494 ± 0.0465,0.0656 ± 0.0490,0.2183 ± 0.0828,0.2293 ± 0.1393
7,Cluster 5,0.0656 ± 0.0474,0.0851 ± 0.0432,0.2249 ± 0.0843,0.2416 ± 0.1498
8,Cluster 6,0.0535 ± 0.0721,0.0596 ± 0.0624,0.2711 ± 0.1081,0.3555 ± 0.2094

Saved table: figures/NMF_6/table_carcinoma_all.csv

Carcinoma Mask Metrics - Predicted Label 0 (n=245):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.0800 ± 0.0938,0.1946 ± 0.1593,N/A,NaN
1,Grad-CAM++,0.0967 ± 0.1128,0.2150 ± 0.1688,N/A,NaN
2,Layer-CAM,0.0199 ± 0.0174,0.0903 ± 0.0879,N/A,NaN
3,Cluster 1,0.0572 ± 0.0789,0.0717 ± 0.0742,0.1287 ± 0.1122,0.1168 ± 0.1437
4,Cluster 2,0.0548 ± 0.0703,0.1148 ± 0.0908,0.1645 ± 0.1135,0.1066 ± 0.1244
5,Cluster 3,0.0733 ± 0.1174,0.1023 ± 0.0942,0.1406 ± 0.1278,0.1460 ± 0.1966
6,Cluster 4,0.0120 ± 0.0216,0.0322 ± 0.0440,0.1107 ± 0.0848,0.0739 ± 0.0909
7,Cluster 5,0.0172 ± 0.0223,0.0502 ± 0.0466,0.1083 ± 0.0801,0.0648 ± 0.0741
8,Cluster 6,0.0422 ± 0.0827,0.0548 ± 0.0775,0.1345 ± 0.1148,0.1332 ± 0.1611

Saved table: figures/NMF_6/table_carcinoma_label_0.csv

Carcinoma Mask Metrics - Predicted Label 1 (n=1596):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.4723 ± 0.2525,0.5828 ± 0.2135,N/A,NaN
1,Grad-CAM++,0.5009 ± 0.2592,0.6111 ± 0.2168,N/A,NaN
2,Layer-CAM,0.0565 ± 0.0171,0.0923 ± 0.0449,N/A,NaN
3,Cluster 1,0.0707 ± 0.0678,0.0734 ± 0.0596,0.1565 ± 0.0862,0.1640 ± 0.1259
4,Cluster 2,0.3484 ± 0.2147,0.2923 ± 0.0954,0.3689 ± 0.0945,0.5057 ± 0.2590
5,Cluster 3,0.0882 ± 0.0879,0.0954 ± 0.0729,0.1963 ± 0.0980,0.2277 ± 0.1636
6,Cluster 4,0.0552 ± 0.0467,0.0707 ± 0.0477,0.2348 ± 0.0690,0.2532 ± 0.1297
7,Cluster 5,0.0731 ± 0.0458,0.0905 ± 0.0400,0.2428 ± 0.0694,0.2687 ± 0.1397
8,Cluster 6,0.0552 ± 0.0702,0.0604 ± 0.0598,0.2921 ± 0.0904,0.3896 ± 0.1946

Saved table: figures/NMF_6/table_carcinoma_label_1.csv

============================================================
Carcinoma IoU Comparison - NMF (6 clusters)
============================================================

  Method/Cluster         All Data          Label 0          Label 1
0       Grad-CAM  0.5311 ± 0.2455  0.1946 ± 0.1593  0.5828 ± 0.2135
1     Grad-CAM++  0.5584 ± 0.2502  0.2150 ± 0.1688  0.6111 ± 0.2168
2      Layer-CAM  0.0920 ± 0.0526  0.0903 ± 0.0879  0.0923 ± 0.0449
3      Cluster 1  0.0732 ± 0.0618  0.0717 ± 0.0742  0.0734 ± 0.0596
4      Cluster 2  0.2687 ± 0.1123  0.1148 ± 0.0908  0.2923 ± 0.0954
5      Cluster 3  0.0963 ± 0.0761  0.1023 ± 0.0942  0.0954 ± 0.0729
6      Cluster 4  0.0656 ± 0.0490  0.0322 ± 0.0440  0.0707 ± 0.0477
7      Cluster 5  0.0851 ± 0.0432  0.0502 ± 0.0466  0.0905 ± 0.0400
8      Cluster 6  0.0596 ± 0.0624  0.0548 ± 0.0775  0.0604 ± 0.0598

Saved table: figures/NMF_6/table_carcinoma_iou_comparison.csv

================================================================================


================================================================================
Processing: NMF with 8 clusters
================================================================================

Label distribution:

label
0.0    8369
1.0    1631
Name: count, dtype: int64

Saved figure: figures/NMF_8/hist_predicted_prob.png

Prediction Metrics - NMF with 8 clusters:
============================================================
Number of samples: 10000

label             0.0   1.0
predicted_label
0                8093   124
1                 276  1507

Accuracy: 0.96
Precision: 0.8452047111609646
Recall: 0.923973022685469
F1 Score: 0.8828353837141183
AUC Score: 0.9844677288867657

Fitting linear regression model - NMF (8 clusters):
============================================================
Coefficients: [-0.00269494 -0.00997897 -0.05648105  0.25673287  0.13563866 -0.13939088
 -0.10783019  0.1718398 ]
Intercept: -0.4595215099490202
R-squared: 0.8537711666852698

Fitting linear regression model (using cluster counts) - NMF (8 clusters):
============================================================
Coefficients: [-0.01269643  0.00973076 -0.01786801  0.02238993  0.03184059 -0.01970803
 -0.01826049  0.00457168]
Intercept: 10.226317833343737
R-squared: 0.7819119214788327
Saved figure: figures/NMF_8/weight_sum_by_label.png
Saved figure: figures/NMF_8/weight_sum_all_data.png
Saved figure: figures/NMF_8/cluster_count_by_label.png
Saved figure: figures/NMF_8/cluster_count_all_data.png
Saved figure: figures/NMF_8/iou_by_label_grad_cam.png
Saved figure: figures/NMF_8/iou_all_data_grad_cam.png
Saved figure: figures/NMF_8/iou_soft_by_label_grad_cam.png
Saved figure: figures/NMF_8/iou_soft_all_data_grad_cam.png
Saved figure: figures/NMF_8/correlation_by_label_grad_cam.png
Saved figure: figures/NMF_8/correlation_all_data_grad_cam.png
Saved figure: figures/NMF_8/l2_distance_by_label_grad_cam.png
Saved figure: figures/NMF_8/l2_distance_all_data_grad_cam.png
Saved figure: figures/NMF_8/iou_by_label_grad_cam_pp.png
Saved figure: figures/NMF_8/iou_all_data_grad_cam_pp.png
Saved figure: figures/NMF_8/iou_soft_by_label_grad_cam_pp.png
Saved figure: figures/NMF_8/iou_soft_all_data_grad_cam_pp.png
Saved figure: figures/NMF_8/correlation_by_label_grad_cam_pp.png
Saved figure: figures/NMF_8/correlation_all_data_grad_cam_pp.png
Saved figure: figures/NMF_8/l2_distance_by_label_grad_cam_pp.png
Saved figure: figures/NMF_8/l2_distance_all_data_grad_cam_pp.png
Saved figure: figures/NMF_8/iou_by_label_layer_cam.png
Saved figure: figures/NMF_8/iou_all_data_layer_cam.png
Saved figure: figures/NMF_8/iou_soft_by_label_layer_cam.png
Saved figure: figures/NMF_8/iou_soft_all_data_layer_cam.png
Saved figure: figures/NMF_8/correlation_by_label_layer_cam.png
Saved figure: figures/NMF_8/correlation_all_data_layer_cam.png
Saved figure: figures/NMF_8/l2_distance_by_label_layer_cam.png
Saved figure: figures/NMF_8/l2_distance_all_data_layer_cam.png
Saved figure: figures/NMF_8/iou_hard_carcinoma.png
Saved figure: figures/NMF_8/iou_soft_carcinoma.png

============================================================
Statistics (Mean ± Std) - NMF (8 clusters)
============================================================


Grad-CAM - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,28.7311 ± 34.9587,292.6084 ± 160.5276,0.2858 ± 0.1568,0.0005 ± 0.0011,0.0112 ± 0.0131,0.0011 ± 0.0026,0.0183 ± 0.0184,-0.0733 ± 0.0449,1.8976 ± 1.7106
1,2,9.4939 ± 31.6645,55.7436 ± 116.2560,0.0544 ± 0.1135,0.0522 ± 0.1120,0.1024 ± 0.1798,0.1559 ± 0.1210,0.2328 ± 0.1488,0.5752 ± 0.3157,0.6323 ± 1.6088
2,3,18.9758 ± 20.4094,221.8549 ± 151.0223,0.2167 ± 0.1475,0.0043 ± 0.0092,0.0402 ± 0.0652,0.0096 ± 0.0161,0.0507 ± 0.0599,-0.0873 ± 0.0575,1.1559 ± 0.9408
3,4,3.6686 ± 8.7480,19.4760 ± 31.7608,0.0190 ± 0.0310,0.0167 ± 0.0288,0.0525 ± 0.0894,0.0935 ± 0.0982,0.0991 ± 0.1014,0.4355 ± 0.3211,0.4349 ± 0.8305
4,5,3.7614 ± 8.9888,18.5106 ± 26.6914,0.0181 ± 0.0261,0.0172 ± 0.0255,0.0628 ± 0.0987,0.0932 ± 0.0775,0.1077 ± 0.0990,0.4782 ± 0.2788,0.4400 ± 0.7835
5,6,11.8332 ± 12.6516,230.2249 ± 153.0145,0.2248 ± 0.1494,0.0037 ± 0.0047,0.0753 ± 0.1016,0.0090 ± 0.0115,0.0962 ± 0.0933,-0.0613 ± 0.0483,0.9714 ± 0.8516
6,7,11.1722 ± 11.9353,120.0954 ± 77.4270,0.1173 ± 0.0756,0.0028 ± 0.0043,0.0546 ± 0.0750,0.0103 ± 0.0143,0.0710 ± 0.0731,-0.0749 ± 0.0498,0.8692 ± 0.8204
7,8,4.5954 ± 11.0829,65.4862 ± 93.7318,0.0640 ± 0.0915,0.0524 ± 0.0816,0.1050 ± 0.1516,0.2196 ± 0.1149,0.1415 ± 0.1239,0.5029 ± 0.2476,0.4235 ± 0.7371

Saved table: figures/NMF_8/table_grad_cam_all.csv

Grad-CAM - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,33.4805 ± 36.3911,320.6645 ± 151.4090,0.3131 ± 0.1479,0.0004 ± 0.0010,0.0078 ± 0.0096,0.0010 ± 0.0026,0.0144 ± 0.0160,-0.0625 ± 0.0359,2.1661 ± 1.7304
1,2,0.5808 ± 1.4277,15.3472 ± 23.0145,0.0150 ± 0.0225,0.0134 ± 0.0209,0.0333 ± 0.0453,0.1260 ± 0.1088,0.1919 ± 0.1318,0.5130 ± 0.3191,0.0951 ± 0.1755
2,3,21.8820 ± 21.1070,242.9067 ± 151.9366,0.2372 ± 0.1484,0.0036 ± 0.0087,0.0273 ± 0.0528,0.0093 ± 0.0165,0.0387 ± 0.0518,-0.0741 ± 0.0452,1.3030 ± 0.9520
3,4,0.5531 ± 1.1330,10.0591 ± 15.8763,0.0098 ± 0.0155,0.0080 ± 0.0134,0.0190 ± 0.0272,0.0916 ± 0.1047,0.0673 ± 0.0757,0.3866 ± 0.3341,0.1167 ± 0.2034
4,5,0.6327 ± 1.2140,9.3324 ± 13.1398,0.0091 ± 0.0128,0.0083 ± 0.0120,0.0258 ± 0.0346,0.0910 ± 0.0842,0.0744 ± 0.0712,0.4604 ± 0.3031,0.1387 ± 0.2263
5,6,13.6965 ± 13.0960,253.3069 ± 153.6620,0.2474 ± 0.1501,0.0032 ± 0.0044,0.0387 ± 0.0488,0.0090 ± 0.0122,0.0644 ± 0.0642,-0.0495 ± 0.0353,1.1054 ± 0.8680
6,7,12.9459 ± 12.2977,133.3903 ± 76.5642,0.1303 ± 0.0748,0.0026 ± 0.0043,0.0328 ± 0.0512,0.0110 ± 0.0152,0.0499 ± 0.0571,-0.0617 ± 0.0363,0.9913 ± 0.8383
7,8,0.8605 ± 1.4086,38.9929 ± 60.2298,0.0381 ± 0.0588,0.0285 ± 0.0490,0.0500 ± 0.0681,0.2194 ± 0.1218,0.1013 ± 0.0928,0.5116 ± 0.2683,0.1444 ± 0.1952

Saved table: figures/NMF_8/table_grad_cam_label_0.csv

Grad-CAM - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,6.8435 ± 12.9714,163.3113 ± 136.1665,0.1595 ± 0.1330,0.0010 ± 0.0015,0.0267 ± 0.0155,0.0015 ± 0.0024,0.0361 ± 0.0183,-0.1168 ± 0.0509,0.6600 ± 0.8653
1,2,50.5701 ± 59.6825,241.9114 ± 176.6126,0.2362 ± 0.1725,0.2309 ± 0.1717,0.4208 ± 0.2204,0.2771 ± 0.0876,0.4142 ± 0.0557,0.8215 ± 0.1237,3.1076 ± 2.6306
2,3,5.5825 ± 8.0501,124.8374 ± 100.4106,0.1219 ± 0.0981,0.0074 ± 0.0108,0.0996 ± 0.0818,0.0110 ± 0.0140,0.1062 ± 0.0634,-0.1404 ± 0.0699,0.4778 ± 0.4767
3,4,18.0263 ± 13.1328,62.8738 ± 46.9549,0.0614 ± 0.0459,0.0568 ± 0.0432,0.2072 ± 0.1109,0.1012 ± 0.0650,0.2458 ± 0.0713,0.6325 ± 0.1431,1.9013 ± 1.0300
4,5,18.1799 ± 13.9080,60.8087 ± 31.9829,0.0594 ± 0.0312,0.0581 ± 0.0309,0.2337 ± 0.1165,0.1023 ± 0.0395,0.2609 ± 0.0551,0.5498 ± 0.1192,1.8283 ± 0.9281
5,6,3.2464 ± 4.1972,123.8508 ± 93.4476,0.1209 ± 0.0913,0.0059 ± 0.0056,0.2437 ± 0.1113,0.0091 ± 0.0078,0.2429 ± 0.0602,-0.1091 ± 0.0622,0.3539 ± 0.3627
6,7,2.9979 ± 4.5472,58.8256 ± 45.1631,0.0574 ± 0.0441,0.0037 ± 0.0045,0.1552 ± 0.0844,0.0069 ± 0.0082,0.1680 ± 0.0588,-0.1283 ± 0.0601,0.3064 ± 0.3879
7,8,21.8079 ± 17.8693,187.5810 ± 120.0827,0.1832 ± 0.1173,0.1622 ± 0.1078,0.3587 ± 0.1710,0.2203 ± 0.0804,0.3260 ± 0.0697,0.4680 ± 0.1294,1.7093 ± 0.9273

Saved table: figures/NMF_8/table_grad_cam_label_1.csv

Grad-CAM++ - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,28.7311 ± 34.9587,292.6084 ± 160.5276,0.2858 ± 0.1568,0.0023 ± 0.0037,0.0215 ± 0.0216,0.0048 ± 0.0071,0.0333 ± 0.0284,-0.0726 ± 0.0478,2.5682 ± 1.5991
1,2,9.4939 ± 31.6645,55.7436 ± 116.2560,0.0544 ± 0.1135,0.0528 ± 0.1126,0.1154 ± 0.1855,0.1201 ± 0.1101,0.2539 ± 0.1481,0.5757 ± 0.2978,0.8977 ± 1.2041
2,3,18.9758 ± 20.4094,221.8549 ± 151.0223,0.2167 ± 0.1475,0.0100 ± 0.0161,0.0528 ± 0.0723,0.0215 ± 0.0264,0.0649 ± 0.0645,-0.0812 ± 0.0780,1.8817 ± 1.1412
3,4,3.6686 ± 8.7480,19.4760 ± 31.7608,0.0190 ± 0.0310,0.0172 ± 0.0293,0.0628 ± 0.0936,0.0702 ± 0.0784,0.1183 ± 0.1042,0.4561 ± 0.3090,0.8670 ± 0.9715
4,5,3.7614 ± 8.9888,18.5106 ± 26.6914,0.0181 ± 0.0261,0.0176 ± 0.0258,0.0742 ± 0.1023,0.0689 ± 0.0618,0.1254 ± 0.0998,0.4953 ± 0.2800,0.8715 ± 0.9915
5,6,11.8332 ± 12.6516,230.2249 ± 153.0145,0.2248 ± 0.1494,0.0216 ± 0.0257,0.0989 ± 0.1130,0.0463 ± 0.0449,0.1241 ± 0.1005,-0.0362 ± 0.0728,1.7030 ± 1.1614
6,7,11.1722 ± 11.9353,120.0954 ± 77.4270,0.1173 ± 0.0756,0.0058 ± 0.0074,0.0700 ± 0.0806,0.0188 ± 0.0206,0.0890 ± 0.0765,-0.0701 ± 0.0516,1.6514 ± 1.1494
7,8,4.5954 ± 11.0829,65.4862 ± 93.7318,0.0640 ± 0.0915,0.0538 ± 0.0823,0.1244 ± 0.1580,0.1732 ± 0.1069,0.1696 ± 0.1283,0.5154 ± 0.2488,0.9071 ± 1.0608

Saved table: figures/NMF_8/table_grad_cam_pp_all.csv

Grad-CAM++ - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,33.4805 ± 36.3911,320.6645 ± 151.4090,0.3131 ± 0.1479,0.0019 ± 0.0030,0.0170 ± 0.0180,0.0045 ± 0.0069,0.0289 ± 0.0267,-0.0631 ± 0.0413,2.3680 ± 1.6653
1,2,0.5808 ± 1.4277,15.3472 ± 23.0145,0.0150 ± 0.0225,0.0138 ± 0.0213,0.0448 ± 0.0566,0.0871 ± 0.0851,0.2176 ± 0.1371,0.5314 ± 0.3106,0.4873 ± 0.5242
2,3,21.8820 ± 21.1070,242.9067 ± 151.9366,0.2372 ± 0.1484,0.0086 ± 0.0154,0.0385 ± 0.0597,0.0211 ± 0.0273,0.0525 ± 0.0573,-0.0687 ± 0.0739,1.5515 ± 0.9435
3,4,0.5531 ± 1.1330,10.0591 ± 15.8763,0.0098 ± 0.0155,0.0084 ± 0.0139,0.0286 ± 0.0362,0.0646 ± 0.0809,0.0897 ± 0.0867,0.4155 ± 0.3249,0.4851 ± 0.5237
4,5,0.6327 ± 1.2140,9.3324 ± 13.1398,0.0091 ± 0.0128,0.0086 ± 0.0124,0.0369 ± 0.0443,0.0628 ± 0.0648,0.0953 ± 0.0802,0.4729 ± 0.3026,0.4783 ± 0.5284
5,6,13.6965 ± 13.0960,253.3069 ± 153.6620,0.2474 ± 0.1501,0.0213 ± 0.0264,0.0619 ± 0.0695,0.0492 ± 0.0474,0.0948 ± 0.0819,-0.0218 ± 0.0676,1.3409 ± 0.9093
6,7,12.9459 ± 12.2977,133.3903 ± 76.5642,0.1303 ± 0.0748,0.0055 ± 0.0074,0.0476 ± 0.0592,0.0202 ± 0.0217,0.0691 ± 0.0650,-0.0581 ± 0.0405,1.2780 ± 0.8616
7,8,0.8605 ± 1.4086,38.9929 ± 60.2298,0.0381 ± 0.0588,0.0297 ± 0.0495,0.0683 ± 0.0798,0.1647 ± 0.1108,0.1330 ± 0.1077,0.5261 ± 0.2691,0.4845 ± 0.5527

Saved table: figures/NMF_8/table_grad_cam_pp_label_0.csv

Grad-CAM++ - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,6.8435 ± 12.9714,163.3113 ± 136.1665,0.1595 ± 0.1330,0.0042 ± 0.0053,0.0420 ± 0.0247,0.0061 ± 0.0078,0.0537 ± 0.0270,-0.1144 ± 0.0517,3.4908 ± 0.7249
1,2,50.5701 ± 59.6825,241.9114 ± 176.6126,0.2362 ± 0.1725,0.2325 ± 0.1724,0.4404 ± 0.2228,0.2642 ± 0.0892,0.4180 ± 0.0570,0.7620 ± 0.1145,2.7893 ± 1.5847
2,3,5.5825 ± 8.0501,124.8374 ± 100.4106,0.1219 ± 0.0981,0.0167 ± 0.0176,0.1186 ± 0.0872,0.0237 ± 0.0216,0.1222 ± 0.0647,-0.1360 ± 0.0719,3.4032 ± 0.6203
3,4,18.0263 ± 13.1328,62.8738 ± 46.9549,0.0614 ± 0.0459,0.0578 ± 0.0437,0.2202 ± 0.1136,0.0951 ± 0.0602,0.2504 ± 0.0711,0.6332 ± 0.1129,2.6274 ± 0.5076
4,5,18.1799 ± 13.9080,60.8087 ± 31.9829,0.0594 ± 0.0312,0.0586 ± 0.0311,0.2460 ± 0.1170,0.0955 ± 0.0363,0.2641 ± 0.0533,0.5929 ± 0.0948,2.6838 ± 0.4790
5,6,3.2464 ± 4.1972,123.8508 ± 93.4476,0.1209 ± 0.0913,0.0231 ± 0.0216,0.2696 ± 0.1183,0.0330 ± 0.0268,0.2591 ± 0.0598,-0.0992 ± 0.0603,3.3714 ± 0.6056
6,7,2.9979 ± 4.5472,58.8256 ± 45.1631,0.0574 ± 0.0441,0.0070 ± 0.0072,0.1730 ± 0.0859,0.0122 ± 0.0123,0.1805 ± 0.0563,-0.1228 ± 0.0610,3.3721 ± 0.6210
7,8,21.8079 ± 17.8693,187.5810 ± 120.0827,0.1832 ± 0.1173,0.1647 ± 0.1080,0.3831 ± 0.1711,0.2107 ± 0.0775,0.3382 ± 0.0654,0.4689 ± 0.1161,2.8547 ± 0.5354

Saved table: figures/NMF_8/table_grad_cam_pp_label_1.csv

Layer-CAM - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,28.7311 ± 34.9587,292.6084 ± 160.5276,0.2858 ± 0.1568,0.0002 ± 0.0005,0.0022 ± 0.0024,0.0006 ± 0.0019,0.0052 ± 0.0059,-0.0372 ± 0.0243,2.3951 ± 1.5730
1,2,9.4939 ± 31.6645,55.7436 ± 116.2560,0.0544 ± 0.1135,0.0082 ± 0.0114,0.0199 ± 0.0202,0.0860 ± 0.0735,0.1381 ± 0.0813,0.4048 ± 0.2505,0.9752 ± 1.5606
2,3,18.9758 ± 20.4094,221.8549 ± 151.0223,0.2167 ± 0.1475,0.0005 ± 0.0009,0.0050 ± 0.0039,0.0022 ± 0.0070,0.0099 ± 0.0080,-0.0392 ± 0.0556,1.6966 ± 1.0126
3,4,3.6686 ± 8.7480,19.4760 ± 31.7608,0.0190 ± 0.0310,0.0046 ± 0.0062,0.0142 ± 0.0149,0.0707 ± 0.0712,0.0597 ± 0.0512,0.3744 ± 0.2675,0.7794 ± 0.9350
4,5,3.7614 ± 8.9888,18.5106 ± 26.6914,0.0181 ± 0.0261,0.0053 ± 0.0058,0.0156 ± 0.0143,0.0926 ± 0.0776,0.0556 ± 0.0417,0.4049 ± 0.2572,0.7943 ± 0.9741
5,6,11.8332 ± 12.6516,230.2249 ± 153.0145,0.2248 ± 0.1494,0.0023 ± 0.0033,0.0143 ± 0.0110,0.0088 ± 0.0137,0.0297 ± 0.0212,-0.0165 ± 0.0451,1.5257 ± 1.0050
6,7,11.1722 ± 11.9353,120.0954 ± 77.4270,0.1173 ± 0.0756,0.0003 ± 0.0007,0.0080 ± 0.0058,0.0024 ± 0.0053,0.0167 ± 0.0126,-0.0351 ± 0.0253,1.4582 ± 0.9919
7,8,4.5954 ± 11.0829,65.4862 ± 93.7318,0.0640 ± 0.0915,0.0066 ± 0.0057,0.0174 ± 0.0137,0.0886 ± 0.0715,0.0447 ± 0.0395,0.3697 ± 0.2280,0.8459 ± 1.0650

Saved table: figures/NMF_8/table_layer_cam_all.csv

Layer-CAM - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,33.4805 ± 36.3911,320.6645 ± 151.4090,0.3131 ± 0.1479,0.0002 ± 0.0006,0.0025 ± 0.0026,0.0007 ± 0.0020,0.0054 ± 0.0060,-0.0366 ± 0.0253,2.3066 ± 1.6718
1,2,0.5808 ± 1.4277,15.3472 ± 23.0145,0.0150 ± 0.0225,0.0042 ± 0.0055,0.0125 ± 0.0123,0.0833 ± 0.0790,0.1422 ± 0.0872,0.4085 ± 0.2691,0.4208 ± 0.4181
2,3,21.8820 ± 21.1070,242.9067 ± 151.9366,0.2372 ± 0.1484,0.0006 ± 0.0009,0.0051 ± 0.0041,0.0026 ± 0.0076,0.0095 ± 0.0079,-0.0375 ± 0.0598,1.4788 ± 0.9198
3,4,0.5531 ± 1.1330,10.0591 ± 15.8763,0.0098 ± 0.0155,0.0030 ± 0.0044,0.0089 ± 0.0094,0.0653 ± 0.0739,0.0473 ± 0.0464,0.3542 ± 0.2833,0.4119 ± 0.4016
4,5,0.6327 ± 1.2140,9.3324 ± 13.1398,0.0091 ± 0.0128,0.0037 ± 0.0045,0.0107 ± 0.0096,0.0897 ± 0.0838,0.0456 ± 0.0380,0.4061 ± 0.2779,0.4091 ± 0.4045
5,6,13.6965 ± 13.0960,253.3069 ± 153.6620,0.2474 ± 0.1501,0.0028 ± 0.0035,0.0135 ± 0.0114,0.0106 ± 0.0145,0.0281 ± 0.0221,-0.0117 ± 0.0477,1.2784 ± 0.8684
6,7,12.9459 ± 12.2977,133.3903 ± 76.5642,0.1303 ± 0.0748,0.0004 ± 0.0008,0.0075 ± 0.0060,0.0028 ± 0.0057,0.0145 ± 0.0119,-0.0335 ± 0.0248,1.1978 ± 0.8236
7,8,0.8605 ± 1.4086,38.9929 ± 60.2298,0.0381 ± 0.0588,0.0057 ± 0.0054,0.0131 ± 0.0103,0.0975 ± 0.0755,0.0400 ± 0.0411,0.3995 ± 0.2366,0.4252 ± 0.4354

Saved table: figures/NMF_8/table_layer_cam_label_0.csv

Layer-CAM - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,6.8435 ± 12.9714,163.3113 ± 136.1665,0.1595 ± 0.1330,0.0000 ± 0.0001,0.0010 ± 0.0014,0.0001 ± 0.0008,0.0039 ± 0.0053,-0.0401 ± 0.0190,2.8030 ± 0.8911
1,2,50.5701 ± 59.6825,241.9114 ± 176.6126,0.2362 ± 0.1725,0.0265 ± 0.0137,0.0543 ± 0.0126,0.0977 ± 0.0395,0.1196 ± 0.0406,0.3889 ± 0.1478,3.5306 ± 2.2155
2,3,5.5825 ± 8.0501,124.8374 ± 100.4106,0.1219 ± 0.0981,0.0001 ± 0.0002,0.0045 ± 0.0032,0.0003 ± 0.0014,0.0116 ± 0.0082,-0.0469 ± 0.0300,2.7004 ± 0.7905
3,4,18.0263 ± 13.1328,62.8738 ± 46.9549,0.0614 ± 0.0459,0.0120 ± 0.0076,0.0387 ± 0.0108,0.0944 ± 0.0516,0.1165 ± 0.0290,0.4623 ± 0.1548,2.4734 ± 0.8172
4,5,18.1799 ± 13.9080,60.8087 ± 31.9829,0.0594 ± 0.0312,0.0127 ± 0.0054,0.0385 ± 0.0088,0.1054 ± 0.0381,0.1017 ± 0.0227,0.3997 ± 0.1324,2.5692 ± 0.8561
5,6,3.2464 ± 4.1972,123.8508 ± 93.4476,0.1209 ± 0.0913,0.0002 ± 0.0005,0.0182 ± 0.0076,0.0008 ± 0.0022,0.0373 ± 0.0145,-0.0378 ± 0.0203,2.6658 ± 0.7798
6,7,2.9979 ± 4.5472,58.8256 ± 45.1631,0.0574 ± 0.0441,0.0000 ± 0.0002,0.0107 ± 0.0041,0.0003 ± 0.0016,0.0267 ± 0.0106,-0.0421 ± 0.0259,2.6583 ± 0.7993
7,8,21.8079 ± 17.8693,187.5810 ± 120.0827,0.1832 ± 0.1173,0.0109 ± 0.0051,0.0371 ± 0.0089,0.0496 ± 0.0257,0.0663 ± 0.0196,0.2397 ± 0.1165,2.7848 ± 0.9551

Saved table: figures/NMF_8/table_layer_cam_label_1.csv

============================================================
CAM-Cluster Comparison (Label 0 vs Label 1) - NMF (8 clusters)
============================================================

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0010 ± 0.0026,-0.0625 ± 0.0359,2.1661 ± 1.7304,0.0015 ± 0.0024,-0.1168 ± 0.0509,0.6600 ± 0.8653
1,2,0.1260 ± 0.1088,0.5130 ± 0.3191,0.0951 ± 0.1755,0.2771 ± 0.0876,0.8215 ± 0.1237,3.1076 ± 2.6306
2,3,0.0093 ± 0.0165,-0.0741 ± 0.0452,1.3030 ± 0.9520,0.0110 ± 0.0140,-0.1404 ± 0.0699,0.4778 ± 0.4767
3,4,0.0916 ± 0.1047,0.3866 ± 0.3341,0.1167 ± 0.2034,0.1012 ± 0.0650,0.6325 ± 0.1431,1.9013 ± 1.0300
4,5,0.0910 ± 0.0842,0.4604 ± 0.3031,0.1387 ± 0.2263,0.1023 ± 0.0395,0.5498 ± 0.1192,1.8283 ± 0.9281
5,6,0.0090 ± 0.0122,-0.0495 ± 0.0353,1.1054 ± 0.8680,0.0091 ± 0.0078,-0.1091 ± 0.0622,0.3539 ± 0.3627
6,7,0.0110 ± 0.0152,-0.0617 ± 0.0363,0.9913 ± 0.8383,0.0069 ± 0.0082,-0.1283 ± 0.0601,0.3064 ± 0.3879
7,8,0.2194 ± 0.1218,0.5116 ± 0.2683,0.1444 ± 0.1952,0.2203 ± 0.0804,0.4680 ± 0.1294,1.7093 ± 0.9273

Saved table: figures/NMF_8/table_grad_cam_cluster_comparison.csv

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0045 ± 0.0069,-0.0631 ± 0.0413,2.3680 ± 1.6653,0.0061 ± 0.0078,-0.1144 ± 0.0517,3.4908 ± 0.7249
1,2,0.0871 ± 0.0851,0.5314 ± 0.3106,0.4873 ± 0.5242,0.2642 ± 0.0892,0.7620 ± 0.1145,2.7893 ± 1.5847
2,3,0.0211 ± 0.0273,-0.0687 ± 0.0739,1.5515 ± 0.9435,0.0237 ± 0.0216,-0.1360 ± 0.0719,3.4032 ± 0.6203
3,4,0.0646 ± 0.0809,0.4155 ± 0.3249,0.4851 ± 0.5237,0.0951 ± 0.0602,0.6332 ± 0.1129,2.6274 ± 0.5076
4,5,0.0628 ± 0.0648,0.4729 ± 0.3026,0.4783 ± 0.5284,0.0955 ± 0.0363,0.5929 ± 0.0948,2.6838 ± 0.4790
5,6,0.0492 ± 0.0474,-0.0218 ± 0.0676,1.3409 ± 0.9093,0.0330 ± 0.0268,-0.0992 ± 0.0603,3.3714 ± 0.6056
6,7,0.0202 ± 0.0217,-0.0581 ± 0.0405,1.2780 ± 0.8616,0.0122 ± 0.0123,-0.1228 ± 0.0610,3.3721 ± 0.6210
7,8,0.1647 ± 0.1108,0.5261 ± 0.2691,0.4845 ± 0.5527,0.2107 ± 0.0775,0.4689 ± 0.1161,2.8547 ± 0.5354

Saved table: figures/NMF_8/table_grad_cam_pp_cluster_comparison.csv

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0007 ± 0.0020,-0.0366 ± 0.0253,2.3066 ± 1.6718,0.0001 ± 0.0008,-0.0401 ± 0.0190,2.8030 ± 0.8911
1,2,0.0833 ± 0.0790,0.4085 ± 0.2691,0.4208 ± 0.4181,0.0977 ± 0.0395,0.3889 ± 0.1478,3.5306 ± 2.2155
2,3,0.0026 ± 0.0076,-0.0375 ± 0.0598,1.4788 ± 0.9198,0.0003 ± 0.0014,-0.0469 ± 0.0300,2.7004 ± 0.7905
3,4,0.0653 ± 0.0739,0.3542 ± 0.2833,0.4119 ± 0.4016,0.0944 ± 0.0516,0.4623 ± 0.1548,2.4734 ± 0.8172
4,5,0.0897 ± 0.0838,0.4061 ± 0.2779,0.4091 ± 0.4045,0.1054 ± 0.0381,0.3997 ± 0.1324,2.5692 ± 0.8561
5,6,0.0106 ± 0.0145,-0.0117 ± 0.0477,1.2784 ± 0.8684,0.0008 ± 0.0022,-0.0378 ± 0.0203,2.6658 ± 0.7798
6,7,0.0028 ± 0.0057,-0.0335 ± 0.0248,1.1978 ± 0.8236,0.0003 ± 0.0016,-0.0421 ± 0.0259,2.6583 ± 0.7993
7,8,0.0975 ± 0.0755,0.3995 ± 0.2366,0.4252 ± 0.4354,0.0496 ± 0.0257,0.2397 ± 0.1165,2.7848 ± 0.9551

Saved table: figures/NMF_8/table_layer_cam_cluster_comparison.csv

============================================================
CAM IoU (All Data) and Correlation (Label 0, Label 1) - NMF (8 clusters)
============================================================

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.0011 ± 0.0026      -0.0625 ± 0.0359      -0.1168 ± 0.0509
1        2  0.1559 ± 0.1210       0.5130 ± 0.3191       0.8215 ± 0.1237
2        3  0.0096 ± 0.0161      -0.0741 ± 0.0452      -0.1404 ± 0.0699
3        4  0.0935 ± 0.0982       0.3866 ± 0.3341       0.6325 ± 0.1431
4        5  0.0932 ± 0.0775       0.4604 ± 0.3031       0.5498 ± 0.1192
5        6  0.0090 ± 0.0115      -0.0495 ± 0.0353      -0.1091 ± 0.0622
6        7  0.0103 ± 0.0143      -0.0617 ± 0.0363      -0.1283 ± 0.0601
7        8  0.2196 ± 0.1149       0.5116 ± 0.2683       0.4680 ± 0.1294

Saved table: figures/NMF_8/table_grad_cam_iou_correlation.csv

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.0048 ± 0.0071      -0.0631 ± 0.0413      -0.1144 ± 0.0517
1        2  0.1201 ± 0.1101       0.5314 ± 0.3106       0.7620 ± 0.1145
2        3  0.0215 ± 0.0264      -0.0687 ± 0.0739      -0.1360 ± 0.0719
3        4  0.0702 ± 0.0784       0.4155 ± 0.3249       0.6332 ± 0.1129
4        5  0.0689 ± 0.0618       0.4729 ± 0.3026       0.5929 ± 0.0948
5        6  0.0463 ± 0.0449      -0.0218 ± 0.0676      -0.0992 ± 0.0603
6        7  0.0188 ± 0.0206      -0.0581 ± 0.0405      -0.1228 ± 0.0610
7        8  0.1732 ± 0.1069       0.5261 ± 0.2691       0.4689 ± 0.1161

Saved table: figures/NMF_8/table_grad_cam_pp_iou_correlation.csv

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.0006 ± 0.0019      -0.0366 ± 0.0253      -0.0401 ± 0.0190
1        2  0.0860 ± 0.0735       0.4085 ± 0.2691       0.3889 ± 0.1478
2        3  0.0022 ± 0.0070      -0.0375 ± 0.0598      -0.0469 ± 0.0300
3        4  0.0707 ± 0.0712       0.3542 ± 0.2833       0.4623 ± 0.1548
4        5  0.0926 ± 0.0776       0.4061 ± 0.2779       0.3997 ± 0.1324
5        6  0.0088 ± 0.0137      -0.0117 ± 0.0477      -0.0378 ± 0.0203
6        7  0.0024 ± 0.0053      -0.0335 ± 0.0248      -0.0421 ± 0.0259
7        8  0.0886 ± 0.0715       0.3995 ± 0.2366       0.2397 ± 0.1165

Saved table: figures/NMF_8/table_layer_cam_iou_correlation.csv

============================================================
Normalized Cluster Count Comparison - NMF (8 clusters)
============================================================

   Cluster         All Data          Label 0          Label 1
0        1  0.2858 ± 0.1568  0.3131 ± 0.1479  0.1595 ± 0.1330
1        2  0.0544 ± 0.1135  0.0150 ± 0.0225  0.2362 ± 0.1725
2        3  0.2167 ± 0.1475  0.2372 ± 0.1484  0.1219 ± 0.0981
3        4  0.0190 ± 0.0310  0.0098 ± 0.0155  0.0614 ± 0.0459
4        5  0.0181 ± 0.0261  0.0091 ± 0.0128  0.0594 ± 0.0312
5        6  0.2248 ± 0.1494  0.2474 ± 0.1501  0.1209 ± 0.0913
6        7  0.1173 ± 0.0756  0.1303 ± 0.0748  0.0574 ± 0.0441
7        8  0.0640 ± 0.0915  0.0381 ± 0.0588  0.1832 ± 0.1173

Saved table: figures/NMF_8/table_norm_count_comparison.csv

============================================================
Annotation Mask Statistics - NMF (8 clusters)
============================================================


Carcinoma Mask Metrics - All Data (n=1841):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.4200 ± 0.2724,0.5311 ± 0.2455,N/A,NaN
1,Grad-CAM++,0.4471 ± 0.2806,0.5584 ± 0.2502,N/A,NaN
2,Layer-CAM,0.0516 ± 0.0212,0.0920 ± 0.0526,N/A,NaN
3,Cluster 1,0.0467 ± 0.0475,0.0534 ± 0.0468,0.1243 ± 0.0872,0.1216 ± 0.1138
4,Cluster 2,0.1984 ± 0.1790,0.1940 ± 0.1079,0.3069 ± 0.1188,0.3739 ± 0.2573
5,Cluster 3,0.0793 ± 0.0879,0.0907 ± 0.0745,0.1798 ± 0.1044,0.2039 ± 0.1669
6,Cluster 4,0.0434 ± 0.0418,0.0584 ± 0.0453,0.2014 ± 0.0807,0.2035 ± 0.1301
7,Cluster 5,0.0475 ± 0.0351,0.0641 ± 0.0350,0.2140 ± 0.0832,0.2299 ± 0.1429
8,Cluster 6,0.0465 ± 0.0610,0.0536 ± 0.0555,0.2229 ± 0.0943,0.2647 ± 0.1637
9,Cluster 7,0.0314 ± 0.0342,0.0411 ± 0.0381,0.2113 ± 0.0917,0.2350 ± 0.1500
10,Cluster 8,0.1399 ± 0.1118,0.1535 ± 0.0775,0.3096 ± 0.1090,0.3944 ± 0.2278

Saved table: figures/NMF_8/table_carcinoma_all.csv

Carcinoma Mask Metrics - Predicted Label 0 (n=245):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.0800 ± 0.0938,0.1946 ± 0.1593,N/A,NaN
1,Grad-CAM++,0.0967 ± 0.1128,0.2150 ± 0.1688,N/A,NaN
2,Layer-CAM,0.0199 ± 0.0174,0.0903 ± 0.0879,N/A,NaN
3,Cluster 1,0.0398 ± 0.0563,0.0559 ± 0.0590,0.1163 ± 0.1054,0.0974 ± 0.1280
4,Cluster 2,0.0241 ± 0.0387,0.0642 ± 0.0722,0.1316 ± 0.1001,0.0651 ± 0.0827
5,Cluster 3,0.0689 ± 0.1122,0.1001 ± 0.0921,0.1389 ± 0.1275,0.1433 ± 0.1944
6,Cluster 4,0.0103 ± 0.0197,0.0274 ± 0.0406,0.0968 ± 0.0741,0.0567 ± 0.0738
7,Cluster 5,0.0102 ± 0.0133,0.0336 ± 0.0347,0.1015 ± 0.0805,0.0662 ± 0.0805
8,Cluster 6,0.0357 ± 0.0714,0.0495 ± 0.0691,0.1136 ± 0.1022,0.1042 ± 0.1350
9,Cluster 7,0.0259 ± 0.0372,0.0476 ± 0.0501,0.1445 ± 0.1229,0.1381 ± 0.1614
10,Cluster 8,0.0416 ± 0.0650,0.0918 ± 0.0787,0.1665 ± 0.1240,0.1433 ± 0.1679

Saved table: figures/NMF_8/table_carcinoma_label_0.csv

Carcinoma Mask Metrics - Predicted Label 1 (n=1596):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.4723 ± 0.2525,0.5828 ± 0.2135,N/A,NaN
1,Grad-CAM++,0.5009 ± 0.2592,0.6111 ± 0.2168,N/A,NaN
2,Layer-CAM,0.0565 ± 0.0171,0.0923 ± 0.0449,N/A,NaN
3,Cluster 1,0.0478 ± 0.0459,0.0530 ± 0.0447,0.1255 ± 0.0840,0.1253 ± 0.1111
4,Cluster 2,0.2251 ± 0.1770,0.2140 ± 0.0983,0.3338 ± 0.0965,0.4213 ± 0.2418
5,Cluster 3,0.0809 ± 0.0835,0.0893 ± 0.0713,0.1861 ± 0.0989,0.2132 ± 0.1604
6,Cluster 4,0.0485 ± 0.0420,0.0631 ± 0.0441,0.2174 ± 0.0688,0.2261 ± 0.1220
7,Cluster 5,0.0532 ± 0.0339,0.0688 ± 0.0326,0.2313 ± 0.0690,0.2550 ± 0.1334
8,Cluster 6,0.0481 ± 0.0591,0.0542 ± 0.0531,0.2396 ± 0.0809,0.2893 ± 0.1535
9,Cluster 7,0.0322 ± 0.0337,0.0400 ± 0.0359,0.2216 ± 0.0812,0.2498 ± 0.1425
10,Cluster 8,0.1549 ± 0.1098,0.1629 ± 0.0728,0.3315 ± 0.0879,0.4329 ± 0.2107

Saved table: figures/NMF_8/table_carcinoma_label_1.csv

============================================================
Carcinoma IoU Comparison - NMF (8 clusters)
============================================================

   Method/Cluster         All Data          Label 0          Label 1
0        Grad-CAM  0.5311 ± 0.2455  0.1946 ± 0.1593  0.5828 ± 0.2135
1      Grad-CAM++  0.5584 ± 0.2502  0.2150 ± 0.1688  0.6111 ± 0.2168
2       Layer-CAM  0.0920 ± 0.0526  0.0903 ± 0.0879  0.0923 ± 0.0449
3       Cluster 1  0.0534 ± 0.0468  0.0559 ± 0.0590  0.0530 ± 0.0447
4       Cluster 2  0.1940 ± 0.1079  0.0642 ± 0.0722  0.2140 ± 0.0983
5       Cluster 3  0.0907 ± 0.0745  0.1001 ± 0.0921  0.0893 ± 0.0713
6       Cluster 4  0.0584 ± 0.0453  0.0274 ± 0.0406  0.0631 ± 0.0441
7       Cluster 5  0.0641 ± 0.0350  0.0336 ± 0.0347  0.0688 ± 0.0326
8       Cluster 6  0.0536 ± 0.0555  0.0495 ± 0.0691  0.0542 ± 0.0531
9       Cluster 7  0.0411 ± 0.0381  0.0476 ± 0.0501  0.0400 ± 0.0359
10      Cluster 8  0.1535 ± 0.0775  0.0918 ± 0.0787  0.1629 ± 0.0728

Saved table: figures/NMF_8/table_carcinoma_iou_comparison.csv

================================================================================


================================================================================
Processing: KMeans with 4 clusters
================================================================================

Label distribution:

label
0.0    8369
1.0    1631
Name: count, dtype: int64

Saved figure: figures/KMeans_4/hist_predicted_prob.png

Prediction Metrics - KMeans with 4 clusters:
============================================================
Number of samples: 10000

label             0.0   1.0
predicted_label
0                8093   124
1                 276  1507

Accuracy: 0.96
Precision: 0.8452047111609646
Recall: 0.923973022685469
F1 Score: 0.8828353837141183
AUC Score: 0.9844677288867657

Fitting linear regression model - KMeans (4 clusters):
============================================================
Coefficients: [ 0.00122274  0.00246785 -0.00740741  0.00013526]
Intercept: 62.96448904745039
R-squared: 0.6618350664058174

Fitting linear regression model (using cluster counts) - KMeans (4 clusters):
============================================================
Coefficients: [-0.00893208 -0.01879612  0.05087241 -0.0231442 ]
Intercept: 7.511850558710517
R-squared: 0.6057215510015734
Saved figure: figures/KMeans_4/weight_sum_by_label.png
Saved figure: figures/KMeans_4/weight_sum_all_data.png
Saved figure: figures/KMeans_4/cluster_count_by_label.png
Saved figure: figures/KMeans_4/cluster_count_all_data.png
Saved figure: figures/KMeans_4/iou_by_label_grad_cam.png
Saved figure: figures/KMeans_4/iou_all_data_grad_cam.png
Saved figure: figures/KMeans_4/iou_soft_by_label_grad_cam.png
Saved figure: figures/KMeans_4/iou_soft_all_data_grad_cam.png
Saved figure: figures/KMeans_4/correlation_by_label_grad_cam.png
Saved figure: figures/KMeans_4/correlation_all_data_grad_cam.png
Saved figure: figures/KMeans_4/l2_distance_by_label_grad_cam.png
Saved figure: figures/KMeans_4/l2_distance_all_data_grad_cam.png
Saved figure: figures/KMeans_4/iou_by_label_grad_cam_pp.png
Saved figure: figures/KMeans_4/iou_all_data_grad_cam_pp.png
Saved figure: figures/KMeans_4/iou_soft_by_label_grad_cam_pp.png
Saved figure: figures/KMeans_4/iou_soft_all_data_grad_cam_pp.png
Saved figure: figures/KMeans_4/correlation_by_label_grad_cam_pp.png
Saved figure: figures/KMeans_4/correlation_all_data_grad_cam_pp.png
Saved figure: figures/KMeans_4/l2_distance_by_label_grad_cam_pp.png
Saved figure: figures/KMeans_4/l2_distance_all_data_grad_cam_pp.png
Saved figure: figures/KMeans_4/iou_by_label_layer_cam.png
Saved figure: figures/KMeans_4/iou_all_data_layer_cam.png
Saved figure: figures/KMeans_4/iou_soft_by_label_layer_cam.png
Saved figure: figures/KMeans_4/iou_soft_all_data_layer_cam.png
Saved figure: figures/KMeans_4/correlation_by_label_layer_cam.png
Saved figure: figures/KMeans_4/correlation_all_data_layer_cam.png
Saved figure: figures/KMeans_4/l2_distance_by_label_layer_cam.png
Saved figure: figures/KMeans_4/l2_distance_all_data_layer_cam.png
Saved figure: figures/KMeans_4/iou_hard_carcinoma.png
Saved figure: figures/KMeans_4/iou_soft_carcinoma.png

============================================================
Statistics (Mean ± Std) - KMeans (4 clusters)
============================================================


Grad-CAM - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,3106.3086 ± 1766.7450,816.0607 ± 192.9348,0.7969 ± 0.1884,0.1270 ± 0.1632,0.1496 ± 0.2129,0.1093 ± 0.1094,0.1072 ± 0.1258,-0.1797 ± 0.2701,19.2782 ± 3.1587
1,2,5061.3836 ± 1169.6668,128.8868 ± 129.5654,0.1259 ± 0.1265,0.0000 ± 0.0001,0.1496 ± 0.2129,0.0000 ± 0.0002,0.1072 ± 0.1258,0.0796 ± 0.1612,7.4798 ± 1.5500
2,3,11180.8742 ± 731.8691,23.1511 ± 75.0330,0.0226 ± 0.0733,0.0226 ± 0.0733,0.1496 ± 0.2129,0.0347 ± 0.0777,0.1072 ± 0.1258,0.2997 ± 0.3302,3.4163 ± 1.1167
3,4,9256.1274 ± 1022.6466,55.9014 ± 85.0318,0.0546 ± 0.0830,0.0000 ± 0.0000,0.1496 ± 0.2129,0.0000 ± 0.0000,0.1072 ± 0.1258,0.1650 ± 0.2714,4.5282 ± 1.4756

Saved table: figures/KMeans_4/table_grad_cam_all.csv

Grad-CAM - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,2883.3841 ± 1564.4252,808.9197 ± 201.7051,0.7900 ± 0.1970,0.0674 ± 0.0821,0.0679 ± 0.0827,0.0710 ± 0.0701,0.0588 ± 0.0628,-0.0677 ± 0.1522,19.4317 ± 3.1944
1,2,4762.8509 ± 659.3864,148.7223 ± 131.9938,0.1452 ± 0.1289,0.0000 ± 0.0000,0.0679 ± 0.0827,0.0000 ± 0.0002,0.0588 ± 0.0628,0.0351 ± 0.1199,7.5979 ± 1.6279
2,3,11299.7245 ± 716.9805,0.4870 ± 2.8087,0.0005 ± 0.0027,0.0005 ± 0.0027,0.0679 ± 0.0827,0.0038 ± 0.0174,0.0588 ± 0.0628,0.1678 ± 0.2177,3.0893 ± 0.6370
3,4,8947.8356 ± 537.7251,65.8710 ± 89.8764,0.0643 ± 0.0878,0.0000 ± 0.0000,0.0679 ± 0.0827,0.0000 ± 0.0000,0.0588 ± 0.0628,0.0533 ± 0.1476,4.5847 ± 1.5711

Saved table: figures/KMeans_4/table_grad_cam_label_0.csv

Grad-CAM - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,4133.6619 ± 2223.7976,848.9703 ± 141.3091,0.8291 ± 0.1380,0.4015 ± 0.1634,0.5261 ± 0.2242,0.2857 ± 0.0809,0.3303 ± 0.0998,-0.6318 ± 0.1377,18.5707 ± 2.8859
1,2,6437.1789 ± 1835.0007,37.4745 ± 60.7708,0.0366 ± 0.0593,0.0000 ± 0.0001,0.5261 ± 0.2242,0.0000 ± 0.0003,0.3303 ± 0.0998,0.2589 ± 0.1809,6.9352 ± 0.9487
2,3,10633.1499 ± 519.6969,127.5990 ± 135.1662,0.1246 ± 0.1320,0.1246 ± 0.1320,0.5261 ± 0.2242,0.1594 ± 0.0989,0.3303 ± 0.0998,0.8321 ± 0.0642,4.9235 ± 1.5363
3,4,10676.8977 ± 1441.1880,9.9563 ± 27.5165,0.0097 ± 0.0269,0.0000 ± 0.0000,0.5261 ± 0.2242,0.0000 ± 0.0000,0.3303 ± 0.0998,0.6158 ± 0.1714,4.2680 ± 0.8687

Saved table: figures/KMeans_4/table_grad_cam_label_1.csv

Grad-CAM++ - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,3106.3086 ± 1766.7450,816.0607 ± 192.9348,0.7969 ± 0.1884,0.1579 ± 0.1758,0.1810 ± 0.2229,0.1355 ± 0.1158,0.1292 ± 0.1295,-0.1688 ± 0.2570,19.1297 ± 3.2285
1,2,5061.3836 ± 1169.6668,128.8868 ± 129.5654,0.1259 ± 0.1265,0.0005 ± 0.0017,0.1810 ± 0.2229,0.0015 ± 0.0046,0.1292 ± 0.1295,0.0792 ± 0.1550,7.2415 ± 1.6607
2,3,11180.8742 ± 731.8691,23.1511 ± 75.0330,0.0226 ± 0.0733,0.0226 ± 0.0733,0.1810 ± 0.2229,0.0303 ± 0.0724,0.1292 ± 0.1295,0.2831 ± 0.3135,3.0540 ± 0.7344
3,4,9256.1274 ± 1022.6466,55.9014 ± 85.0318,0.0546 ± 0.0830,0.0000 ± 0.0003,0.1810 ± 0.2229,0.0001 ± 0.0011,0.1292 ± 0.1295,0.1548 ± 0.2596,4.3192 ± 1.5485

Saved table: figures/KMeans_4/table_grad_cam_pp_all.csv

Grad-CAM++ - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,2883.3841 ± 1564.4252,808.9197 ± 201.7051,0.7900 ± 0.1970,0.0968 ± 0.1027,0.0978 ± 0.1036,0.0987 ± 0.0857,0.0819 ± 0.0766,-0.0671 ± 0.1469,19.3648 ± 3.2003
1,2,4762.8509 ± 659.3864,148.7223 ± 131.9938,0.1452 ± 0.1289,0.0004 ± 0.0015,0.0978 ± 0.1036,0.0015 ± 0.0047,0.0819 ± 0.0766,0.0372 ± 0.1155,7.5168 ± 1.6491
2,3,11299.7245 ± 716.9805,0.4870 ± 2.8087,0.0005 ± 0.0027,0.0005 ± 0.0027,0.0978 ± 0.1036,0.0027 ± 0.0132,0.0819 ± 0.0766,0.1644 ± 0.2096,3.0012 ± 0.6366
3,4,8947.8356 ± 537.7251,65.8710 ± 89.8764,0.0643 ± 0.0878,0.0000 ± 0.0003,0.0978 ± 0.1036,0.0001 ± 0.0012,0.0819 ± 0.0766,0.0522 ± 0.1410,4.5291 ± 1.5915

Saved table: figures/KMeans_4/table_grad_cam_pp_label_0.csv

Grad-CAM++ - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,4133.6619 ± 2223.7976,848.9703 ± 141.3091,0.8291 ± 0.1380,0.4391 ± 0.1685,0.5646 ± 0.2241,0.3049 ± 0.0797,0.3473 ± 0.0959,-0.6134 ± 0.1325,18.0461 ± 3.1361
1,2,6437.1789 ± 1835.0007,37.4745 ± 60.7708,0.0366 ± 0.0593,0.0009 ± 0.0021,0.5646 ± 0.2241,0.0015 ± 0.0037,0.3473 ± 0.0959,0.2630 ± 0.1709,5.9727 ± 0.9880
2,3,10633.1499 ± 519.6969,127.5990 ± 135.1662,0.1246 ± 0.1320,0.1246 ± 0.1320,0.5646 ± 0.2241,0.1508 ± 0.0975,0.3473 ± 0.0959,0.8019 ± 0.0711,3.2972 ± 1.0422
3,4,10676.8977 ± 1441.1880,9.9563 ± 27.5165,0.0097 ± 0.0269,0.0000 ± 0.0002,0.5646 ± 0.2241,0.0000 ± 0.0004,0.3473 ± 0.0959,0.6028 ± 0.1682,3.3516 ± 0.7978

Saved table: figures/KMeans_4/table_grad_cam_pp_label_1.csv

Layer-CAM - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,3106.3086 ± 1766.7450,816.0607 ± 192.9348,0.7969 ± 0.1884,0.0214 ± 0.0156,0.0280 ± 0.0222,0.0261 ± 0.0188,0.0268 ± 0.0208,-0.0925 ± 0.1143,19.2608 ± 3.1569
1,2,5061.3836 ± 1169.6668,128.8868 ± 129.5654,0.1259 ± 0.1265,0.0001 ± 0.0003,0.0280 ± 0.0222,0.0003 ± 0.0023,0.0268 ± 0.0208,0.0423 ± 0.0699,7.4643 ± 1.5548
2,3,11180.8742 ± 731.8691,23.1511 ± 75.0330,0.0226 ± 0.0733,0.0065 ± 0.0149,0.0280 ± 0.0222,0.0451 ± 0.0871,0.0268 ± 0.0208,0.1698 ± 0.1608,3.3812 ± 1.1184
3,4,9256.1274 ± 1022.6466,55.9014 ± 85.0318,0.0546 ± 0.0830,0.0000 ± 0.0001,0.0280 ± 0.0222,0.0000 ± 0.0008,0.0268 ± 0.0208,0.0874 ± 0.1226,4.5445 ± 1.4867

Saved table: figures/KMeans_4/table_layer_cam_all.csv

Layer-CAM - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,2883.3841 ± 1564.4252,808.9197 ± 201.7051,0.7900 ± 0.1970,0.0200 ± 0.0158,0.0205 ± 0.0162,0.0251 ± 0.0198,0.0198 ± 0.0155,-0.0565 ± 0.0889,19.4086 ± 3.1970
1,2,4762.8509 ± 659.3864,148.7223 ± 131.9938,0.1452 ± 0.1289,0.0001 ± 0.0003,0.0205 ± 0.0162,0.0004 ± 0.0025,0.0198 ± 0.0155,0.0312 ± 0.0647,7.5685 ± 1.6341
2,3,11299.7245 ± 716.9805,0.4870 ± 2.8087,0.0005 ± 0.0027,0.0004 ± 0.0020,0.0205 ± 0.0162,0.0088 ± 0.0352,0.0198 ± 0.0155,0.1300 ± 0.1416,3.0586 ± 0.6356
3,4,8947.8356 ± 537.7251,65.8710 ± 89.8764,0.0643 ± 0.0878,0.0000 ± 0.0001,0.0205 ± 0.0162,0.0001 ± 0.0009,0.0198 ± 0.0155,0.0455 ± 0.0872,4.5688 ± 1.5771

Saved table: figures/KMeans_4/table_layer_cam_label_0.csv

Layer-CAM - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,4133.6619 ± 2223.7976,848.9703 ± 141.3091,0.8291 ± 0.1380,0.0280 ± 0.0125,0.0624 ± 0.0108,0.0308 ± 0.0121,0.0586 ± 0.0096,-0.2499 ± 0.0723,18.5799 ± 2.8695
1,2,6437.1789 ± 1835.0007,37.4745 ± 60.7708,0.0366 ± 0.0593,0.0000 ± 0.0001,0.0624 ± 0.0108,0.0000 ± 0.0006,0.0586 ± 0.0096,0.0911 ± 0.0709,6.9840 ± 0.9864
2,3,10633.1499 ± 519.6969,127.5990 ± 135.1662,0.1246 ± 0.1320,0.0344 ± 0.0169,0.0624 ± 0.0108,0.2036 ± 0.0669,0.0586 ± 0.0096,0.3436 ± 0.1187,4.8681 ± 1.5699
3,4,10676.8977 ± 1441.1880,9.9563 ± 27.5165,0.0097 ± 0.0269,0.0000 ± 0.0000,0.0624 ± 0.0108,0.0000 ± 0.0003,0.0586 ± 0.0096,0.2703 ± 0.0796,4.4323 ± 0.9592

Saved table: figures/KMeans_4/table_layer_cam_label_1.csv

============================================================
CAM-Cluster Comparison (Label 0 vs Label 1) - KMeans (4 clusters)
============================================================

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0710 ± 0.0701,-0.0677 ± 0.1522,19.4317 ± 3.1944,0.2857 ± 0.0809,-0.6318 ± 0.1377,18.5707 ± 2.8859
1,2,0.0000 ± 0.0002,0.0351 ± 0.1199,7.5979 ± 1.6279,0.0000 ± 0.0003,0.2589 ± 0.1809,6.9352 ± 0.9487
2,3,0.0038 ± 0.0174,0.1678 ± 0.2177,3.0893 ± 0.6370,0.1594 ± 0.0989,0.8321 ± 0.0642,4.9235 ± 1.5363
3,4,0.0000 ± 0.0000,0.0533 ± 0.1476,4.5847 ± 1.5711,0.0000 ± 0.0000,0.6158 ± 0.1714,4.2680 ± 0.8687

Saved table: figures/KMeans_4/table_grad_cam_cluster_comparison.csv

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0987 ± 0.0857,-0.0671 ± 0.1469,19.3648 ± 3.2003,0.3049 ± 0.0797,-0.6134 ± 0.1325,18.0461 ± 3.1361
1,2,0.0015 ± 0.0047,0.0372 ± 0.1155,7.5168 ± 1.6491,0.0015 ± 0.0037,0.2630 ± 0.1709,5.9727 ± 0.9880
2,3,0.0027 ± 0.0132,0.1644 ± 0.2096,3.0012 ± 0.6366,0.1508 ± 0.0975,0.8019 ± 0.0711,3.2972 ± 1.0422
3,4,0.0001 ± 0.0012,0.0522 ± 0.1410,4.5291 ± 1.5915,0.0000 ± 0.0004,0.6028 ± 0.1682,3.3516 ± 0.7978

Saved table: figures/KMeans_4/table_grad_cam_pp_cluster_comparison.csv

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0251 ± 0.0198,-0.0565 ± 0.0889,19.4086 ± 3.1970,0.0308 ± 0.0121,-0.2499 ± 0.0723,18.5799 ± 2.8695
1,2,0.0004 ± 0.0025,0.0312 ± 0.0647,7.5685 ± 1.6341,0.0000 ± 0.0006,0.0911 ± 0.0709,6.9840 ± 0.9864
2,3,0.0088 ± 0.0352,0.1300 ± 0.1416,3.0586 ± 0.6356,0.2036 ± 0.0669,0.3436 ± 0.1187,4.8681 ± 1.5699
3,4,0.0001 ± 0.0009,0.0455 ± 0.0872,4.5688 ± 1.5771,0.0000 ± 0.0003,0.2703 ± 0.0796,4.4323 ± 0.9592

Saved table: figures/KMeans_4/table_layer_cam_cluster_comparison.csv

============================================================
CAM IoU (All Data) and Correlation (Label 0, Label 1) - KMeans (4 clusters)
============================================================

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.1093 ± 0.1094      -0.0677 ± 0.1522      -0.6318 ± 0.1377
1        2  0.0000 ± 0.0002       0.0351 ± 0.1199       0.2589 ± 0.1809
2        3  0.0347 ± 0.0777       0.1678 ± 0.2177       0.8321 ± 0.0642
3        4  0.0000 ± 0.0000       0.0533 ± 0.1476       0.6158 ± 0.1714

Saved table: figures/KMeans_4/table_grad_cam_iou_correlation.csv

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.1355 ± 0.1158      -0.0671 ± 0.1469      -0.6134 ± 0.1325
1        2  0.0015 ± 0.0046       0.0372 ± 0.1155       0.2630 ± 0.1709
2        3  0.0303 ± 0.0724       0.1644 ± 0.2096       0.8019 ± 0.0711
3        4  0.0001 ± 0.0011       0.0522 ± 0.1410       0.6028 ± 0.1682

Saved table: figures/KMeans_4/table_grad_cam_pp_iou_correlation.csv

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.0261 ± 0.0188      -0.0565 ± 0.0889      -0.2499 ± 0.0723
1        2  0.0003 ± 0.0023       0.0312 ± 0.0647       0.0911 ± 0.0709
2        3  0.0451 ± 0.0871       0.1300 ± 0.1416       0.3436 ± 0.1187
3        4  0.0000 ± 0.0008       0.0455 ± 0.0872       0.2703 ± 0.0796

Saved table: figures/KMeans_4/table_layer_cam_iou_correlation.csv

============================================================
Normalized Cluster Count Comparison - KMeans (4 clusters)
============================================================

   Cluster         All Data          Label 0          Label 1
0        1  0.7969 ± 0.1884  0.7900 ± 0.1970  0.8291 ± 0.1380
1        2  0.1259 ± 0.1265  0.1452 ± 0.1289  0.0366 ± 0.0593
2        3  0.0226 ± 0.0733  0.0005 ± 0.0027  0.1246 ± 0.1320
3        4  0.0546 ± 0.0830  0.0643 ± 0.0878  0.0097 ± 0.0269

Saved table: figures/KMeans_4/table_norm_count_comparison.csv

============================================================
Annotation Mask Statistics - KMeans (4 clusters)
============================================================


Carcinoma Mask Metrics - All Data (n=1841):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.4200 ± 0.2724,0.5311 ± 0.2455,N/A,NaN
1,Grad-CAM++,0.4471 ± 0.2806,0.5584 ± 0.2502,N/A,NaN
2,Layer-CAM,0.0516 ± 0.0212,0.0920 ± 0.0526,N/A,NaN
3,Cluster 1,0.4932 ± 0.2745,0.3103 ± 0.1343,0.3583 ± 0.1482,0.6330 ± 0.3287
4,Cluster 2,0.0239 ± 0.0408,0.0328 ± 0.0492,0.3583 ± 0.1482,0.6330 ± 0.3287
5,Cluster 3,0.1106 ± 0.1315,0.1183 ± 0.0993,0.3583 ± 0.1482,0.6330 ± 0.3287
6,Cluster 4,0.0053 ± 0.0155,0.0086 ± 0.0237,0.3583 ± 0.1482,0.6330 ± 0.3287

Saved table: figures/KMeans_4/table_carcinoma_all.csv

Carcinoma Mask Metrics - Predicted Label 0 (n=245):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.0800 ± 0.0938,0.1946 ± 0.1593,N/A,NaN
1,Grad-CAM++,0.0967 ± 0.1128,0.2150 ± 0.1688,N/A,NaN
2,Layer-CAM,0.0199 ± 0.0174,0.0903 ± 0.0879,N/A,NaN
3,Cluster 1,0.2186 ± 0.2562,0.1590 ± 0.1467,0.1697 ± 0.1552,0.2566 ± 0.2855
4,Cluster 2,0.0272 ± 0.0502,0.0520 ± 0.0665,0.1697 ± 0.1552,0.2566 ± 0.2855
5,Cluster 3,0.0038 ± 0.0106,0.0153 ± 0.0374,0.1697 ± 0.1552,0.2566 ± 0.2855
6,Cluster 4,0.0070 ± 0.0181,0.0159 ± 0.0372,0.1697 ± 0.1552,0.2566 ± 0.2855

Saved table: figures/KMeans_4/table_carcinoma_label_0.csv

Carcinoma Mask Metrics - Predicted Label 1 (n=1596):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.4723 ± 0.2525,0.5828 ± 0.2135,N/A,NaN
1,Grad-CAM++,0.5009 ± 0.2592,0.6111 ± 0.2168,N/A,NaN
2,Layer-CAM,0.0565 ± 0.0171,0.0923 ± 0.0449,N/A,NaN
3,Cluster 1,0.5354 ± 0.2520,0.3335 ± 0.1161,0.3873 ± 0.1240,0.6908 ± 0.2950
4,Cluster 2,0.0233 ± 0.0391,0.0298 ± 0.0453,0.3873 ± 0.1240,0.6908 ± 0.2950
5,Cluster 3,0.1270 ± 0.1338,0.1341 ± 0.0963,0.3873 ± 0.1240,0.6908 ± 0.2950
6,Cluster 4,0.0050 ± 0.0150,0.0074 ± 0.0207,0.3873 ± 0.1240,0.6908 ± 0.2950

Saved table: figures/KMeans_4/table_carcinoma_label_1.csv

============================================================
Carcinoma IoU Comparison - KMeans (4 clusters)
============================================================

  Method/Cluster         All Data          Label 0          Label 1
0       Grad-CAM  0.5311 ± 0.2455  0.1946 ± 0.1593  0.5828 ± 0.2135
1     Grad-CAM++  0.5584 ± 0.2502  0.2150 ± 0.1688  0.6111 ± 0.2168
2      Layer-CAM  0.0920 ± 0.0526  0.0903 ± 0.0879  0.0923 ± 0.0449
3      Cluster 1  0.3103 ± 0.1343  0.1590 ± 0.1467  0.3335 ± 0.1161
4      Cluster 2  0.0328 ± 0.0492  0.0520 ± 0.0665  0.0298 ± 0.0453
5      Cluster 3  0.1183 ± 0.0993  0.0153 ± 0.0374  0.1341 ± 0.0963
6      Cluster 4  0.0086 ± 0.0237  0.0159 ± 0.0372  0.0074 ± 0.0207

Saved table: figures/KMeans_4/table_carcinoma_iou_comparison.csv

================================================================================


================================================================================
Processing: KMeans with 6 clusters
================================================================================

Label distribution:

label
0.0    8369
1.0    1631
Name: count, dtype: int64

Saved figure: figures/KMeans_6/hist_predicted_prob.png

Prediction Metrics - KMeans with 6 clusters:
============================================================
Number of samples: 10000

label             0.0   1.0
predicted_label
0                8093   124
1                 276  1507

Accuracy: 0.96
Precision: 0.8452047111609646
Recall: 0.923973022685469
F1 Score: 0.8828353837141183
AUC Score: 0.9844677288867657

Fitting linear regression model - KMeans (6 clusters):
============================================================
Coefficients: [ 0.00935097  0.0025288  -0.00113882 -0.01823715 -0.00385356  0.00788003]
Intercept: 52.14655314219659
R-squared: 0.691939196295603

Fitting linear regression model (using cluster counts) - KMeans (6 clusters):
============================================================
Coefficients: [ 0.04178623 -0.01634138 -0.02791999  0.0445188  -0.02068177 -0.02136188]
Intercept: 14.076105208657019
R-squared: 0.7500863027087312
Saved figure: figures/KMeans_6/weight_sum_by_label.png
Saved figure: figures/KMeans_6/weight_sum_all_data.png
Saved figure: figures/KMeans_6/cluster_count_by_label.png
Saved figure: figures/KMeans_6/cluster_count_all_data.png
Saved figure: figures/KMeans_6/iou_by_label_grad_cam.png
Saved figure: figures/KMeans_6/iou_all_data_grad_cam.png
Saved figure: figures/KMeans_6/iou_soft_by_label_grad_cam.png
Saved figure: figures/KMeans_6/iou_soft_all_data_grad_cam.png
Saved figure: figures/KMeans_6/correlation_by_label_grad_cam.png
Saved figure: figures/KMeans_6/correlation_all_data_grad_cam.png
Saved figure: figures/KMeans_6/l2_distance_by_label_grad_cam.png
Saved figure: figures/KMeans_6/l2_distance_all_data_grad_cam.png
Saved figure: figures/KMeans_6/iou_by_label_grad_cam_pp.png
Saved figure: figures/KMeans_6/iou_all_data_grad_cam_pp.png
Saved figure: figures/KMeans_6/iou_soft_by_label_grad_cam_pp.png
Saved figure: figures/KMeans_6/iou_soft_all_data_grad_cam_pp.png
Saved figure: figures/KMeans_6/correlation_by_label_grad_cam_pp.png
Saved figure: figures/KMeans_6/correlation_all_data_grad_cam_pp.png
Saved figure: figures/KMeans_6/l2_distance_by_label_grad_cam_pp.png
Saved figure: figures/KMeans_6/l2_distance_all_data_grad_cam_pp.png
Saved figure: figures/KMeans_6/iou_by_label_layer_cam.png
Saved figure: figures/KMeans_6/iou_all_data_layer_cam.png
Saved figure: figures/KMeans_6/iou_soft_by_label_layer_cam.png
Saved figure: figures/KMeans_6/iou_soft_all_data_layer_cam.png
Saved figure: figures/KMeans_6/correlation_by_label_layer_cam.png
Saved figure: figures/KMeans_6/correlation_all_data_layer_cam.png
Saved figure: figures/KMeans_6/l2_distance_by_label_layer_cam.png
Saved figure: figures/KMeans_6/l2_distance_all_data_layer_cam.png
Saved figure: figures/KMeans_6/iou_hard_carcinoma.png
Saved figure: figures/KMeans_6/iou_soft_carcinoma.png

============================================================
Statistics (Mean ± Std) - KMeans (6 clusters)
============================================================


Grad-CAM - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,9383.3821 ± 799.8997,8.8798 ± 24.6869,0.0087 ± 0.0241,0.0087 ± 0.0241,0.1496 ± 0.2129,0.0187 ± 0.0368,0.1072 ± 0.1258,0.2686 ± 0.2978,2.7228 ± 0.6674
1,2,3086.9357 ± 1803.6088,728.5233 ± 222.7101,0.7114 ± 0.2175,0.1062 ± 0.1268,0.1496 ± 0.2129,0.1037 ± 0.0948,0.1072 ± 0.1258,-0.1779 ± 0.2387,15.8046 ± 3.2794
2,3,8217.2294 ± 1037.5427,83.0409 ± 114.2524,0.0811 ± 0.1116,0.0000 ± 0.0000,0.1496 ± 0.2129,0.0000 ± 0.0000,0.1072 ± 0.1258,0.1262 ± 0.2424,3.6123 ± 1.2519
3,4,6081.3457 ± 1104.0252,27.3729 ± 67.1968,0.0267 ± 0.0656,0.0267 ± 0.0656,0.1496 ± 0.2129,0.0554 ± 0.0834,0.1072 ± 0.1258,0.2404 ± 0.2114,3.9938 ± 0.6876
4,5,15519.7899 ± 712.4760,8.1286 ± 35.5974,0.0079 ± 0.0348,0.0079 ± 0.0348,0.1496 ± 0.2129,0.0119 ± 0.0390,0.1072 ± 0.1258,0.2730 ± 0.3485,1.7949 ± 0.6435
5,6,3814.5063 ± 1407.4874,168.0545 ± 138.3620,0.1641 ± 0.1351,0.0000 ± 0.0003,0.1496 ± 0.2129,0.0001 ± 0.0009,0.1072 ± 0.1258,-0.0366 ± 0.1553,6.9997 ± 1.0050

Saved table: figures/KMeans_6/table_grad_cam_all.csv

Grad-CAM - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,9432.3174 ± 813.8396,0.5489 ± 2.1993,0.0005 ± 0.0021,0.0005 ± 0.0021,0.0679 ± 0.0827,0.0049 ± 0.0175,0.0588 ± 0.0628,0.1504 ± 0.1967,2.5695 ± 0.5212
1,2,2861.6283 ± 1602.6272,731.6014 ± 230.4121,0.7145 ± 0.2250,0.0648 ± 0.0791,0.0679 ± 0.0827,0.0753 ± 0.0724,0.0588 ± 0.0628,-0.0808 ± 0.1422,15.9963 ± 3.2942
2,3,7902.0020 ± 501.7391,97.5556 ± 119.8805,0.0953 ± 0.1171,0.0000 ± 0.0000,0.0679 ± 0.0827,0.0000 ± 0.0000,0.0588 ± 0.0628,0.0305 ± 0.1326,3.7185 ± 1.3234
3,4,6050.2772 ± 1078.7551,2.6108 ± 7.1813,0.0025 ± 0.0070,0.0025 ± 0.0070,0.0679 ± 0.0827,0.0215 ± 0.0429,0.0588 ± 0.0628,0.1819 ± 0.1806,3.8363 ± 0.5576
4,5,15704.4188 ± 558.5827,0.0338 ± 0.6173,0.0000 ± 0.0006,0.0000 ± 0.0006,0.0679 ± 0.0827,0.0003 ± 0.0039,0.0588 ± 0.0628,0.1240 ± 0.1953,1.6329 ± 0.4136
5,6,3539.6945 ± 1042.5600,191.6495 ± 137.6062,0.1872 ± 0.1344,0.0000 ± 0.0002,0.0679 ± 0.0827,0.0001 ± 0.0008,0.0588 ± 0.0628,0.0079 ± 0.0811,7.1291 ± 1.0153

Saved table: figures/KMeans_6/table_grad_cam_label_0.csv

Grad-CAM - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,9157.8624 ± 688.8781,47.2731 ± 40.0305,0.0462 ± 0.0391,0.0462 ± 0.0391,0.5261 ± 0.2242,0.0745 ± 0.0414,0.3303 ± 0.0998,0.7458 ± 0.0786,3.4293 ± 0.7997
1,2,4125.2701 ± 2257.9531,714.3376 ± 182.4606,0.6976 ± 0.1782,0.2973 ± 0.1303,0.5261 ± 0.2242,0.2346 ± 0.0733,0.3303 ± 0.0998,-0.5698 ± 0.1162,14.9215 ± 3.0599
2,3,9669.9627 ± 1519.8178,16.1497 ± 39.2059,0.0158 ± 0.0383,0.0000 ± 0.0000,0.5261 ± 0.2242,0.0000 ± 0.0000,0.3303 ± 0.0998,0.5124 ± 0.1970,3.1229 ± 0.6544
3,4,6224.5259 ± 1203.7053,141.4896 ± 96.1324,0.1382 ± 0.0939,0.1382 ± 0.0939,0.5261 ± 0.2242,0.1923 ± 0.0650,0.3303 ± 0.0998,0.4768 ± 0.1542,4.7195 ± 0.7602
4,5,14668.9229 ± 726.7744,45.4335 ± 73.5794,0.0444 ± 0.0719,0.0444 ± 0.0719,0.5261 ± 0.2242,0.0589 ± 0.0697,0.3303 ± 0.0998,0.8746 ± 0.0779,2.5419 ± 0.9252
5,6,5080.9832 ± 2037.4679,59.3163 ± 75.6227,0.0579 ± 0.0739,0.0001 ± 0.0005,0.5261 ± 0.2242,0.0003 ± 0.0012,0.3303 ± 0.0998,-0.2164 ± 0.2337,6.4035 ± 0.6940

Saved table: figures/KMeans_6/table_grad_cam_label_1.csv

Grad-CAM++ - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,9383.3821 ± 799.8997,8.8798 ± 24.6869,0.0087 ± 0.0241,0.0087 ± 0.0241,0.1810 ± 0.2229,0.0156 ± 0.0330,0.1292 ± 0.1295,0.2572 ± 0.2872,2.5376 ± 0.5222
1,2,3086.9357 ± 1803.6088,728.5233 ± 222.7101,0.7114 ± 0.2175,0.1360 ± 0.1409,0.1810 ± 0.2229,0.1315 ± 0.1037,0.1292 ± 0.1295,-0.1700 ± 0.2272,15.7151 ± 3.3288
2,3,8217.2294 ± 1037.5427,83.0409 ± 114.2524,0.0811 ± 0.1116,0.0001 ± 0.0005,0.1810 ± 0.2229,0.0002 ± 0.0015,0.1292 ± 0.1295,0.1182 ± 0.2327,3.5609 ± 1.2913
3,4,6081.3457 ± 1104.0252,27.3729 ± 67.1968,0.0267 ± 0.0656,0.0267 ± 0.0656,0.1810 ± 0.2229,0.0454 ± 0.0761,0.1292 ± 0.1295,0.2349 ± 0.2040,3.7770 ± 0.5383
4,5,15519.7899 ± 712.4760,8.1286 ± 35.5974,0.0079 ± 0.0348,0.0079 ± 0.0348,0.1810 ± 0.2229,0.0106 ± 0.0366,0.1292 ± 0.1295,0.2545 ± 0.3272,1.7372 ± 0.4881
5,6,3814.5063 ± 1407.4874,168.0545 ± 138.3620,0.1641 ± 0.1351,0.0016 ± 0.0033,0.1810 ± 0.2229,0.0042 ± 0.0080,0.1292 ± 0.1295,-0.0237 ± 0.1436,6.8658 ± 1.0925

Saved table: figures/KMeans_6/table_grad_cam_pp_all.csv

Grad-CAM++ - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,9432.3174 ± 813.8396,0.5489 ± 2.1993,0.0005 ± 0.0021,0.0005 ± 0.0021,0.0978 ± 0.1036,0.0033 ± 0.0126,0.0819 ± 0.0766,0.1482 ± 0.1899,2.5191 ± 0.5304
1,2,2861.6283 ± 1602.6272,731.6014 ± 230.4121,0.7145 ± 0.2250,0.0933 ± 0.0991,0.0978 ± 0.1036,0.1046 ± 0.0884,0.0819 ± 0.0766,-0.0820 ± 0.1377,15.9481 ± 3.3004
2,3,7902.0020 ± 501.7391,97.5556 ± 119.8805,0.0953 ± 0.1171,0.0001 ± 0.0005,0.0978 ± 0.1036,0.0002 ± 0.0016,0.0819 ± 0.0766,0.0299 ± 0.1269,3.6969 ± 1.3385
3,4,6050.2772 ± 1078.7551,2.6108 ± 7.1813,0.0025 ± 0.0070,0.0025 ± 0.0070,0.0978 ± 0.1036,0.0145 ± 0.0319,0.0819 ± 0.0766,0.1812 ± 0.1755,3.7491 ± 0.5514
4,5,15704.4188 ± 558.5827,0.0338 ± 0.6173,0.0000 ± 0.0006,0.0000 ± 0.0006,0.0978 ± 0.1036,0.0002 ± 0.0030,0.0819 ± 0.0766,0.1213 ± 0.1867,1.6612 ± 0.4419
5,6,3539.6945 ± 1042.5600,191.6495 ± 137.6062,0.1872 ± 0.1344,0.0013 ± 0.0029,0.0978 ± 0.1036,0.0041 ± 0.0080,0.0819 ± 0.0766,0.0163 ± 0.0798,7.0648 ± 1.0299

Saved table: figures/KMeans_6/table_grad_cam_pp_label_0.csv

Grad-CAM++ - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,9157.8624 ± 688.8781,47.2731 ± 40.0305,0.0462 ± 0.0391,0.0462 ± 0.0391,0.5646 ± 0.2241,0.0696 ± 0.0398,0.3473 ± 0.0959,0.7334 ± 0.0810,2.6225 ± 0.4738
1,2,4125.2701 ± 2257.9531,714.3376 ± 182.4606,0.6976 ± 0.1782,0.3331 ± 0.1376,0.5646 ± 0.2241,0.2557 ± 0.0741,0.3473 ± 0.0959,-0.5547 ± 0.1115,14.6411 ± 3.2483
2,3,9669.9627 ± 1519.8178,16.1497 ± 39.2059,0.0158 ± 0.0383,0.0001 ± 0.0004,0.5646 ± 0.2241,0.0001 ± 0.0007,0.3473 ± 0.0959,0.5036 ± 0.1941,2.9342 ± 0.7855
3,4,6224.5259 ± 1203.7053,141.4896 ± 96.1324,0.1382 ± 0.0939,0.1382 ± 0.0939,0.5646 ± 0.2241,0.1807 ± 0.0645,0.3473 ± 0.0959,0.4693 ± 0.1462,3.9057 ± 0.4512
4,5,14668.9229 ± 726.7744,45.4335 ± 73.5794,0.0444 ± 0.0719,0.0444 ± 0.0719,0.5646 ± 0.2241,0.0560 ± 0.0679,0.3473 ± 0.0959,0.8368 ± 0.0762,2.0874 ± 0.5359
5,6,5080.9832 ± 2037.4679,59.3163 ± 75.6227,0.0579 ± 0.0739,0.0028 ± 0.0046,0.5646 ± 0.2241,0.0046 ± 0.0077,0.3473 ± 0.0959,-0.1983 ± 0.2131,5.9490 ± 0.8847

Saved table: figures/KMeans_6/table_grad_cam_pp_label_1.csv

Layer-CAM - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,9383.3821 ± 799.8997,8.8798 ± 24.6869,0.0087 ± 0.0241,0.0030 ± 0.0064,0.0280 ± 0.0222,0.0344 ± 0.0639,0.0268 ± 0.0208,0.1507 ± 0.1411,2.7713 ± 0.7651
1,2,3086.9357 ± 1803.6088,728.5233 ± 222.7101,0.7114 ± 0.2175,0.0167 ± 0.0131,0.0280 ± 0.0222,0.0234 ± 0.0191,0.0268 ± 0.0208,-0.0917 ± 0.0969,15.8121 ± 3.2673
2,3,8217.2294 ± 1037.5427,83.0409 ± 114.2524,0.0811 ± 0.1116,0.0000 ± 0.0001,0.0280 ± 0.0222,0.0001 ± 0.0009,0.0268 ± 0.0208,0.0648 ± 0.1085,3.7041 ± 1.2517
3,4,6081.3457 ± 1104.0252,27.3729 ± 67.1968,0.0267 ± 0.0656,0.0057 ± 0.0096,0.0280 ± 0.0222,0.0595 ± 0.0844,0.0268 ± 0.0208,0.1299 ± 0.1023,4.0145 ± 0.7591
4,5,15519.7899 ± 712.4760,8.1286 ± 35.5974,0.0079 ± 0.0348,0.0025 ± 0.0076,0.0280 ± 0.0222,0.0210 ± 0.0540,0.0268 ± 0.0208,0.1576 ± 0.1745,1.9070 ± 0.7716
5,6,3814.5063 ± 1407.4874,168.0545 ± 138.3620,0.1641 ± 0.1351,0.0002 ± 0.0005,0.0280 ± 0.0222,0.0008 ± 0.0030,0.0268 ± 0.0208,-0.0105 ± 0.0644,7.0250 ± 0.9886

Saved table: figures/KMeans_6/table_layer_cam_all.csv

Layer-CAM - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,9432.3174 ± 813.8396,0.5489 ± 2.1993,0.0005 ± 0.0021,0.0005 ± 0.0017,0.0205 ± 0.0162,0.0109 ± 0.0358,0.0198 ± 0.0155,0.1159 ± 0.1249,2.5610 ± 0.5269
1,2,2861.6283 ± 1602.6272,731.6014 ± 230.4121,0.7145 ± 0.2250,0.0178 ± 0.0137,0.0205 ± 0.0162,0.0253 ± 0.0202,0.0198 ± 0.0155,-0.0632 ± 0.0800,15.9824 ± 3.2960
2,3,7902.0020 ± 501.7391,97.5556 ± 119.8805,0.0953 ± 0.1171,0.0000 ± 0.0001,0.0205 ± 0.0162,0.0001 ± 0.0010,0.0198 ± 0.0155,0.0285 ± 0.0760,3.7222 ± 1.3267
3,4,6050.2772 ± 1078.7551,2.6108 ± 7.1813,0.0025 ± 0.0070,0.0020 ± 0.0045,0.0205 ± 0.0162,0.0413 ± 0.0765,0.0198 ± 0.0155,0.1272 ± 0.1034,3.8098 ± 0.5566
4,5,15704.4188 ± 558.5827,0.0338 ± 0.6173,0.0000 ± 0.0006,0.0000 ± 0.0004,0.0205 ± 0.0162,0.0006 ± 0.0086,0.0198 ± 0.0155,0.0994 ± 0.1278,1.6692 ± 0.4305
5,6,3539.6945 ± 1042.5600,191.6495 ± 137.6062,0.1872 ± 0.1344,0.0002 ± 0.0006,0.0205 ± 0.0162,0.0009 ± 0.0032,0.0198 ± 0.0155,0.0083 ± 0.0470,7.1104 ± 1.0189

Saved table: figures/KMeans_6/table_layer_cam_label_0.csv

Layer-CAM - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,9157.8624 ± 688.8781,47.2731 ± 40.0305,0.0462 ± 0.0391,0.0147 ± 0.0073,0.0624 ± 0.0108,0.1369 ± 0.0583,0.0586 ± 0.0096,0.3030 ± 0.1011,3.7408 ± 0.9278
1,2,4125.2701 ± 2257.9531,714.3376 ± 182.4606,0.6976 ± 0.1782,0.0113 ± 0.0078,0.0624 ± 0.0108,0.0143 ± 0.0084,0.0586 ± 0.0096,-0.2160 ± 0.0586,15.0273 ± 3.0103
2,3,9669.9627 ± 1519.8178,16.1497 ± 39.2059,0.0158 ± 0.0383,0.0000 ± 0.0000,0.0624 ± 0.0108,0.0000 ± 0.0003,0.0586 ± 0.0096,0.2237 ± 0.0838,3.6203 ± 0.8169
3,4,6224.5259 ± 1203.7053,141.4896 ± 96.1324,0.1382 ± 0.0939,0.0227 ± 0.0086,0.0624 ± 0.0108,0.1388 ± 0.0701,0.0586 ± 0.0096,0.1417 ± 0.0963,4.9582 ± 0.8490
4,5,14668.9229 ± 726.7744,45.4335 ± 73.5794,0.0444 ± 0.0719,0.0137 ± 0.0131,0.0624 ± 0.0108,0.1099 ± 0.0749,0.0586 ± 0.0096,0.4119 ± 0.1128,3.0029 ± 1.0120
5,6,5080.9832 ± 2037.4679,59.3163 ± 75.6227,0.0579 ± 0.0739,0.0000 ± 0.0001,0.0624 ± 0.0108,0.0001 ± 0.0009,0.0586 ± 0.0096,-0.0924 ± 0.0659,6.6313 ± 0.7131

Saved table: figures/KMeans_6/table_layer_cam_label_1.csv

============================================================
CAM-Cluster Comparison (Label 0 vs Label 1) - KMeans (6 clusters)
============================================================

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0049 ± 0.0175,0.1504 ± 0.1967,2.5695 ± 0.5212,0.0745 ± 0.0414,0.7458 ± 0.0786,3.4293 ± 0.7997
1,2,0.0753 ± 0.0724,-0.0808 ± 0.1422,15.9963 ± 3.2942,0.2346 ± 0.0733,-0.5698 ± 0.1162,14.9215 ± 3.0599
2,3,0.0000 ± 0.0000,0.0305 ± 0.1326,3.7185 ± 1.3234,0.0000 ± 0.0000,0.5124 ± 0.1970,3.1229 ± 0.6544
3,4,0.0215 ± 0.0429,0.1819 ± 0.1806,3.8363 ± 0.5576,0.1923 ± 0.0650,0.4768 ± 0.1542,4.7195 ± 0.7602
4,5,0.0003 ± 0.0039,0.1240 ± 0.1953,1.6329 ± 0.4136,0.0589 ± 0.0697,0.8746 ± 0.0779,2.5419 ± 0.9252
5,6,0.0001 ± 0.0008,0.0079 ± 0.0811,7.1291 ± 1.0153,0.0003 ± 0.0012,-0.2164 ± 0.2337,6.4035 ± 0.6940

Saved table: figures/KMeans_6/table_grad_cam_cluster_comparison.csv

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0033 ± 0.0126,0.1482 ± 0.1899,2.5191 ± 0.5304,0.0696 ± 0.0398,0.7334 ± 0.0810,2.6225 ± 0.4738
1,2,0.1046 ± 0.0884,-0.0820 ± 0.1377,15.9481 ± 3.3004,0.2557 ± 0.0741,-0.5547 ± 0.1115,14.6411 ± 3.2483
2,3,0.0002 ± 0.0016,0.0299 ± 0.1269,3.6969 ± 1.3385,0.0001 ± 0.0007,0.5036 ± 0.1941,2.9342 ± 0.7855
3,4,0.0145 ± 0.0319,0.1812 ± 0.1755,3.7491 ± 0.5514,0.1807 ± 0.0645,0.4693 ± 0.1462,3.9057 ± 0.4512
4,5,0.0002 ± 0.0030,0.1213 ± 0.1867,1.6612 ± 0.4419,0.0560 ± 0.0679,0.8368 ± 0.0762,2.0874 ± 0.5359
5,6,0.0041 ± 0.0080,0.0163 ± 0.0798,7.0648 ± 1.0299,0.0046 ± 0.0077,-0.1983 ± 0.2131,5.9490 ± 0.8847

Saved table: figures/KMeans_6/table_grad_cam_pp_cluster_comparison.csv

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0109 ± 0.0358,0.1159 ± 0.1249,2.5610 ± 0.5269,0.1369 ± 0.0583,0.3030 ± 0.1011,3.7408 ± 0.9278
1,2,0.0253 ± 0.0202,-0.0632 ± 0.0800,15.9824 ± 3.2960,0.0143 ± 0.0084,-0.2160 ± 0.0586,15.0273 ± 3.0103
2,3,0.0001 ± 0.0010,0.0285 ± 0.0760,3.7222 ± 1.3267,0.0000 ± 0.0003,0.2237 ± 0.0838,3.6203 ± 0.8169
3,4,0.0413 ± 0.0765,0.1272 ± 0.1034,3.8098 ± 0.5566,0.1388 ± 0.0701,0.1417 ± 0.0963,4.9582 ± 0.8490
4,5,0.0006 ± 0.0086,0.0994 ± 0.1278,1.6692 ± 0.4305,0.1099 ± 0.0749,0.4119 ± 0.1128,3.0029 ± 1.0120
5,6,0.0009 ± 0.0032,0.0083 ± 0.0470,7.1104 ± 1.0189,0.0001 ± 0.0009,-0.0924 ± 0.0659,6.6313 ± 0.7131

Saved table: figures/KMeans_6/table_layer_cam_cluster_comparison.csv

============================================================
CAM IoU (All Data) and Correlation (Label 0, Label 1) - KMeans (6 clusters)
============================================================

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.0187 ± 0.0368       0.1504 ± 0.1967       0.7458 ± 0.0786
1        2  0.1037 ± 0.0948      -0.0808 ± 0.1422      -0.5698 ± 0.1162
2        3  0.0000 ± 0.0000       0.0305 ± 0.1326       0.5124 ± 0.1970
3        4  0.0554 ± 0.0834       0.1819 ± 0.1806       0.4768 ± 0.1542
4        5  0.0119 ± 0.0390       0.1240 ± 0.1953       0.8746 ± 0.0779
5        6  0.0001 ± 0.0009       0.0079 ± 0.0811      -0.2164 ± 0.2337

Saved table: figures/KMeans_6/table_grad_cam_iou_correlation.csv

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.0156 ± 0.0330       0.1482 ± 0.1899       0.7334 ± 0.0810
1        2  0.1315 ± 0.1037      -0.0820 ± 0.1377      -0.5547 ± 0.1115
2        3  0.0002 ± 0.0015       0.0299 ± 0.1269       0.5036 ± 0.1941
3        4  0.0454 ± 0.0761       0.1812 ± 0.1755       0.4693 ± 0.1462
4        5  0.0106 ± 0.0366       0.1213 ± 0.1867       0.8368 ± 0.0762
5        6  0.0042 ± 0.0080       0.0163 ± 0.0798      -0.1983 ± 0.2131

Saved table: figures/KMeans_6/table_grad_cam_pp_iou_correlation.csv

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.0344 ± 0.0639       0.1159 ± 0.1249       0.3030 ± 0.1011
1        2  0.0234 ± 0.0191      -0.0632 ± 0.0800      -0.2160 ± 0.0586
2        3  0.0001 ± 0.0009       0.0285 ± 0.0760       0.2237 ± 0.0838
3        4  0.0595 ± 0.0844       0.1272 ± 0.1034       0.1417 ± 0.0963
4        5  0.0210 ± 0.0540       0.0994 ± 0.1278       0.4119 ± 0.1128
5        6  0.0008 ± 0.0030       0.0083 ± 0.0470      -0.0924 ± 0.0659

Saved table: figures/KMeans_6/table_layer_cam_iou_correlation.csv

============================================================
Normalized Cluster Count Comparison - KMeans (6 clusters)
============================================================

   Cluster         All Data          Label 0          Label 1
0        1  0.0087 ± 0.0241  0.0005 ± 0.0021  0.0462 ± 0.0391
1        2  0.7114 ± 0.2175  0.7145 ± 0.2250  0.6976 ± 0.1782
2        3  0.0811 ± 0.1116  0.0953 ± 0.1171  0.0158 ± 0.0383
3        4  0.0267 ± 0.0656  0.0025 ± 0.0070  0.1382 ± 0.0939
4        5  0.0079 ± 0.0348  0.0000 ± 0.0006  0.0444 ± 0.0719
5        6  0.1641 ± 0.1351  0.1872 ± 0.1344  0.0579 ± 0.0739

Saved table: figures/KMeans_6/table_norm_count_comparison.csv

============================================================
Annotation Mask Statistics - KMeans (6 clusters)
============================================================


Carcinoma Mask Metrics - All Data (n=1841):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.4200 ± 0.2724,0.5311 ± 0.2455,N/A,NaN
1,Grad-CAM++,0.4471 ± 0.2806,0.5584 ± 0.2502,N/A,NaN
2,Layer-CAM,0.0516 ± 0.0212,0.0920 ± 0.0526,N/A,NaN
3,Cluster 1,0.0402 ± 0.0400,0.0524 ± 0.0404,0.3583 ± 0.1482,0.6330 ± 0.3287
4,Cluster 2,0.3855 ± 0.2332,0.2642 ± 0.1237,0.3583 ± 0.1482,0.6330 ± 0.3287
5,Cluster 3,0.0091 ± 0.0232,0.0140 ± 0.0328,0.3583 ± 0.1482,0.6330 ± 0.3287
6,Cluster 4,0.1194 ± 0.0987,0.1373 ± 0.0777,0.3583 ± 0.1482,0.6330 ± 0.3287
7,Cluster 5,0.0401 ± 0.0701,0.0456 ± 0.0645,0.3583 ± 0.1482,0.6330 ± 0.3287
8,Cluster 6,0.0387 ± 0.0547,0.0502 ± 0.0587,0.3583 ± 0.1482,0.6330 ± 0.3287

Saved table: figures/KMeans_6/table_carcinoma_all.csv

Carcinoma Mask Metrics - Predicted Label 0 (n=245):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.0800 ± 0.0938,0.1946 ± 0.1593,N/A,NaN
1,Grad-CAM++,0.0967 ± 0.1128,0.2150 ± 0.1688,N/A,NaN
2,Layer-CAM,0.0199 ± 0.0174,0.0903 ± 0.0879,N/A,NaN
3,Cluster 1,0.0022 ± 0.0049,0.0106 ± 0.0243,0.1697 ± 0.1552,0.2566 ± 0.2855
4,Cluster 2,0.1914 ± 0.2350,0.1466 ± 0.1405,0.1697 ± 0.1552,0.2566 ± 0.2855
5,Cluster 3,0.0123 ± 0.0290,0.0253 ± 0.0502,0.1697 ± 0.1552,0.2566 ± 0.2855
6,Cluster 4,0.0107 ± 0.0177,0.0408 ± 0.0604,0.1697 ± 0.1552,0.2566 ± 0.2855
7,Cluster 5,0.0005 ± 0.0029,0.0020 ± 0.0084,0.1697 ± 0.1552,0.2566 ± 0.2855
8,Cluster 6,0.0395 ± 0.0642,0.0717 ± 0.0736,0.1697 ± 0.1552,0.2566 ± 0.2855

Saved table: figures/KMeans_6/table_carcinoma_label_0.csv

Carcinoma Mask Metrics - Predicted Label 1 (n=1596):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.4723 ± 0.2525,0.5828 ± 0.2135,N/A,NaN
1,Grad-CAM++,0.5009 ± 0.2592,0.6111 ± 0.2168,N/A,NaN
2,Layer-CAM,0.0565 ± 0.0171,0.0923 ± 0.0449,N/A,NaN
3,Cluster 1,0.0460 ± 0.0399,0.0589 ± 0.0385,0.3873 ± 0.1240,0.6908 ± 0.2950
4,Cluster 2,0.4153 ± 0.2182,0.2822 ± 0.1104,0.3873 ± 0.1240,0.6908 ± 0.2950
5,Cluster 3,0.0086 ± 0.0221,0.0122 ± 0.0289,0.3873 ± 0.1240,0.6908 ± 0.2950
6,Cluster 4,0.1361 ± 0.0954,0.1521 ± 0.0690,0.3873 ± 0.1240,0.6908 ± 0.2950
7,Cluster 5,0.0462 ± 0.0735,0.0523 ± 0.0667,0.3873 ± 0.1240,0.6908 ± 0.2950
8,Cluster 6,0.0386 ± 0.0531,0.0469 ± 0.0554,0.3873 ± 0.1240,0.6908 ± 0.2950

Saved table: figures/KMeans_6/table_carcinoma_label_1.csv

============================================================
Carcinoma IoU Comparison - KMeans (6 clusters)
============================================================

  Method/Cluster         All Data          Label 0          Label 1
0       Grad-CAM  0.5311 ± 0.2455  0.1946 ± 0.1593  0.5828 ± 0.2135
1     Grad-CAM++  0.5584 ± 0.2502  0.2150 ± 0.1688  0.6111 ± 0.2168
2      Layer-CAM  0.0920 ± 0.0526  0.0903 ± 0.0879  0.0923 ± 0.0449
3      Cluster 1  0.0524 ± 0.0404  0.0106 ± 0.0243  0.0589 ± 0.0385
4      Cluster 2  0.2642 ± 0.1237  0.1466 ± 0.1405  0.2822 ± 0.1104
5      Cluster 3  0.0140 ± 0.0328  0.0253 ± 0.0502  0.0122 ± 0.0289
6      Cluster 4  0.1373 ± 0.0777  0.0408 ± 0.0604  0.1521 ± 0.0690
7      Cluster 5  0.0456 ± 0.0645  0.0020 ± 0.0084  0.0523 ± 0.0667
8      Cluster 6  0.0502 ± 0.0587  0.0717 ± 0.0736  0.0469 ± 0.0554

Saved table: figures/KMeans_6/table_carcinoma_iou_comparison.csv

================================================================================


================================================================================
Processing: KMeans with 8 clusters
================================================================================

Label distribution:

label
0.0    8369
1.0    1631
Name: count, dtype: int64

Saved figure: figures/KMeans_8/hist_predicted_prob.png

Prediction Metrics - KMeans with 8 clusters:
============================================================
Number of samples: 10000

label             0.0   1.0
predicted_label
0                8093   124
1                 276  1507

Accuracy: 0.96
Precision: 0.8452047111609646
Recall: 0.923973022685469
F1 Score: 0.8828353837141183
AUC Score: 0.9844677288867657

Fitting linear regression model - KMeans (8 clusters):
============================================================
Coefficients: [-0.02770329  0.00061271  0.00503526  0.00395215  0.01135531 -0.00072959
  0.01734138 -0.00461526]
Intercept: -126.31627710649313
R-squared: 0.8245704514837064

Fitting linear regression model (using cluster counts) - KMeans (8 clusters):
============================================================
Coefficients: [ 0.06366098  0.00377478 -0.00634152 -0.00539064  0.00447312 -0.00516344
 -0.03789335 -0.01711993]
Intercept: -4.637570204082763
R-squared: 0.805772470759121
Saved figure: figures/KMeans_8/weight_sum_by_label.png
Saved figure: figures/KMeans_8/weight_sum_all_data.png
Saved figure: figures/KMeans_8/cluster_count_by_label.png
Saved figure: figures/KMeans_8/cluster_count_all_data.png
Saved figure: figures/KMeans_8/iou_by_label_grad_cam.png
Saved figure: figures/KMeans_8/iou_all_data_grad_cam.png
Saved figure: figures/KMeans_8/iou_soft_by_label_grad_cam.png
Saved figure: figures/KMeans_8/iou_soft_all_data_grad_cam.png
Saved figure: figures/KMeans_8/correlation_by_label_grad_cam.png
Saved figure: figures/KMeans_8/correlation_all_data_grad_cam.png
Saved figure: figures/KMeans_8/l2_distance_by_label_grad_cam.png
Saved figure: figures/KMeans_8/l2_distance_all_data_grad_cam.png
Saved figure: figures/KMeans_8/iou_by_label_grad_cam_pp.png
Saved figure: figures/KMeans_8/iou_all_data_grad_cam_pp.png
Saved figure: figures/KMeans_8/iou_soft_by_label_grad_cam_pp.png
Saved figure: figures/KMeans_8/iou_soft_all_data_grad_cam_pp.png
Saved figure: figures/KMeans_8/correlation_by_label_grad_cam_pp.png
Saved figure: figures/KMeans_8/correlation_all_data_grad_cam_pp.png
Saved figure: figures/KMeans_8/l2_distance_by_label_grad_cam_pp.png
Saved figure: figures/KMeans_8/l2_distance_all_data_grad_cam_pp.png
Saved figure: figures/KMeans_8/iou_by_label_layer_cam.png
Saved figure: figures/KMeans_8/iou_all_data_layer_cam.png
Saved figure: figures/KMeans_8/iou_soft_by_label_layer_cam.png
Saved figure: figures/KMeans_8/iou_soft_all_data_layer_cam.png
Saved figure: figures/KMeans_8/correlation_by_label_layer_cam.png
Saved figure: figures/KMeans_8/correlation_all_data_layer_cam.png
Saved figure: figures/KMeans_8/l2_distance_by_label_layer_cam.png
Saved figure: figures/KMeans_8/l2_distance_all_data_layer_cam.png
Saved figure: figures/KMeans_8/iou_hard_carcinoma.png
Saved figure: figures/KMeans_8/iou_soft_carcinoma.png

============================================================
Statistics (Mean ± Std) - KMeans (8 clusters)
============================================================


Grad-CAM - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,6393.4511 ± 1059.6370,31.8921 ± 78.8891,0.0311 ± 0.0770,0.0311 ± 0.0770,0.1496 ± 0.2129,0.0615 ± 0.0938,0.1072 ± 0.1258,0.2874 ± 0.2227,3.1253 ± 0.5197
1,2,3067.2903 ± 1789.1997,757.6887 ± 194.2047,0.7399 ± 0.1897,0.1081 ± 0.1297,0.1496 ± 0.2129,0.1018 ± 0.0947,0.1072 ± 0.1258,-0.1760 ± 0.2314,14.5391 ± 3.1776
2,3,12543.9374 ± 967.7892,15.2200 ± 32.6152,0.0149 ± 0.0319,0.0000 ± 0.0000,0.1496 ± 0.2129,0.0000 ± 0.0000,0.1072 ± 0.1258,0.1927 ± 0.2958,1.8722 ± 0.6092
3,4,4877.8186 ± 1197.0251,107.0499 ± 104.6931,0.1045 ± 0.1022,0.0000 ± 0.0001,0.1496 ± 0.2129,0.0000 ± 0.0003,0.1072 ± 0.1258,0.0341 ± 0.1294,4.4661 ± 0.8256
4,5,14473.6852 ± 704.0515,10.6460 ± 42.7393,0.0104 ± 0.0417,0.0104 ± 0.0417,0.1496 ± 0.2129,0.0158 ± 0.0465,0.1072 ± 0.1258,0.3047 ± 0.3457,1.5078 ± 0.5176
5,6,9310.9150 ± 1091.0605,36.2626 ± 59.4443,0.0354 ± 0.0581,0.0000 ± 0.0000,0.1496 ± 0.2129,0.0000 ± 0.0000,0.1072 ± 0.1258,0.1512 ± 0.2636,2.5362 ± 0.8105
6,7,5259.4327 ± 1382.5947,30.7405 ± 43.7994,0.0300 ± 0.0428,0.0000 ± 0.0002,0.1496 ± 0.2129,0.0001 ± 0.0010,0.1072 ± 0.1258,0.1087 ± 0.1324,3.8811 ± 0.4161
7,8,6925.9406 ± 991.6360,34.5002 ± 47.4053,0.0337 ± 0.0463,0.0000 ± 0.0000,0.1496 ± 0.2129,0.0000 ± 0.0000,0.1072 ± 0.1258,0.1329 ± 0.2090,3.0551 ± 0.6409

Saved table: figures/KMeans_8/table_grad_cam_all.csv

Grad-CAM - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,6377.3347 ± 1045.7299,2.7890 ± 7.7591,0.0027 ± 0.0076,0.0027 ± 0.0076,0.0679 ± 0.0827,0.0227 ± 0.0462,0.0588 ± 0.0628,0.2277 ± 0.1971,2.9728 ± 0.3362
1,2,2838.3682 ± 1580.8537,760.8941 ± 197.9163,0.7431 ± 0.1933,0.0651 ± 0.0794,0.0679 ± 0.0827,0.0728 ± 0.0707,0.0588 ± 0.0628,-0.0824 ± 0.1394,14.7274 ± 3.1935
2,3,12265.7608 ± 612.4163,18.0837 ± 35.1229,0.0177 ± 0.0343,0.0000 ± 0.0000,0.0679 ± 0.0827,0.0000 ± 0.0000,0.0588 ± 0.0628,0.0667 ± 0.1503,1.8817 ± 0.6495
3,4,4583.2563 ± 711.2014,122.9848 ± 106.3759,0.1201 ± 0.1039,0.0000 ± 0.0000,0.0679 ± 0.0827,0.0000 ± 0.0003,0.0588 ± 0.0628,0.0238 ± 0.0999,4.5481 ± 0.8591
4,5,14644.5220 ± 590.0512,0.0692 ± 0.8896,0.0001 ± 0.0009,0.0001 ± 0.0009,0.0679 ± 0.0827,0.0005 ± 0.0057,0.0588 ± 0.0628,0.1617 ± 0.2127,1.3554 ± 0.2582
5,6,8991.3532 ± 647.3652,42.6358 ± 63.1177,0.0416 ± 0.0616,0.0000 ± 0.0000,0.0679 ± 0.0827,0.0000 ± 0.0000,0.0588 ± 0.0628,0.0433 ± 0.1382,2.5822 ± 0.8632
6,7,5047.9196 ± 1155.0600,36.2783 ± 46.1359,0.0354 ± 0.0451,0.0000 ± 0.0002,0.0679 ± 0.0827,0.0001 ± 0.0010,0.0588 ± 0.0628,0.1060 ± 0.1079,3.8651 ± 0.4344
7,8,6637.5506 ± 401.0751,40.2651 ± 49.7305,0.0393 ± 0.0486,0.0000 ± 0.0000,0.0679 ± 0.0827,0.0000 ± 0.0000,0.0588 ± 0.0628,0.0537 ± 0.1304,3.0810 ± 0.6797

Saved table: figures/KMeans_8/table_grad_cam_label_0.csv

Grad-CAM - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,6467.7236 ± 1118.8114,166.0146 ± 112.8655,0.1621 ± 0.1102,0.1621 ± 0.1102,0.5261 ± 0.2242,0.2180 ± 0.0715,0.3303 ± 0.0998,0.5282 ± 0.1439,3.8281 ± 0.6269
1,2,4122.2835 ± 2254.9917,742.9164 ± 175.3874,0.7255 ± 0.1713,0.3060 ± 0.1329,0.5261 ± 0.2242,0.2358 ± 0.0739,0.3303 ± 0.0998,-0.5537 ± 0.1148,13.6713 ± 2.9530
2,3,13825.9212 ± 1234.9206,2.0224 ± 8.3113,0.0020 ± 0.0081,0.0000 ± 0.0000,0.5261 ± 0.2242,0.0000 ± 0.0000,0.3303 ± 0.0998,0.7010 ± 0.1641,1.8284 ± 0.3680
3,4,6235.3160 ± 1861.1855,33.6136 ± 52.5590,0.0328 ± 0.0513,0.0000 ± 0.0002,0.5261 ± 0.2242,0.0000 ± 0.0004,0.3303 ± 0.0998,0.0758 ± 0.2047,4.0879 ± 0.4979
4,5,13686.3795 ± 649.1360,59.3892 ± 85.7486,0.0580 ± 0.0837,0.0580 ± 0.0837,0.5261 ± 0.2242,0.0775 ± 0.0776,0.3303 ± 0.0998,0.8819 ± 0.0597,2.2103 ± 0.7712
5,6,10783.6236 ± 1451.3335,6.8918 ± 20.2344,0.0067 ± 0.0198,0.0000 ± 0.0000,0.5261 ± 0.2242,0.0000 ± 0.0000,0.3303 ± 0.0998,0.5866 ± 0.1908,2.3241 ± 0.4422
6,7,6234.1959 ± 1848.7311,5.2193 ± 12.5505,0.0051 ± 0.0123,0.0000 ± 0.0002,0.5261 ± 0.2242,0.0001 ± 0.0011,0.3303 ± 0.0998,0.1199 ± 0.2030,3.9547 ± 0.3079
7,8,8254.9931 ± 1620.2191,7.9327 ± 18.6474,0.0077 ± 0.0182,0.0000 ± 0.0000,0.5261 ± 0.2242,0.0000 ± 0.0000,0.3303 ± 0.0998,0.4526 ± 0.1545,2.9358 ± 0.3964

Saved table: figures/KMeans_8/table_grad_cam_label_1.csv

Grad-CAM++ - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,6393.4511 ± 1059.6370,31.8921 ± 78.8891,0.0311 ± 0.0770,0.0311 ± 0.0770,0.1810 ± 0.2229,0.0508 ± 0.0859,0.1292 ± 0.1295,0.2807 ± 0.2165,2.9753 ± 0.3713
1,2,3067.2903 ± 1789.1997,757.6887 ± 194.2047,0.7399 ± 0.1897,0.1349 ± 0.1431,0.1810 ± 0.2229,0.1258 ± 0.1029,0.1292 ± 0.1295,-0.1687 ± 0.2204,14.4739 ± 3.2160
2,3,12543.9374 ± 967.7892,15.2200 ± 32.6152,0.0149 ± 0.0319,0.0000 ± 0.0001,0.1810 ± 0.2229,0.0000 ± 0.0008,0.1292 ± 0.1295,0.1802 ± 0.2815,2.0336 ± 0.6952
3,4,4877.8186 ± 1197.0251,107.0499 ± 104.6931,0.1045 ± 0.1022,0.0005 ± 0.0016,0.1810 ± 0.2229,0.0017 ± 0.0049,0.1292 ± 0.1295,0.0375 ± 0.1216,4.4006 ± 0.8769
4,5,14473.6852 ± 704.0515,10.6460 ± 42.7393,0.0104 ± 0.0417,0.0104 ± 0.0417,0.1810 ± 0.2229,0.0140 ± 0.0435,0.1292 ± 0.1295,0.2860 ± 0.3264,1.5372 ± 0.4612
5,6,9310.9150 ± 1091.0605,36.2626 ± 59.4443,0.0354 ± 0.0581,0.0000 ± 0.0004,0.1810 ± 0.2229,0.0001 ± 0.0014,0.1292 ± 0.1295,0.1409 ± 0.2521,2.6053 ± 0.8422
6,7,5259.4327 ± 1382.5947,30.7405 ± 43.7994,0.0300 ± 0.0428,0.0039 ± 0.0075,0.1810 ± 0.2229,0.0194 ± 0.0340,0.1292 ± 0.1295,0.1228 ± 0.1193,3.8056 ± 0.4356
7,8,6925.9406 ± 991.6360,34.5002 ± 47.4053,0.0337 ± 0.0463,0.0000 ± 0.0003,0.1810 ± 0.2229,0.0003 ± 0.0018,0.1292 ± 0.1295,0.1272 ± 0.2014,3.0444 ± 0.6804

Saved table: figures/KMeans_8/table_grad_cam_pp_all.csv

Grad-CAM++ - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,6377.3347 ± 1045.7299,2.7890 ± 7.7591,0.0027 ± 0.0076,0.0027 ± 0.0076,0.0978 ± 0.1036,0.0154 ± 0.0344,0.0819 ± 0.0766,0.2262 ± 0.1928,2.9063 ± 0.3290
1,2,2838.3682 ± 1580.8537,760.8941 ± 197.9163,0.7431 ± 0.1933,0.0900 ± 0.0968,0.0978 ± 0.1036,0.0974 ± 0.0847,0.0819 ± 0.0766,-0.0837 ± 0.1347,14.6868 ± 3.1989
2,3,12265.7608 ± 612.4163,18.0837 ± 35.1229,0.0177 ± 0.0343,0.0000 ± 0.0001,0.0978 ± 0.1036,0.0000 ± 0.0009,0.0819 ± 0.0766,0.0651 ± 0.1431,1.9317 ± 0.6686
3,4,4583.2563 ± 711.2014,122.9848 ± 106.3759,0.1201 ± 0.1039,0.0004 ± 0.0015,0.0978 ± 0.1036,0.0017 ± 0.0051,0.0819 ± 0.0766,0.0265 ± 0.0967,4.5066 ± 0.8750
4,5,14644.5220 ± 590.0512,0.0692 ± 0.8896,0.0001 ± 0.0009,0.0001 ± 0.0009,0.0978 ± 0.1036,0.0004 ± 0.0043,0.0819 ± 0.0766,0.1578 ± 0.2042,1.4084 ± 0.3209
5,6,8991.3532 ± 647.3652,42.6358 ± 63.1177,0.0416 ± 0.0616,0.0000 ± 0.0004,0.0978 ± 0.1036,0.0001 ± 0.0015,0.0819 ± 0.0766,0.0419 ± 0.1323,2.5949 ± 0.8771
6,7,5047.9196 ± 1155.0600,36.2783 ± 46.1359,0.0354 ± 0.0451,0.0045 ± 0.0080,0.0978 ± 0.1036,0.0231 ± 0.0364,0.0819 ± 0.0766,0.1202 ± 0.1004,3.8144 ± 0.4274
7,8,6637.5506 ± 401.0751,40.2651 ± 49.7305,0.0393 ± 0.0486,0.0000 ± 0.0003,0.0978 ± 0.1036,0.0003 ± 0.0019,0.0819 ± 0.0766,0.0538 ± 0.1252,3.0619 ± 0.6956

Saved table: figures/KMeans_8/table_grad_cam_pp_label_0.csv

Grad-CAM++ - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,6467.7236 ± 1118.8114,166.0146 ± 112.8655,0.1621 ± 0.1102,0.1621 ± 0.1102,0.5646 ± 0.2241,0.2052 ± 0.0713,0.3473 ± 0.0959,0.5189 ± 0.1400,3.2934 ± 0.3892
1,2,4122.2835 ± 2254.9917,742.9164 ± 175.3874,0.7255 ± 0.1713,0.3421 ± 0.1397,0.5646 ± 0.2241,0.2566 ± 0.0744,0.3473 ± 0.0959,-0.5398 ± 0.1109,13.4930 ± 3.1115
2,3,13825.9212 ± 1234.9206,2.0224 ± 8.3113,0.0020 ± 0.0081,0.0000 ± 0.0000,0.5646 ± 0.2241,0.0000 ± 0.0001,0.3473 ± 0.0959,0.6829 ± 0.1597,2.5034 ± 0.6178
3,4,6235.3160 ± 1861.1855,33.6136 ± 52.5590,0.0328 ± 0.0513,0.0009 ± 0.0022,0.5646 ± 0.2241,0.0017 ± 0.0040,0.3473 ± 0.0959,0.0855 ± 0.1889,3.9122 ± 0.7029
4,5,13686.3795 ± 649.1360,59.3892 ± 85.7486,0.0580 ± 0.0837,0.0580 ± 0.0837,0.5646 ± 0.2241,0.0735 ± 0.0757,0.3473 ± 0.0959,0.8462 ± 0.0640,2.1305 ± 0.5389
5,6,10783.6236 ± 1451.3335,6.8918 ± 20.2344,0.0067 ± 0.0198,0.0000 ± 0.0002,0.5646 ± 0.2241,0.0001 ± 0.0005,0.3473 ± 0.0959,0.5733 ± 0.1868,2.6533 ± 0.6563
6,7,6234.1959 ± 1848.7311,5.2193 ± 12.5505,0.0051 ± 0.0123,0.0014 ± 0.0036,0.5646 ± 0.2241,0.0029 ± 0.0083,0.3473 ± 0.0959,0.1341 ± 0.1797,3.7653 ± 0.4695
7,8,8254.9931 ± 1620.2191,7.9327 ± 18.6474,0.0077 ± 0.0182,0.0001 ± 0.0004,0.5646 ± 0.2241,0.0002 ± 0.0009,0.3473 ± 0.0959,0.4479 ± 0.1517,2.9639 ± 0.5991

Saved table: figures/KMeans_8/table_grad_cam_pp_label_1.csv

Layer-CAM - Overall:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,6393.4511 ± 1059.6370,31.8921 ± 78.8891,0.0311 ± 0.0770,0.0074 ± 0.0131,0.0280 ± 0.0222,0.0686 ± 0.0973,0.0268 ± 0.0208,0.1570 ± 0.1155,3.1848 ± 0.6586
1,2,3067.2903 ± 1789.1997,757.6887 ± 194.2047,0.7399 ± 0.1897,0.0165 ± 0.0129,0.0280 ± 0.0222,0.0221 ± 0.0177,0.0268 ± 0.0208,-0.0907 ± 0.0936,14.5578 ± 3.1603
2,3,12543.9374 ± 967.7892,15.2200 ± 32.6152,0.0149 ± 0.0319,0.0000 ± 0.0000,0.0280 ± 0.0222,0.0000 ± 0.0008,0.0268 ± 0.0208,0.1051 ± 0.1389,2.0800 ± 0.7435
3,4,4877.8186 ± 1197.0251,107.0499 ± 104.6931,0.1045 ± 0.1022,0.0001 ± 0.0003,0.0280 ± 0.0222,0.0004 ± 0.0023,0.0268 ± 0.0208,0.0195 ± 0.0568,4.5410 ± 0.8267
4,5,14473.6852 ± 704.0515,10.6460 ± 42.7393,0.0104 ± 0.0417,0.0034 ± 0.0096,0.0280 ± 0.0222,0.0278 ± 0.0659,0.0268 ± 0.0208,0.1772 ± 0.1753,1.6680 ± 0.7297
5,6,9310.9150 ± 1091.0605,36.2626 ± 59.4443,0.0354 ± 0.0581,0.0000 ± 0.0001,0.0280 ± 0.0222,0.0000 ± 0.0013,0.0268 ± 0.0208,0.0779 ± 0.1177,2.6929 ± 0.8635
6,7,5259.4327 ± 1382.5947,30.7405 ± 43.7994,0.0300 ± 0.0428,0.0005 ± 0.0012,0.0280 ± 0.0222,0.0068 ± 0.0171,0.0268 ± 0.0208,0.0678 ± 0.0612,3.9559 ± 0.4961
7,8,6925.9406 ± 991.6360,34.5002 ± 47.4053,0.0337 ± 0.0463,0.0000 ± 0.0001,0.0280 ± 0.0222,0.0001 ± 0.0012,0.0268 ± 0.0208,0.0686 ± 0.0891,3.1697 ± 0.7029

Saved table: figures/KMeans_8/table_layer_cam_all.csv

Layer-CAM - Label 0:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,6377.3347 ± 1045.7299,2.7890 ± 7.7591,0.0027 ± 0.0076,0.0022 ± 0.0051,0.0205 ± 0.0162,0.0446 ± 0.0837,0.0198 ± 0.0155,0.1578 ± 0.1177,2.9593 ± 0.3401
1,2,2838.3682 ± 1580.8537,760.8941 ± 197.9163,0.7431 ± 0.1933,0.0175 ± 0.0135,0.0205 ± 0.0162,0.0237 ± 0.0187,0.0198 ± 0.0155,-0.0635 ± 0.0775,14.7174 ± 3.1946
2,3,12265.7608 ± 612.4163,18.0837 ± 35.1229,0.0177 ± 0.0343,0.0000 ± 0.0001,0.0205 ± 0.0162,0.0000 ± 0.0009,0.0198 ± 0.0155,0.0539 ± 0.0906,1.9304 ± 0.6561
3,4,4583.2563 ± 711.2014,122.9848 ± 106.3759,0.1201 ± 0.1039,0.0001 ± 0.0003,0.0205 ± 0.0162,0.0004 ± 0.0026,0.0198 ± 0.0155,0.0202 ± 0.0531,4.5428 ± 0.8633
4,5,14644.5220 ± 590.0512,0.0692 ± 0.8896,0.0001 ± 0.0009,0.0001 ± 0.0007,0.0205 ± 0.0162,0.0014 ± 0.0130,0.0198 ± 0.0155,0.1257 ± 0.1418,1.4089 ± 0.2987
5,6,8991.3532 ± 647.3652,42.6358 ± 63.1177,0.0416 ± 0.0616,0.0000 ± 0.0001,0.0205 ± 0.0162,0.0001 ± 0.0015,0.0198 ± 0.0155,0.0370 ± 0.0804,2.6075 ± 0.8668
6,7,5047.9196 ± 1155.0600,36.2783 ± 46.1359,0.0354 ± 0.0451,0.0006 ± 0.0013,0.0205 ± 0.0162,0.0083 ± 0.0186,0.0198 ± 0.0155,0.0769 ± 0.0548,3.8575 ± 0.4351
7,8,6637.5506 ± 401.0751,40.2651 ± 49.7305,0.0393 ± 0.0486,0.0000 ± 0.0001,0.0205 ± 0.0162,0.0001 ± 0.0013,0.0198 ± 0.0155,0.0432 ± 0.0726,3.0892 ± 0.6856

Saved table: figures/KMeans_8/table_layer_cam_label_0.csv

Layer-CAM - Label 1:
------------------------------------------------------------

,Cluster,Weight Sum,Cluster Count,Norm Count,Intersection/Pixels,Intersection/Pixels (Soft),IoU,Soft IoU,Correlation,L2 Distance
0,1,6467.7236 ± 1118.8114,166.0146 ± 112.8655,0.1621 ± 0.1102,0.0316 ± 0.0115,0.0624 ± 0.0108,0.1735 ± 0.0815,0.0586 ± 0.0096,0.1536 ± 0.1054,4.2242 ± 0.7647
1,2,4122.2835 ± 2254.9917,742.9164 ± 175.3874,0.7255 ± 0.1713,0.0120 ± 0.0082,0.0624 ± 0.0108,0.0145 ± 0.0084,0.0586 ± 0.0096,-0.2100 ± 0.0573,13.8222 ± 2.8859
2,3,13825.9212 ± 1234.9206,2.0224 ± 8.3113,0.0020 ± 0.0081,0.0000 ± 0.0000,0.0624 ± 0.0108,0.0000 ± 0.0000,0.0586 ± 0.0096,0.3287 ± 0.0791,2.7690 ± 0.7345
3,4,6235.3160 ± 1861.1855,33.6136 ± 52.5590,0.0328 ± 0.0513,0.0000 ± 0.0001,0.0624 ± 0.0108,0.0000 ± 0.0007,0.0586 ± 0.0096,0.0166 ± 0.0707,4.5328 ± 0.6310
4,5,13686.3795 ± 649.1360,59.3892 ± 85.7486,0.0580 ± 0.0837,0.0188 ± 0.0149,0.0624 ± 0.0108,0.1433 ± 0.0785,0.0586 ± 0.0096,0.4021 ± 0.1226,2.8617 ± 0.9170
5,6,10783.6236 ± 1451.3335,6.8918 ± 20.2344,0.0067 ± 0.0198,0.0000 ± 0.0000,0.0624 ± 0.0108,0.0000 ± 0.0003,0.0586 ± 0.0096,0.2567 ± 0.0824,3.0862 ± 0.7288
6,7,6234.1959 ± 1848.7311,5.2193 ± 12.5505,0.0051 ± 0.0123,0.0000 ± 0.0002,0.0624 ± 0.0108,0.0002 ± 0.0018,0.0586 ± 0.0096,0.0278 ± 0.0709,4.4092 ± 0.5079
7,8,8254.9931 ± 1620.2191,7.9327 ± 18.6474,0.0077 ± 0.0182,0.0000 ± 0.0000,0.0624 ± 0.0108,0.0000 ± 0.0003,0.0586 ± 0.0096,0.1793 ± 0.0672,3.5402 ± 0.6620

Saved table: figures/KMeans_8/table_layer_cam_label_1.csv

============================================================
CAM-Cluster Comparison (Label 0 vs Label 1) - KMeans (8 clusters)
============================================================

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0227 ± 0.0462,0.2277 ± 0.1971,2.9728 ± 0.3362,0.2180 ± 0.0715,0.5282 ± 0.1439,3.8281 ± 0.6269
1,2,0.0728 ± 0.0707,-0.0824 ± 0.1394,14.7274 ± 3.1935,0.2358 ± 0.0739,-0.5537 ± 0.1148,13.6713 ± 2.9530
2,3,0.0000 ± 0.0000,0.0667 ± 0.1503,1.8817 ± 0.6495,0.0000 ± 0.0000,0.7010 ± 0.1641,1.8284 ± 0.3680
3,4,0.0000 ± 0.0003,0.0238 ± 0.0999,4.5481 ± 0.8591,0.0000 ± 0.0004,0.0758 ± 0.2047,4.0879 ± 0.4979
4,5,0.0005 ± 0.0057,0.1617 ± 0.2127,1.3554 ± 0.2582,0.0775 ± 0.0776,0.8819 ± 0.0597,2.2103 ± 0.7712
5,6,0.0000 ± 0.0000,0.0433 ± 0.1382,2.5822 ± 0.8632,0.0000 ± 0.0000,0.5866 ± 0.1908,2.3241 ± 0.4422
6,7,0.0001 ± 0.0010,0.1060 ± 0.1079,3.8651 ± 0.4344,0.0001 ± 0.0011,0.1199 ± 0.2030,3.9547 ± 0.3079
7,8,0.0000 ± 0.0000,0.0537 ± 0.1304,3.0810 ± 0.6797,0.0000 ± 0.0000,0.4526 ± 0.1545,2.9358 ± 0.3964

Saved table: figures/KMeans_8/table_grad_cam_cluster_comparison.csv

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0154 ± 0.0344,0.2262 ± 0.1928,2.9063 ± 0.3290,0.2052 ± 0.0713,0.5189 ± 0.1400,3.2934 ± 0.3892
1,2,0.0974 ± 0.0847,-0.0837 ± 0.1347,14.6868 ± 3.1989,0.2566 ± 0.0744,-0.5398 ± 0.1109,13.4930 ± 3.1115
2,3,0.0000 ± 0.0009,0.0651 ± 0.1431,1.9317 ± 0.6686,0.0000 ± 0.0001,0.6829 ± 0.1597,2.5034 ± 0.6178
3,4,0.0017 ± 0.0051,0.0265 ± 0.0967,4.5066 ± 0.8750,0.0017 ± 0.0040,0.0855 ± 0.1889,3.9122 ± 0.7029
4,5,0.0004 ± 0.0043,0.1578 ± 0.2042,1.4084 ± 0.3209,0.0735 ± 0.0757,0.8462 ± 0.0640,2.1305 ± 0.5389
5,6,0.0001 ± 0.0015,0.0419 ± 0.1323,2.5949 ± 0.8771,0.0001 ± 0.0005,0.5733 ± 0.1868,2.6533 ± 0.6563
6,7,0.0231 ± 0.0364,0.1202 ± 0.1004,3.8144 ± 0.4274,0.0029 ± 0.0083,0.1341 ± 0.1797,3.7653 ± 0.4695
7,8,0.0003 ± 0.0019,0.0538 ± 0.1252,3.0619 ± 0.6956,0.0002 ± 0.0009,0.4479 ± 0.1517,2.9639 ± 0.5991

Saved table: figures/KMeans_8/table_grad_cam_pp_cluster_comparison.csv

,Cluster,Label 0 IoU,Label 0 Correlation,Label 0 L2 Distance,Label 1 IoU,Label 1 Correlation,Label 1 L2 Distance
0,1,0.0446 ± 0.0837,0.1578 ± 0.1177,2.9593 ± 0.3401,0.1735 ± 0.0815,0.1536 ± 0.1054,4.2242 ± 0.7647
1,2,0.0237 ± 0.0187,-0.0635 ± 0.0775,14.7174 ± 3.1946,0.0145 ± 0.0084,-0.2100 ± 0.0573,13.8222 ± 2.8859
2,3,0.0000 ± 0.0009,0.0539 ± 0.0906,1.9304 ± 0.6561,0.0000 ± 0.0000,0.3287 ± 0.0791,2.7690 ± 0.7345
3,4,0.0004 ± 0.0026,0.0202 ± 0.0531,4.5428 ± 0.8633,0.0000 ± 0.0007,0.0166 ± 0.0707,4.5328 ± 0.6310
4,5,0.0014 ± 0.0130,0.1257 ± 0.1418,1.4089 ± 0.2987,0.1433 ± 0.0785,0.4021 ± 0.1226,2.8617 ± 0.9170
5,6,0.0001 ± 0.0015,0.0370 ± 0.0804,2.6075 ± 0.8668,0.0000 ± 0.0003,0.2567 ± 0.0824,3.0862 ± 0.7288
6,7,0.0083 ± 0.0186,0.0769 ± 0.0548,3.8575 ± 0.4351,0.0002 ± 0.0018,0.0278 ± 0.0709,4.4092 ± 0.5079
7,8,0.0001 ± 0.0013,0.0432 ± 0.0726,3.0892 ± 0.6856,0.0000 ± 0.0003,0.1793 ± 0.0672,3.5402 ± 0.6620

Saved table: figures/KMeans_8/table_layer_cam_cluster_comparison.csv

============================================================
CAM IoU (All Data) and Correlation (Label 0, Label 1) - KMeans (8 clusters)
============================================================

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.0615 ± 0.0938       0.2277 ± 0.1971       0.5282 ± 0.1439
1        2  0.1018 ± 0.0947      -0.0824 ± 0.1394      -0.5537 ± 0.1148
2        3  0.0000 ± 0.0000       0.0667 ± 0.1503       0.7010 ± 0.1641
3        4  0.0000 ± 0.0003       0.0238 ± 0.0999       0.0758 ± 0.2047
4        5  0.0158 ± 0.0465       0.1617 ± 0.2127       0.8819 ± 0.0597
5        6  0.0000 ± 0.0000       0.0433 ± 0.1382       0.5866 ± 0.1908
6        7  0.0001 ± 0.0010       0.1060 ± 0.1079       0.1199 ± 0.2030
7        8  0.0000 ± 0.0000       0.0537 ± 0.1304       0.4526 ± 0.1545

Saved table: figures/KMeans_8/table_grad_cam_iou_correlation.csv

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.0508 ± 0.0859       0.2262 ± 0.1928       0.5189 ± 0.1400
1        2  0.1258 ± 0.1029      -0.0837 ± 0.1347      -0.5398 ± 0.1109
2        3  0.0000 ± 0.0008       0.0651 ± 0.1431       0.6829 ± 0.1597
3        4  0.0017 ± 0.0049       0.0265 ± 0.0967       0.0855 ± 0.1889
4        5  0.0140 ± 0.0435       0.1578 ± 0.2042       0.8462 ± 0.0640
5        6  0.0001 ± 0.0014       0.0419 ± 0.1323       0.5733 ± 0.1868
6        7  0.0194 ± 0.0340       0.1202 ± 0.1004       0.1341 ± 0.1797
7        8  0.0003 ± 0.0018       0.0538 ± 0.1252       0.4479 ± 0.1517

Saved table: figures/KMeans_8/table_grad_cam_pp_iou_correlation.csv

   Cluster   IoU (All Data) Correlation (Label 0) Correlation (Label 1)
0        1  0.0686 ± 0.0973       0.1578 ± 0.1177       0.1536 ± 0.1054
1        2  0.0221 ± 0.0177      -0.0635 ± 0.0775      -0.2100 ± 0.0573
2        3  0.0000 ± 0.0008       0.0539 ± 0.0906       0.3287 ± 0.0791
3        4  0.0004 ± 0.0023       0.0202 ± 0.0531       0.0166 ± 0.0707
4        5  0.0278 ± 0.0659       0.1257 ± 0.1418       0.4021 ± 0.1226
5        6  0.0000 ± 0.0013       0.0370 ± 0.0804       0.2567 ± 0.0824
6        7  0.0068 ± 0.0171       0.0769 ± 0.0548       0.0278 ± 0.0709
7        8  0.0001 ± 0.0012       0.0432 ± 0.0726       0.1793 ± 0.0672

Saved table: figures/KMeans_8/table_layer_cam_iou_correlation.csv

============================================================
Normalized Cluster Count Comparison - KMeans (8 clusters)
============================================================

   Cluster         All Data          Label 0          Label 1
0        1  0.0311 ± 0.0770  0.0027 ± 0.0076  0.1621 ± 0.1102
1        2  0.7399 ± 0.1897  0.7431 ± 0.1933  0.7255 ± 0.1713
2        3  0.0149 ± 0.0319  0.0177 ± 0.0343  0.0020 ± 0.0081
3        4  0.1045 ± 0.1022  0.1201 ± 0.1039  0.0328 ± 0.0513
4        5  0.0104 ± 0.0417  0.0001 ± 0.0009  0.0580 ± 0.0837
5        6  0.0354 ± 0.0581  0.0416 ± 0.0616  0.0067 ± 0.0198
6        7  0.0300 ± 0.0428  0.0354 ± 0.0451  0.0051 ± 0.0123
7        8  0.0337 ± 0.0463  0.0393 ± 0.0486  0.0077 ± 0.0182

Saved table: figures/KMeans_8/table_norm_count_comparison.csv

============================================================
Annotation Mask Statistics - KMeans (8 clusters)
============================================================


Carcinoma Mask Metrics - All Data (n=1841):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.4200 ± 0.2724,0.5311 ± 0.2455,N/A,NaN
1,Grad-CAM++,0.4471 ± 0.2806,0.5584 ± 0.2502,N/A,NaN
2,Layer-CAM,0.0516 ± 0.0212,0.0920 ± 0.0526,N/A,NaN
3,Cluster 1,0.1402 ± 0.1162,0.1557 ± 0.0866,0.3583 ± 0.1482,0.6330 ± 0.3287
4,Cluster 2,0.4073 ± 0.2422,0.2738 ± 0.1261,0.3583 ± 0.1482,0.6330 ± 0.3287
5,Cluster 3,0.0010 ± 0.0044,0.0017 ± 0.0079,0.3583 ± 0.1482,0.6330 ± 0.3287
6,Cluster 4,0.0217 ± 0.0360,0.0305 ± 0.0443,0.3583 ± 0.1482,0.6330 ± 0.3287
7,Cluster 5,0.0521 ± 0.0820,0.0590 ± 0.0726,0.3583 ± 0.1482,0.6330 ± 0.3287
8,Cluster 6,0.0040 ± 0.0130,0.0068 ± 0.0215,0.3583 ± 0.1482,0.6330 ± 0.3287
9,Cluster 7,0.0022 ± 0.0068,0.0033 ± 0.0110,0.3583 ± 0.1482,0.6330 ± 0.3287
10,Cluster 8,0.0046 ± 0.0116,0.0074 ± 0.0178,0.3583 ± 0.1482,0.6330 ± 0.3287

Saved table: figures/KMeans_8/table_carcinoma_all.csv

Carcinoma Mask Metrics - Predicted Label 0 (n=245):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.0800 ± 0.0938,0.1946 ± 0.1593,N/A,NaN
1,Grad-CAM++,0.0967 ± 0.1128,0.2150 ± 0.1688,N/A,NaN
2,Layer-CAM,0.0199 ± 0.0174,0.0903 ± 0.0879,N/A,NaN
3,Cluster 1,0.0115 ± 0.0189,0.0442 ± 0.0659,0.1697 ± 0.1552,0.2566 ± 0.2855
4,Cluster 2,0.2046 ± 0.2465,0.1526 ± 0.1434,0.1697 ± 0.1552,0.2566 ± 0.2855
5,Cluster 3,0.0011 ± 0.0042,0.0027 ± 0.0103,0.1697 ± 0.1552,0.2566 ± 0.2855
6,Cluster 4,0.0241 ± 0.0432,0.0493 ± 0.0600,0.1697 ± 0.1552,0.2566 ± 0.2855
7,Cluster 5,0.0009 ± 0.0041,0.0035 ± 0.0131,0.1697 ± 0.1552,0.2566 ± 0.2855
8,Cluster 6,0.0062 ± 0.0185,0.0152 ± 0.0374,0.1697 ± 0.1552,0.2566 ± 0.2855
9,Cluster 7,0.0034 ± 0.0100,0.0070 ± 0.0211,0.1697 ± 0.1552,0.2566 ± 0.2855
10,Cluster 8,0.0050 ± 0.0133,0.0117 ± 0.0256,0.1697 ± 0.1552,0.2566 ± 0.2855

Saved table: figures/KMeans_8/table_carcinoma_label_0.csv

Carcinoma Mask Metrics - Predicted Label 1 (n=1596):
------------------------------------------------------------

,Method/Cluster,Intersection/Pixels,IoU (Mean ± Std),IoU Soft (Mean ± Std),Intersection/Pixels (Soft)
0,Grad-CAM,0.4723 ± 0.2525,0.5828 ± 0.2135,N/A,NaN
1,Grad-CAM++,0.5009 ± 0.2592,0.6111 ± 0.2168,N/A,NaN
2,Layer-CAM,0.0565 ± 0.0171,0.0923 ± 0.0449,N/A,NaN
3,Cluster 1,0.1600 ± 0.1122,0.1728 ± 0.0760,0.3873 ± 0.1240,0.6908 ± 0.2950
4,Cluster 2,0.4384 ± 0.2260,0.2924 ± 0.1122,0.3873 ± 0.1240,0.6908 ± 0.2950
5,Cluster 3,0.0009 ± 0.0045,0.0016 ± 0.0074,0.3873 ± 0.1240,0.6908 ± 0.2950
6,Cluster 4,0.0213 ± 0.0348,0.0276 ± 0.0406,0.3873 ± 0.1240,0.6908 ± 0.2950
7,Cluster 5,0.0600 ± 0.0854,0.0676 ± 0.0742,0.3873 ± 0.1240,0.6908 ± 0.2950
8,Cluster 6,0.0036 ± 0.0119,0.0055 ± 0.0175,0.3873 ± 0.1240,0.6908 ± 0.2950
9,Cluster 7,0.0020 ± 0.0061,0.0028 ± 0.0084,0.3873 ± 0.1240,0.6908 ± 0.2950
10,Cluster 8,0.0045 ± 0.0113,0.0067 ± 0.0161,0.3873 ± 0.1240,0.6908 ± 0.2950

Saved table: figures/KMeans_8/table_carcinoma_label_1.csv

============================================================
Carcinoma IoU Comparison - KMeans (8 clusters)
============================================================

   Method/Cluster         All Data          Label 0          Label 1
0        Grad-CAM  0.5311 ± 0.2455  0.1946 ± 0.1593  0.5828 ± 0.2135
1      Grad-CAM++  0.5584 ± 0.2502  0.2150 ± 0.1688  0.6111 ± 0.2168
2       Layer-CAM  0.0920 ± 0.0526  0.0903 ± 0.0879  0.0923 ± 0.0449
3       Cluster 1  0.1557 ± 0.0866  0.0442 ± 0.0659  0.1728 ± 0.0760
4       Cluster 2  0.2738 ± 0.1261  0.1526 ± 0.1434  0.2924 ± 0.1122
5       Cluster 3  0.0017 ± 0.0079  0.0027 ± 0.0103  0.0016 ± 0.0074
6       Cluster 4  0.0305 ± 0.0443  0.0493 ± 0.0600  0.0276 ± 0.0406
7       Cluster 5  0.0590 ± 0.0726  0.0035 ± 0.0131  0.0676 ± 0.0742
8       Cluster 6  0.0068 ± 0.0215  0.0152 ± 0.0374  0.0055 ± 0.0175
9       Cluster 7  0.0033 ± 0.0110  0.0070 ± 0.0211  0.0028 ± 0.0084
10      Cluster 8  0.0074 ± 0.0178  0.0117 ± 0.0256  0.0067 ± 0.0161

Saved table: figures/KMeans_8/table_carcinoma_iou_comparison.csv

================================================================================